### ISSUE TITLE
FYI, a nefarious URL was added to your project wiki python page

### ISSUE THREAD

**Issue by doolio** [direnv/direnv#1021]
I [reverted a commit](https://github.com/direnv/direnv/wiki/Python/_compare/05c83e0a277317d69cf5b1e2a6f1a5335b7715dc...f621b5bd72bde7e812e996d74d7979b04cfa8bc2) made to the project wiki python page. The nefarious commit changed the URL to a `direnv` release to be some kind of IP logger site. I will not include the link here to prevent a user from clicking on it by accident.

**Comment by zimbatm** [comment]
thanks, it looks like @pablorame was the culprit and he already got suspended
