### ISSUE TITLE
Allow `layout python` to use minor versions for the interpreter directory in .direnv

### ISSUE THREAD

**Issue by offbyone** [direnv/direnv#1035]
Currently `layout python` creates a virtualenv in `.direnv/` that has the full python version: `.direnv/python-3.11.1`. This is the most _correct_ location for some definition of _correct_ but it can introduce friction when integrating with IDEs, when upgrading the patch version of the interpreter.

I'd like a way to tell `layout python` to create virtualenvs named after the _minor version_ instead of the patch version. `.direnv/python-3.11` instead of `.direnv/python-3.11.1`

An example describing the problem is here: https://mastodon.social/@hynek/109561175719682337

> And btw it’s a HUGE pain with VS Code because it uses complete version numbers (.direnv/python-3.11.1) which means on every Python update I have to switch the active version in all VS Code projects.

**Edit**

How did I miss #1033? That's exactly what I want the option of doing! I wouldn't do it as the ONLY way, but let me choose, please.

**Comment by zimbatm** [comment]
merged :)
