### ISSUE TITLE
Fish shell - direnv not loading the exported variable

### ISSUE THREAD

**Issue by Beinish** [direnv/direnv#1037]
Hello, I've been using direnv in the past and it worked flawlessly. I've changed my shell to Fish for a while and can't get direnv to work for some reason.

My `~/.config/fish/config.fish`:
```bash
if status is-interactive
    # Commands to run in interactive sessions can go here
end

test -e {$HOME}/.iterm2_shell_integration.fish ; and source {$HOME}/.iterm2_shell_integration.fish
direnv hook fish | source
```

I have a test directory `~/playground` with the following `.envrc` file:
```
❯ cat .envrc
set -x AWS_PROFILE profile
```
When I `cd` into the folder, I get the following:
```
❯ cd playground/
direnv: loading ~/playground/.envrc
+ popd
+ popd
+ __dump_at_exit
+ local ret=0
+ /opt/homebrew/bin/direnv dump json ''
+ trap - EXIT
+ exit 0
```
However the variable is not being set for some reason. Manually running the same `set` command works, so I'm not sure what I'm doing wrong.

A small, maybe unrelated thing I wanted to mention about the `~/.config/fish/config.fish`. In the documentation it says to use `>direnv hook fish | source`, but in my file I removed the `>` because I was getting the following error:
`~/.config/fish/config.fish (line 7): Expected a string, but found a redirection`. Not sure if it's related to the issue but I thought it's worth mentioning.

My Env:
```
Laptop: Macbook Pro M1
OS: Monterey 12.6.2
Terminal: iTerm2
Direnv: 2.32.2
```

Any help would be appreciated.

**Comment by branchvincent** [comment]
Note that `.envrc` is always [executed as bash](https://github.com/direnv/direnv#faq) regardless of your own shell:

> 3. direnv is not loading the `.envrc` into the current shell. It's creating a new bash sub-process ... and only exports the environment diff back to the original shell

So you just need to use `export` over `set -x`

**Comment by Beinish** [comment]
Thank you!
