### ISSUE TITLE
.envrc.local or provide a security framework check for option for source_env_if_exists

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [direnv/direnv#1050]
**Is your feature request related to a problem? Please describe.**
I work in a repository where `.envrc` files have been committed and are shared by all developers.
I'm in need of some custom options, but `.envrc` has been taken.
I solved the problem by committing a `source_env_if_exists .envrc.local`

This comes with a downside: if .envrc.local is modified, there is no security framework check.

Direnv is very useful in simplify dev environments so I can't recommend un-committing `.envrc` either, I wish there was a solution to make everybody happy.

**Describe the solution you'd like**
Direnv could always load two files: `.envrc` and `.envrc.local`, this way there would be room for project settings and user settings

**Describe alternatives you've considered**
An option like `secured_source_env_if_exists` so that I could manually request to check `.envrc.local`

I'm very open to other alternatives, this is only what I came up with

**Additional context**
None

**Comment by gluxon** [comment]
Hey @Fire-Dragon-DoL, I think there's active discussion on a similar request over in https://github.com/direnv/direnv/issues/556. Wanted to point you there in case you haven't seen it yet.

**Comment by Fire-Dragon-DoL** [comment]
> Hey @Fire-Dragon-DoL, I think there's active discussion on a similar request over in #556. Wanted to point you there in case you haven't seen it yet.

Thank you! This can be closed as a duplicate then.
