### ISSUE TITLE
Cannot reference PWD in .env file for variable expansion

### ISSUE THREAD

**Issue by reegnz** [direnv/direnv#1051]
**Describe the bug**
Direnv allows for variable expansion in `.env` files. The `PWD` environment variable is however [removed in the direnv process](https://github.com/direnv/direnv/blob/master/internal/cmd/mod.go#L17) from the environment variables to not interfere with finding .envrc.

**To Reproduce**
In any folder put the following two files:
```.envrc
dotenv
```

```.env
TEST1=$PWD
TEST2=$HOME
```

TEST1 will be empty, while TEST2 will have expanded properly.

**Expected behavior**
PWD in .env files should expand to the folder the .env file resides in.

**Environment**
 - OS: [e.g. macOS Ventura]
 - Shell: [zsh]
 - Direnv version [e.g. 2.32.2]

**Additional context**
Other .env impementations don't have this issue. I've checked the following, which all seem to work as expected:
https://github.com/bkeepers/dotenv
https://github.com/motdotla/dotenv-expand

Both work as expected and expand PWD properly.

**Comment by reegnz** [comment]
This was the original fix that introduced the PWD issue, before dotenv support was introduced: https://github.com/direnv/direnv/commit/c0f171816cd396a9bb9c248098b4325acec1c899

**Comment by reegnz** [comment]
Reading the original issue, I think we have two potential ways to handling PWD:
If `dotenv` is called without args, it's quite clear that PWD can be safely passed to the `direnv dotenv bash` command.

If however we invoke with a non-default path like `dotenv ../../.env` What should PWD be? Should it be the caller's path, or the path where the .env file resides? I think it's unclear, so I'll be preparing a PR only for the most common-case, eg. using `dotenv` without any arguments.

We should discuss in the PR then what the non-default invocation should be.

**Comment by seanorama** [comment]
I'm hitting this as well. Expected to be able to use `${PWD}`.

> if however we invoke with a non-default path like `dotenv ../../.env` , What should PWD be?

It should be the `dirname` of the `.env` file.

**Comment by joeriddles** [comment]
I'm also running into this and finding it frustrating. I'm not familiar with this code base but will try to see if I can make a branch that implements this.

**Comment by reegnz** [comment]
@joeriddles FYI I already had a PR ready for quite a while: https://github.com/direnv/direnv/pull/1052

**Comment by joeriddles** [comment]
> @joeriddles FYI I already had a PR ready for quite a while: #1052

Thanks! I missed that.

**Comment by gsong** [comment]
This issue seems to have resurfaced.

**Comment by reegnz** [comment]
@gsong it has definitely not "resurfaced", because the change hasn't landed in any release yet. What you're experiencing is not a regression but simply the current behavior without this change released yet.
