### ISSUE TITLE
direnv spamming "direnv allow" message

### ISSUE THREAD

**Issue by fushiii** [direnv/direnv#1058]
**Describe the bug**
Whenever a .envrc is not allowed, even though DIRENV_LOG_FORMAT is set to nothing, direnv will keep nagging about the .envrc file not being allowed with each and every command like so:
`direnv: error /$pwd/.envrc is blocked. Run `direnv allow` to approve its content`

**To Reproduce**

1. Enter a folder with a .envrc file
2. Don't allow it
3. Use other commands

**Expected behavior**
Direnv should not keep spamming about having to allow a .envrc file

**Environment**
 - OS: NixOS unstable
 - Shell: elvish
 - Direnv version 2.32.2

**Additional context**
The logs from direnv should be hidden when setting DIREN_LOG_FORMAT to null, but that doesn't happen with the "direnv allow" message.

![image](https://user-images.githubusercontent.com/90937648/218176514-daa33b0d-4809-4eb7-9ec1-a81de2b1be87.png)

**Comment by tmccombs** [comment]
I think there should be an inverse of `allow` that tells direnv that I never want to allow running the .envrc file in a directory. And maybe a "blocklist" configuration in direnv.toml similar to the "whitelist" configuration, that blocks certain folders instead of allowing them.

**Comment by fushiii** [comment]
This hasn't happened with me anymore.
