### ISSUE TITLE
Using direnv to contain Bash history to DIRENV_DIR?

### ISSUE THREAD

**Issue by synthead** [direnv/direnv#1062]
Can I leverage direnv to contain Bash history to DIRENV_DIR?  For example, this is what I am aiming to do:

1. Open a shell in my home directory
   - No .envrc present, Bash history writes to ~/.bash_history as usual
2. Execute some commands on a bash shell
3. cd to a dir with .envrc
   - Current command history is written to ~/.bash_history
   - In-memory history is cleared
   - direnv sets HISTFILE to $DIRENV/.bash_history
   - History is read from $DIRENV/.bash_history
4. Execute more commands on a bash shell
5. cd to my home directory
   - No .envrc present, like before
   - direnv writes the history to $DIRENV/.bash_history from above
   - HISTFILE is set back to ~/.bash_history
   - In-memory history is cleared
   - History is read from ~/.bash_history

With a flow like this :point_up:, I can contain Bash history to direnv-managed directories.  For example, in a Rails project, I may run `rake` or `bundle exec` a bunch, but these commands are meaningless outside of the Rails root (where an .envrc file lives).  Additionally, I can keep general commands that don't pertain to a Rails project outside of the history that would live with the Rails project.

I figured I could call `history -w` and `history -c` to write to file and clear in-memory history, set HISTFILE, and do `history -r`.  However, I can't think of a clever way to perform the same task (write, clear, set env, read) when unloading direnv.

How would you approach this?  Thanks so much in advance, and thanks a ton for direnv!

**Comment by zimbatm** [comment]
Unfortunately, direnv hooks only work with environment variables. Sorry :sweat_smile:

**Comment by synthead** [comment]
That makes sense! :heart:  I was thinking about possibly doing something like...

```shell
export HISTFILE="$(history -w; history -c)$DIRENV/.bash_history"
```

...but this seems like quite a hack :smile:

I'll poke around the 'net for other peoples' solutions and maybe toss together some Bash functions.  Thanks so much!

**Comment by synthead** [comment]
This appears to do the trick nicely!  I have this in my `~/.bashrc`, above any `eval`s for shell hooks, including direnv:

```bash
_set_local_histfile() {
  histfile_local=${DIRENV_FILE%\/*}
  histfile_local=${histfile_local:-$HOME}/.bash_history
  
  [[ "$HISTFILE" == "$histfile_local" ]] && return

  echo "Writing Bash history to $histfile_local"
  
  history -w
  history -c

  export HISTFILE=$histfile_local

  history -r
}

PROMPT_COMMAND=_set_local_histfile
```

**Comment by zimbatm** [comment]
This is great, it would be a good addition to the wiki!

**Comment by kim0** [comment]
@synthead Amazing snippet, was just looking for this. IMO this line needs to be 
> Writing Bash history to $HISTFILE

Thanks!

**Comment by michael-gratton** [comment]
Unfortunately the workaround above seems breaks random things such as "Opening a new tab in the same directory as a current tab" in MacOS Terminal.

**Comment by michael-gratton** [comment]
Ah, fix for the MacOS Terminal issue is:

> PROMPT_COMMAND="_set_local_histfile;${PROMPT_COMMAND}"
