### ISSUE TITLE
Direnv missing entries from `.envrc`

### ISSUE THREAD

**Issue by gf3** [direnv/direnv#1063]
**Describe the bug**
Direnv seems to be missing entries from the `.envrc`/`.env` file

![Screenshot 2023-02-21 at 12 13 39 PM](https://user-images.githubusercontent.com/18397/220414622-1c6149df-5a54-420d-9356-c97c4fea9508.png)

From the screenshot above, you'll notice that there are 14 ENV vars being set in the `.envrc`

The directory has been previously `direnv allow`'d

Calling `direnv reload` to illustrate the issue, shows that none of the environment variables have been correctly loaded.

**Expected behavior**
Envronment variables are correctly added from `.envrc`/`.env` file.

**Environment**
 - OS: `macOS 13.0.1 (22A400)`
 - Shell: `0.75.0`
 - Direnv version: `2.32.1`

**Additional context**
I have recently started using nushell.

**Comment by gf3** [comment]
@zimbatm i was originally using just a `.env` with `load_env = true` in my direnv config when experiencing this issue

however i just tried your suggestion and it still seems to be broken:

![Screenshot](https://screenshot.pics/s/Codefreshlinearowana_2023-02-21_13-07-34.png)

**Comment by zimbatm** [comment]
I suspect that some of the content in your `.env` is not parsed correctly. Try cutting everything below the first two items and see if it fixes the reload.

```
$ cd foo
direnv: loading ~/foo/.envrc
direnv: export +FOO

~/foo via 🐹 v1.19.5 on ☁️  jonas@numtide.com 
$ cat .en
.env    .envrc  

~/foo via 🐹 v1.19.5 on ☁️  jonas@numtide.com 
$ cat .env
FOO=3

~/foo via 🐹 v1.19.5 on ☁️  jonas@numtide.com took 2s 
$ cat .en
.env    .envrc  

~/foo via 🐹 v1.19.5 on ☁️  jonas@numtide.com took 2s 
$ cat .envrc 
dotenv

~/foo via 🐹 v1.19.5 on ☁️  jonas@numtide.com took 2s 
$ echo $FOO
3
```

**Comment by gf3** [comment]
i suspect something must have been up with my shell because the problem seems to have magically fixed itself

thank you for your assistance @zimbatm
