### ISSUE TITLE
layout function not working with `elif` and `else` statements

### ISSUE THREAD

**Issue by zoof** [direnv/direnv#1072]
I'm trying to set up auto activation with a micromamba environment and the `if` portion of the funtion works fine.  But when the `if` condition fails, neither the `elif` nor the `else` portion of the function works.  The `.direnvrc` function is:
```
layout_mamba() {
  eval "$(micromamba shell hook --shell=bash)" # initialize micromamba
  if [ -f ".envrc" ]; then # check for .envrc file
    if [ -n "$1" ]; then # check if environment name is specified
      local env_name="$1" # Explicit environment name from layout command.
    else
      local env_name="" # No explicit environment name so use "base" environment
    fi
    micromamba activate ${env_name}; # activate environment
  elif [ -f "environment.yml" ]; then # check for environment.yml file
    local env_name=`grep name: environment.yml | sed -e 's/name: //'` # Detect environment name from `environment.yml` file
    micromamba activate ${env_name}
  else
    (>&2 echo No environment specified);
    exit 1;
  fi
}
```
I have tried this with both Debian Bookworm (direnv v2.32.1) and Garuda (direnv v2.32.2) with both fish and bash.  Executing the statements within the layout function in a bash shell works to the extent that the `elif` and `else` statements are reached.

**Comment by xiamaz** [comment]
Your if condition will always evaluate to true, as you check whether envrc is specified, but since this code is only evaluated if you have specified a layout mamba instruction in the envrc, this will always be the case.

**Comment by zoof** [comment]
Thank you!  Clearly I didn't fully understand how layouts work.  Following https://github.com/direnv/direnv/wiki/Python#anaconda, I now have it working the way I had originally planned.

**Comment by zoof** [comment]
Now working.
