### ISSUE TITLE
Paths are not properly escaped

### ISSUE THREAD

**Issue by CoolingTool** [direnv/direnv#1073]
**Describe the bug**
On some commands direnv will trigger escape sequences in paths.

**To Reproduce**
![image](https://user-images.githubusercontent.com/62089272/224531310-e1566591-918a-4257-abd4-e2d0c37a954e.png)

**Expected behavior**
direnv allow should run fine.

**Environment**
 - OS: Windows 11 Home
 - Shell: nushell (using [this direnv hook](https://www.nushell.sh/cookbook/direnv.html)) and setting DIRENV_BASH to cygwin's bash
 - Direnv version: 2.32.2

**Additional context**
Might just be a cygwin issue.

**Comment by CoolingTool** [comment]
ok so it seems like I had a badly configured cygwin installation that didn't have access to cygpath and I actually couldn't load anything

after fixing it tho, it still can't load paths that have folders that start with b or n

**Comment by lukawolf** [comment]
The same with t... It gets expanded into tab
