### ISSUE TITLE
Avoid "is taking a while to execute. Use CTRL-C to give up" warning for commands that are not supposed to finish

### ISSUE THREAD

**Issue by ostrolucky** [direnv/direnv#1084]
I need to run separate shell session (I'm using `nix develop`) command for this. However, direnv complains for these with

`direnv: ([/nix/store/bav6wajkryhkvzkpncisr6xfbd4qvw1j-direnv-2.32.2/bin/direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.
`

Is there a way to disable this waiting in direnv? Because really, after cd to directory, I expect to enter this bash session and stay inside indefinitely.

**Comment by BeyondEvil** [comment]
I want this too. Or at least being able to set the timeout.

**Comment by ostrolucky** [comment]
I've dropped direnv because of this and now use zsh's `chpwd_functions` https://github.com/nix-community/nix-direnv/issues/324#issuecomment-1490085474

**Comment by BeyondEvil** [comment]
Ouf, harsh, haha.

I'm happy with direnv, this is just a minor inconvenience for my setup.

**Comment by YellowOnion** [comment]
You should be using `use_flake` from something like `nix-direnv`, or import the nix develop environment: https://github.com/direnv/direnv/wiki/Nix#hand-rolled-nix-flakes-integration

This feels like a squaring a circle kind of deal, direnv is for staying in the current shell, not calling in to a new one.

**Comment by e-nikolov** [comment]
https://github.com/direnv/direnv/issues/272 

There is an environment variable that can be set in the .envrc file  to increase the timeout

```
export DIRENV_WARN_TIMEOUT=1m
```

**Comment by ostrolucky** [comment]
I know. I think what we are asking here is to be able to set `DIRENV_WARN_TIMEOUT=0`
