### ISSUE TITLE
Plans for aliases?

### ISSUE THREAD

**Issue by blackxored** [direnv/direnv#109]
It would be handy if I can use the .envrc to setup project specific aliases as well:

```
alias deploy="bundle exec rspec && gps origin && BRANCH=master cap production deploy"
```

This doesn't work.

**Comment by mcnichol** [comment]
@zimbatm - Strange question resurrecting the dead here...

In this directory, if I wanted to call up this _alias_ with a `dep[TAB]` it wouldn't work.  (because I can't tab out bash scripts without being in the directory and doing something like `./dep[TAB]`

Any thoughts on working around this?

**Comment by zimbatm** [comment]
yeah it's best to open new issues.

try adding `PATH_add .` to the `.envrc`. Once the project root is in the path the script will be found by bash.
