### ISSUE TITLE
Workaround NixOS/nix#3121 by vendoring flake

### ISSUE THREAD

**Issue by j-baker** [direnv/direnv#1103]
**Is your feature request related to a problem? Please describe.**

I have a dev environment for a large project. It's a 3d game, and contains gigabytes of assets. Each time a flake computation occurs, due to [nixpkgs/nix#3121](https://github.com/NixOS/nix/issues/3121) the flake evaluation takes _forever_ because the whole directory is copied into the store.

For purposes of direnv, this is basically the opposite of what you want - you want to evaluate your dev-shell, and it shouldn't really depend on random files you have in your repo. Your nix build, certainly.

**Describe the solution you'd like**

I worked around this for myself by creating an .envrc like

```
SHA=$(cat flake/** | sha256sum | cut -d' ' -f 1)
CACHE_PATH=~/.sparseflake/$SHA
if [ ! -d $CACHE_PATH ]; then
  mkdir -p $CACHE_PATH
  cp -r flake $CACHE_PATH
fi
use flake $CACHE_PATH/flake
```

This approach totally solves my problem, as by vendoring the flake, the rest of the tree is no longer copied.

I'd love direnv to perform this optimisation automagically on behalf of the user.

**Describe alternatives you've considered**

I obviously can solve this myself. I figured it might be helpful for others for direnv to work around on behalf of the use given its focus on speed.

**Additional context**

**Comment by bbenne10** [comment]
If I understand the report correctly, this is not a direnv bug at all and should be closed here and addressed at https://github.com/nix-community/nix-direnv/issues/347
