### ISSUE TITLE
source_up from Git root

### ISSUE THREAD

**Issue by rawkode** [direnv/direnv#1133]
**Is your feature request related to a problem? Please describe.**

I work mostly in monorepos and use `source_up` quite heavily. However, as I add more `source_up` calls, I'm finding that I also need to include a global.

For this, I use `source_up ../../../../.envrc`

This works, but I think there's a better solution.

**Describe the solution you'd like**

`source_up git://.envrc`

Where `git://` starts at the closest discovered Git root directory

**Describe alternatives you've considered**

`source_up ../../../../.envrc`

It works, but it's a little messy

**Additional context**

**Comment by zimbatm** [comment]
I didn't test it but something like this should work:

```
source_up_git() {
  local git_config
  git_config=$(find_up .git/config)
  if [[ -z $git_config ]]; then log_err ".git/config not found"; return 1; fi
  source_env "$(dirname "$(dirname "$git_config")")"
}
```

you can then stick it in your direnvrc to use it between projects

**Comment by rawkode** [comment]
This is great for my own personal repositories, but I'd love to have something standard that could be in my OSS monorepos too.

Perhaps, inline with existing functions, it should be: `git_source_up: .envrc`

**Comment by zimbatm** [comment]
Can you link me to the projects where you would use this function?

**Comment by rawkode** [comment]
Thinking about this more, perhaps the Git approach isn't what I'm actually needing.

I think I want `source_up_all` where it recursively finds `.envrc` files and sources them, perhaps using the Git root as a stop point, followed by `max_depth` ?

The repository is here:

https://github.com/RawkodeAcademy/RawkodeAcademy

We have a top level `.envrc` with some common environment variables:

https://github.com/RawkodeAcademy/RawkodeAcademy/blob/main/.envrc

Then I started working on the CMS:

https://github.com/RawkodeAcademy/RawkodeAcademy/blob/main/projects/rawkode.academy/cms/.envrc

Then the CMS needed some deployment automation and I realised `source_up` wasn't quite doing what I expected:

https://github.com/RawkodeAcademy/RawkodeAcademy/blob/main/projects/rawkode.academy/cms/deploy/.envrc

**Comment by rawkode** [comment]
Related: https://github.com/direnv/direnv/issues/652

**Comment by rawkode** [comment]
I'm now just chaining source_up throughout my repo and it works fine
