### ISSUE TITLE
Using direnv with Cygwin

### ISSUE THREAD

**Issue by CMCDragonkai** [direnv/direnv#116]
Specifically, the linux versions give a format error when used with Cygwin. The windows version works, but it has problems with the paths when executed inside Cygwin.

So when I use Cygwin and try this command `direnv allow .envrc`,

it gives me this:

`direnv: error LoadConfig() Lookpath failed: "exec: \"C:\\\\Users\\\\CMCDragonkai\\\\bin\\\\direnv\": file does not exist"`

Changing the binary direnv to direnv.exe seems to have solved the above error. But now nothing gets loaded.

**Comment by vshih** [comment]
I submitted https://github.com/direnv/direnv/pull/431.
