### ISSUE TITLE
Unknown target shell 'pwsh'

### ISSUE THREAD

**Issue by Sacro** [direnv/direnv#1183]
**Describe the bug**
`direnv hook pwsh` doesn't work

**To Reproduce**
```pwsh
direnv hook pwsh
```
results in

```pwsh
direnv: error unknown target shell 'pwsh'
```

**Expected behavior**
Print the code to establsh the hook

**Environment**
 - OS: Windows 11 22H2 22621.2428
 - Shell: Powershell 7.3.8
 - Direnv: 2.32.3

**Additional context**
Installed via [scoop](https://scoop.sh/) if that makes any difference

**Comment by yipengsun** [comment]
Same error here with Windows 11.

**Comment by zimbatm** [comment]
I need to cut a new release. Right now this is only available if you build direnv from source.

**Comment by Ryonez** [comment]
Just a head up, new user and ran into this issue.

**Comment by JustinBrower** [comment]
@Ryonez Did you find a way around it? Just ran into this myself.

**Comment by Ryonez** [comment]
> @Ryonez Did you find a way around it? Just ran into this myself.

Built from source myself, and added it to the PATH.

**Comment by zimbatm** [comment]
Fixed. v2.33.0 is out!

**Comment by nicksettoon** [comment]
wow. went through all the work to make a scoop install that compiles from source. *sigh* oh well, thanks a ton!!!! (not sarcasm)

**Comment by zimbatm** [comment]
ok, I didn't realize this feature would be needed so much. oh well :)

**Comment by Sacro** [comment]
I wouldn't have raised the ticket if you hadn't offered it as a feature!

**Comment by hwine** [comment]
But the `winget` version is still at 2.23.3 😉 (releases are hard)

**Comment by zimbatm** [comment]
who is taking care of the winget release?
