### ISSUE TITLE
use() in stdlib seems to clash with gvm use $1

### ISSUE THREAD

**Issue by aussielunix** [direnv/direnv#128]
I want to hook direnv and gvm together.

I have an `.envrc` 

```
gvm use $1
layout go
```

Whenever I cd into that dir I get:

```
direnv: loading ~/.direnvrc
direnv: loading .envrc
ERROR: Unrecognized command line argument: 'use'
direnv: export +GOPATH ~PATH
```

From what I can tell this is a clash of the method [use](https://github.com/zimbatm/direnv/blob/master/stdlib.sh#L322-L327) but I could be wrong.

**Comment by michaelmior** [comment]
@aussielunix Could you explain what you did to fix your problem? I don't see the info in the wiki.

**Comment by zimbatm** [comment]
You can do something like this.

Create or add to your `~/.direnvrc`:
```
use_go() {
  # FIXME: gvm root might vary
  source $HOME/.gvm/scripts/gvm
  gvm use "$@"
}
```

And then in any `.envrc` file:
```
use go 1.4
```

I haven't tested that out. Can you add it to the wiki if it works for you ?

**Comment by michaelmior** [comment]
I'm not using `direnv` actually, but I was having a related problem. That looks like it would work correctly though. Although did you mean `use_go` instead of `use go`?

**Comment by zimbatm** [comment]
In direnv `use` is a dispatch command. Both will work.

If you're not using direnv and just installed gvm using their install script, it writes the `source ...` line in your `~/.bashrc`. Restarting your shell would probably fix the issue.
