### ISSUE TITLE
Matrix room?

### ISSUE THREAD

**Issue by hjkatz** [direnv/direnv#1290]
**Describe the bug**
Is the matrix room linked in the docs correct? I can't seem to connect to https://app.element.io/#/room/#direnv:numtide.com am seeing a 404 in the js console.

**To Reproduce**

**Expected behavior**

**Environment**
 - OS: [e.g. macOS Mojave, Ubuntu 18.04, ...]
 - Shell: [e.g. bash, zsh, ...]
 - Direnv version [e.g. 2.20.0]

**Additional context**

**Comment by zimbatm** [comment]
The server was down for a bit, it should be back up now!
