### ISSUE TITLE
direnv in a VS Code Integrated Terminal stopped working automatically.

### ISSUE THREAD

**Issue by richard-scott** [direnv/direnv#1307]
**Describe the bug**
I have direnv setup with my Bash Shell on macOS using the following in my ~/.bash_profile:
eval "$(direnv hook bash)"

When I open an Intergated Terminal in VS Code in a directory that I have previously authorised for direnv to process I have to manually run `direnv allow .` to get the .envrc file to be processed.

**To Reproduce**
Setup and use direnv in VS Code on macOS.

**Expected behavior**
It used to parse the .envrc file contents automatically.

**Environment**
 - OS: [macOS Sonoma 14.5]
 - Shell: [bash]
 - Direnv version [2.34.0]

**Additional context**
Until recently, it all used to work perfectly.

**Comment by richard-scott** [comment]
Oh, and when I run `direnv status` in my directory with the .envrc it shows the current directory listed as an a 'Loaded RC path' entry.

if I delete the config stores:
```
rm -rf /Users/richard/.config/direnv/ /Users/richard/.local/share/direnv
```
I then get prompted for `Run `direnv allow` to approve its content`.
I run that to allow the .envrc file to get processed and it works in that shell instance.

If I then quit the bash terminal, and open it again (the integrated terminal in VS Code). I no longer get the prompt for approval, and my .envrc file isn't processed.

**Comment by richard-scott** [comment]
I've just noticed that if I launch the integrated terminal in VS Code in a folder that has an .envrc file the file is initially ignored. 

However, if I then ```cd ..``` out of that directory, direnv unloads and when I change back into the directory with the previously ignored .envrc file, it gets processed and works fine.

**Comment by mkhl** [comment]
This sounds like it might be direnv/direnv-vscode#561, do you have the direnv extension installed?

In that case what's happening would be this:
- direnv is setting up an environment *inside VSCode*
- you're starting a terminal, which starts a shell, where that environment set up by direnv is present
- your shell startup files clobber the environment set up by direnv and set variables, including PATH
- direnv inside the shell notices that it has already run and so doesn't "fix" the variables clobbered by your shell startup files

The easiest workaround would be to add `direnv reload` to where you're loading direnv, maybe conditional on a variable like `DIRENV_DIFF` being set.

The full fix would be to make sure your shell startup files are idempotent, i.e. they don't modify environment variables that they have already modified.

**Comment by richard-scott** [comment]
The removal of the VS Code direnv extension solved my issue. Thanks.

**Comment by programuoju** [comment]
Removing `direnv` VS code extension and deleting local `.direnv` directory worked for me as well. 

Thank you @richard-scott !

**Comment by pucinsk** [comment]
Removing `direnv` VS code extension and deleting local `.direnv` directory worked for me as well. 

Thank you @richard-scott 🙏
