### ISSUE TITLE
${PWD} not expanded properly using dotenv

### ISSUE THREAD

**Issue by gsong** [direnv/direnv#1331]
**Describe the bug**

`${PWD}` isn't expanded 

**To Reproduce**

```
$ cat .envrc
dotenv

$ cat .env
FOO=${PWD}/foo
BAR=${HOME}/bar

$ direnv reload
direnv: loading ~/Downloads/test-direnv/.envrc
direnv: export +BAR +FOO

$ echo $FOO
/foo

$ echo $BAR
/Users/george/bar

$ direnv --version
2.34.0
```

**Expected behavior**

`${PWD}` to be shell expanded properly.

**Environment**

```
$ sw_vers
ProductName:            macOS
ProductVersion:         15.0.1
BuildVersion:           24A348

$ echo $SHELL
/opt/homebrew/bin/bash

$ direnv --version
2.34.0
```

**Additional context**

This was supposedly resolved by #1052, and reported in #1051.

**Comment by reegnz** [comment]
#1051 hasn't been released yet so this issue is moot.
Just wait for a release.

**Comment by zimbatm** [comment]
finally got around to do release v2.34.0

**Comment by gsong** [comment]
> finally got around to do release v2.34.0

Much appreciated. Confirmed that it worked.
