### ISSUE TITLE
Usage of 'read' within .envrc possible?

### ISSUE THREAD

**Issue by toao** [direnv/direnv#148]
I get an error if I try to use `read` within my .envrc file to read user input. The .envrc looks like this:

```
#!/bin/bash
read foo
echo $foo
```

It dies with the following error:

```
direnv: loading .envrc
direnv: error exit status 1
```

If I execute is manually via `bash .envrc` it works as expected.

Is this a known bug (or feature) and is there any way to make this work? Any help is highly appreciated.

Cheers,
Raik

**Comment by rvandanp** [comment]
can any one help me here ?

direnv: error LoadConfig() Getwd failed: "stat .: no such file or directory"

**Comment by zimbatm** [comment]
Please create a new issue instead of hijacking another thread. I recommend also putting the output of `ls -la ~/.config/direnv`
