### ISSUE TITLE
python anaconda support

### ISSUE THREAD

**Issue by rmorgans** [direnv/direnv#166]
This works for me to add conda (http://continuum.io/open-source/conda) package management to python

in my ~/.direnv

``` bash
layout_anaconda() {
  local ANACONDA_HOME="/opt/anaconda"
  PATH_add "$ANACONDA_HOME/bin"
  source activate $1
}
```

and my .envrc

```
layout anaconda root
```

**Comment by zimbatm** [comment]
Nice. You can add it in the wiki if you want: https://github.com/zimbatm/direnv/wiki#tools-integration

**Comment by peterfpeterson** [comment]
I just added a version of this to https://github.com/direnv/direnv/wiki/Python#-anaconda

**Comment by zimbatm** [comment]
Ok I think that this issue can be closed now
