### ISSUE TITLE
"dump" test case is broken

### ISSUE THREAD

**Issue by punitagrawal** [direnv/direnv#175]
The dump test case fails if direnv is not already installed in the system. I hit this when building direnv in a chroot that didn't already have direnv installed.

On further investigation, I found that 'bash -l -c "direnv dump"' from test/scenarios/dump/.envrc fails as bash can't find the direnv binary. I tried a few different ways to pass an updated PATH to the new shell but couldn't get it to work.

Also if the test succeeds, it's checking the already installed version of direnv as opposed to the newly built one.

**Comment by zimbatm** [comment]
Is it possible that direnv wasn't compiled in the root directory of the project ?

https://github.com/direnv/direnv/blob/master/test/direnv-test.sh#L7 adds the project root onto the $PATH. This is where the binary should be found.

**Comment by zimbatm** [comment]
I should probably add a check for it's existence at the top of the tests.

**Comment by punitagrawal** [comment]
I should've mentioned this in the issue.

direnv was indeed compiled before the tests were run. And I noticed the
update to the PATH in the test script.

The problem arises because the PATH variable isn't inherited when you
create a new shell as is done in test/scenarios/dump/.envrc where direnv is
invoked using "bash -l -c direnv dump" [0].


[0]
https://github.com/direnv/direnv/blob/master/test/scenarios/dump/.envrc#L5

**Comment by zimbatm** [comment]
The `-l` is likely the culprit. 9b60b43216d6c1c58ea1b9e74a483619acefbb65 should fix the issue.

**Comment by punitagrawal** [comment]
On Mon, Jul 13, 2015 at 8:11 PM, zimbatm <notifications@github.com> wrote:

> The -l is likely the culprit. 9b60b43
> <https://github.com/direnv/direnv/commit/9b60b43216d6c1c58ea1b9e74a483619acefbb65>
> should fix the issue.
>

Indeed. Dropping the -l fixes it for me.

Thanks

**Comment by zimbatm** [comment]
Do you need me to make a new release for packaging ?

**Comment by punitagrawal** [comment]
No, I can fix it up locally and drop it when the upstream release with the
fix appears.

Just to be clear, this isn't a blocker. I came across this when trying to
update to 2.6.1

**Comment by punitagrawal** [comment]
[0] https://packages.debian.org/sid/direnv

**Comment by zimbatm** [comment]
Sweet thanks a lot for reporting and for the debian package !

**Comment by zimbatm** [comment]
(it's fixed in master)
