### ISSUE TITLE
eval error in zsh

### ISSUE THREAD

**Issue by siddharthist** [direnv/direnv#176]
This may be a stupid question, but I'll try my best:
### Error:
```
(eval):1: bad pattern: ^[[01
```
### Steps to reproduce:
Name this file .env instead of .envrc:
```
#!/bin/zsh
dependencies=$PWD/.godeps
export GOPATH=$PWD:$dependencies
export GOBIN=$PWD/bin:$dependencies/bin
export PATH=$PATH:$PWD/bin:$dependencies/bin
```
### Expected behavior:
.env and .envrc files load the same, with no problems. To be clear, it still sets variables properly, it just also echoes that message. 
### Information:
```
$ zsh --version
zsh 5.0.8 (x86_64-unknown-linux-gnu)
```
```
$ yaourt -Q direnv
local/direnv 2.6.0-1
```
```
$ cat ~/.zshrc
[...]
eval "$(direnv hook zsh)"
```

**Comment by zimbatm** [comment]
Hi @siddharthist,

the `.envrc` is actually loaded inside of a bash sub-shell by direnv so the behavior might differ from zsh. How is the file loaded once it's been renamed to `.env` ? direnv only looks for `.envrc` files at the moment. It's possible to load a subset of the `.env` syntax if you use the `dotenv` directive inside of an `.envrc` file.

**Comment by siddharthist** [comment]
If direnv only loads .envrc files, then the problem must be on my end. Thanks for clarifying its behavior!

**Comment by zimbatm** [comment]
It shouldn't break on unload though. Feel free to re-open if you're seeing similar errors.
Also you can check the stdlib for the `dotenv` command: http://direnv.net/#man/direnv-stdlib.1

**Comment by turboMaCk** [comment]
I'm getting similar error `(eval):1: bad pattern: ^[[31mdirenv:` when ever I have `.envrc` file which is not allowed and when ever I run `direnv deny`.
