### ISSUE TITLE
does not restore overwritten env variables

### ISSUE THREAD

**Issue by juliantaylor** [direnv/direnv#181]
direnv does not restore environment variables that have been overwritten inside a directory.
this would be useful for me as I have a set of variables that are valid in the whole system except some folders. But each time I enter and exit one of these folders the my global environment is broken.

```
/tmp$ mkdir test
/tmp$ cd test
/tmp/test$ echo export FOO=inside > .envrc; direnv allow
direnv: loading .envrc
direnv: export +FOO
/tmp/test$ cd ..
direnv: unloading
/tmp$ FOO=outside
/tmp$ echo $FOO
outside
/tmp$ cd test
direnv: loading .envrc
direnv: export +FOO
/tmp/test$ echo $FOO
inside
/tmp/test$ cd ..
direnv: unloading
/tmp$ echo $FOO

/tmp$ direnv
direnv v2.6.1
```

**Comment by zimbatm** [comment]
Hi @juliantaylor ,

the issue is that the FOO from the outside is not an exported variable so direnv doesn't detect it. If you run:
```
cd /tmp
export FOO=outside
```
then the variable is going to get restored. The direnv line should look like (~ instead of +):
```
direnv: export ~FOO
```

**Comment by juliantaylor** [comment]
ah that makes sense.
thank you
