### ISSUE TITLE
Cannot `make install`

### ISSUE THREAD

**Issue by hdavidzhu** [direnv/direnv#183]
Following the instructions here: https://github.com/direnv/direnv#from-source

```
go fmt
make: go: Command not found
make: *** [direnv] Error 127
```

**Comment by zimbatm** [comment]
Did you install go before-hand ? If you just want the binary you can grab it following these instructions:
https://github.com/direnv/direnv/wiki/Custom-builds

**Comment by hdavidzhu** [comment]
Sorry this is completely my fault. Even though Golan was listed as a dependency it completely went over my head.

**Comment by zimbatm** [comment]
No worries :)
