### ISSUE TITLE
Trouble installing the latest direnv from master branch

### ISSUE THREAD

**Issue by wilmoore** [direnv/direnv#186]
I am having trouble installing the latest `direnv` from master:

```sh
brew uninstall --force direnv
```

and install from head:

```sh
brew install --HEAD direnv
```

Unfortunately, I do not believe I got what I was expecting. I was expecting to have the `use node` directive available; however, it simply isn't there.

To ensure I wasn't missing something, I checked the man page:

```sh
man direnv-stdlib
```

I noticed that there was no `use node` section in that man page. That tells me that there is something amiss. I wonder if this is a homebrew issue or if there is something I missed?

**Comment by zimbatm** [comment]
try again, the stdlib wasn't compiled into the `stdlib.go` file

**Comment by zimbatm** [comment]
I believe this should solve your issue but please re-open if it's not the case

**Comment by wilmoore** [comment]
:+1:
