### ISSUE TITLE
Override Merge, don't wipe, ancestor envrc's with subdirectory envrc's

### ISSUE THREAD

**Issue by mcandre** [direnv/direnv#201]
A commonly desired pattern is:

```
$ tree coolproject
coolproject
|--- .envrc
|--- subproject
      |--- .envrc
```

Where the top-level coolproject/.envrc settings that are not directly overwritten in subproject/.envrc, are maintained.

**Comment by zimbatm** [comment]
Right now you can achieve something similar by adding `source_up` (which is part of the direnv stdlib) in your subproject's `.envrc`. I agree that direnv's default behaviour is debatable but I like that it's explicit.

**Comment by mcandre** [comment]
Eh, good enough for now

**Comment by zimbatm** [comment]
Cool. Thanks for the idea
