### ISSUE TITLE
How best to quiet direnv?

### ISSUE THREAD

**Issue by mcandre** [direnv/direnv#203]
Does direnv offer a global configuration option to stop showing loading/unloading messages, or should I just `alias direnv='direnv 2>&1 >/dev/null'` ?

**Comment by zimbatm** [comment]
If you `export DIRENV_LOG_FORMAT=` it should do the trick

**Comment by mcandre** [comment]
Works on my machine tm

**Comment by con-f-use** [comment]
I'd like to have the option to quiet direnv in a `.envrc` file, i.e. just for the specific env I'm working in. `export DIRENV_LOG_FORMAT=` is kinda global, and has the added problem of that if you activate another direnv, the log format bleeds into that one.

**Comment by StudioLE** [comment]
For anyone else coming across this `export DIRENV_LOG_FORMAT=` has to be placed before the `direnv hook` or `direnv export` call

**Comment by krobelus** [comment]
Somehow it doesn't work for me:

```
export DIRENV_LOG_FORMAT=
direnv hook fish | source
```

```
$ cd kak-ansi/
direnv: loading ~/git/kak-ansi/.envrc
direnv: using flake
```

it still prints loading/unloading logs

**Comment by safareli** [comment]
if you have output like this
```
direnv: loading ~/dev/my/repo/.envrc
direnv: export +BLA +BLA +BLA +BLA +BLA
```

and want to only see loading and not all exported env vars which takes lot of real estate  this is what workes:

```toml
[global]
log_filter="^loading"
```

**Comment by bdesham** [comment]
It’s also possible to use ANSI escape sequences (a.k.a. color codes) to make the direnv output dimmer without hiding it entirely. I described this approach in [this blog post](https://esham.io/2023/10/direnv).

**Comment by rwese** [comment]
I had to do the regex // too

```toml
[global]
log_filter="/^loading/"
```

```
direnv --version
2.37.1
```

**Comment by huyz** [comment]
For me there must not be regex `/` delimeters.  Same version of direnv
