### ISSUE TITLE
Any chances of having binaries for the latest release?

### ISSUE THREAD

**Issue by RedX2501** [direnv/direnv#211]
The older releases used to have binaries attached to them. That was fantastic as I don't have a go development environment.

Will you provide binaries for the latest release aswell?

**Comment by zimbatm** [comment]
I think we lost them since I moved the repo to it's own org. I will have a look at restoring the builds but Travis is causing me some pain.

**Comment by zimbatm** [comment]
Fixed in release [v2.8.1](https://github.com/direnv/direnv/releases/tag/v2.8.1)
