### ISSUE TITLE
Inaccurate path in fish shell, in tmux

### ISSUE THREAD

**Issue by AKST** [direnv/direnv#213]
Not sure if it's an already known issue, but direnv seems to be altering my $PATH (or using an older version) in `fish` shell while I'm using tmux, and this is the case even when I'm not in a directory or (child directory of a parent directory) with a .envrc file

**Comment by zimbatm** [comment]
Hi, this is an issue with tmux who breaks the assumptions direnv can make. I updated the wiki page for fish, let me know if this works for you: https://github.com/direnv/direnv/wiki/Tmux

**Comment by AKST** [comment]
Looks like I'm no longer experiencing the same issue as before, if I have any issues I'll follow up, otherwise this issue can be closed. Cheers!

**Comment by zimbatm** [comment]
Great. The rule of thumb is to make sure the direnv environment is unloaded before starting tmux and then it's fine.
