### ISSUE TITLE
intellij idea IDE File Watchers plugin

### ISSUE THREAD

**Issue by nalipaz** [direnv/direnv#215]
I use direnv in my shell already. I also use intellij idea IDE to code, and I am trying to setup a File Watcher to watch for changed files in the project directory then run a command in that directory. This all works but I can't seem to figure out why the `.envrc` is not sourced. I have attempted manually sourcing the `.envrc` too, but I guess I am a little unsure of the command to do so. Currently the script I run on file changes is:
```
#!/bin/bash
DIR="$( cd "$(dirname $( dirname "${BASH_SOURCE[0]}" ))" && pwd )"
source ~/.bashrc
cd "$DIR" && direnv reload
echo "$DIR"

echo $USER
echo $PROJECTDIR
exit 1
```
My `.envrc` looks like:
```
export PROJECTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
```
And output of the `$PROJECTDIR` variable works fine when in a terminal. However, when intellij ide runs the same bash file from above the `$PROJECTDIR` variable is empty whilst all the other variables look correct. Thanks for any assistance.

**Comment by nalipaz** [comment]
For more info, I have now done the following without any resolution:

add this to my script:
```
shopt -s expand_aliases
```
Editing my `~/.bashrc` to comment the following:
```
# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac
```
I am on Debian Jessie.

**Comment by nalipaz** [comment]
So reading through the community support on intellij website I was able to see that the file watcher run a non-interactive shell.

I guess a better question at this point might be, how do I load the aliases in an non-interactive shell? Can I run a command to load them before I run the rest of my commands? Thanks

**Comment by zimbatm** [comment]
Hi @nalipaz. I don't know exactly how intellij works but I think I know what the issue is.

What you want is to do something like this:

```bash
#!/bin/bash
DIR="$( cd "$(dirname $( dirname "${BASH_SOURCE[0]}" ))" && pwd )"
cd "$DIR"
# That what's executed on every prompt, but you don't have a prompt here.
# See `direnv hook bash`
eval "$(direnv export bash)"

echo "$DIR"
echo $USER
echo $PROJECTDIR
exit 1
```

**Comment by nalipaz** [comment]
This seems promising, I will give it a try later today, thanks!

**Comment by nalipaz** [comment]
That worked beautifully. Thanks so much.

**Comment by zimbatm** [comment]
Great !

**Comment by tmaslen** [comment]
Hi @nalipaz, are you able to share your full solution? I'm attempting to do the same thing, can get the script to run direnv, but am unable to get my application to pick up the env vars set when the script runs.

Thanks,
/t

**Comment by nalipaz** [comment]
@tmaslen I just ran this and added it as part of setup instructions for people who are using my project:

```
echo 'eval "$(direnv hook bash)"' >> ~/.bashrc
```

Best!
