### ISSUE TITLE
Load environment without `cd` into directory

### ISSUE THREAD

**Issue by russellseymour** [direnv/direnv#228]
Is it possible to load up the `direnv` without using `cd` into the directory?

I am reconfiguring our Jenkins server so that it uses `chruby` and `direnv` to replace `rvm`.  I have got the initial steps of the build writing out the `.envrc` file and `.ruby-version` but it is not being "activated".

If I SSH onto the machine and `cd` into the workspace then environment activates as expected, but this is an interactive login.

I understand that Jenkins is not an interactive login which is where I suspect the issues are.  I am trying to use the following script:

```bash
#!/bin/bash
eval "$(direnv hook bash)"
echo "2.3.1" > .ruby-version
echo "use_ruby" > .envrc
direnv allow .
which ruby
```

The `which` always comes back with the rvm version.  I have added the `eval` to the `.bashrc` for the jenkins user and restarted the service but it is not doing what I need it to.

I am hoping there is a simple command I can run to make this run properly.  Thanks for any advice.

**Comment by zimbatm** [comment]
Yes, in a bash context you can use `eval "$(direnv export bash)"`.

The issue is that the hook only works in an interactive shell because it's executed before every prompt. If you look at the output of `direnv hook bash` you'll see that it basically sets a callback to that previous command.

**Comment by russellseymour** [comment]
@zimbatm Thanks for that.  I think there was a clash with RVM which was why the path to the ruby was not correct.

However the reason I wanted to use `direnv` was so that the gems for each project and installed locally in the `.direnv` directory, but this is not happening.

I have got the `use_ruby` function in the `.direnvrc` for the Jenkins user, but as the build is not an interactive login I assumed that this was not being sourced.  So I copied the `use_ruby` function into the `.envrc` for the project.  But the gems are not being installed in the local dir still.

This is the build step I am running

```bash
#!/bin/bash -ex
echo "2.3.1" > .ruby-version
cp /home/jenkins/envrc .envrc
eval "$(direnv hook bash)"
direnv allow .
gem install bundle
```

The `/home/jenkins/envrc` file contains the following:

```bash
  source /usr/local/share/chruby/chruby.sh

  local ver=$1
  if [[ -z $ver ]] && [[ -f .ruby-version ]]; then
    ver=$(cat .ruby-version)
  fi
  if [[ -z $ver ]]; then
    echo Unknown ruby version
    exit 1
  fi

  # switch to the desired ruby
  chruby $ver

  # Sets the GEM_HOME environment variable to `$PWD/.direnv/ruby/RUBY_VERSION`.
  # This forces the installation of any gems into the project’s sub-folder. If
  # you’re using bundler it will create wrapper programs that can be invoked
  # directly instead of using the `bundle exec` prefix.
  layout_ruby
```

The gems are not being installed locally to the project still.  I think that the `layout_ruby` function is not available so the GEM_HOME environment var is not being set.  Where is this function declared?

**Comment by russellseymour** [comment]
I think I am trying to do too many things here and getting confused. :(

**Comment by zimbatm** [comment]
No worries, try keeping the `use_ruby` definition in the `~/.direnvrc` file and adjust your Jenkins scrip to:
```bash
#!/bin/bash -ex
echo "2.3.1" > .ruby-version # maybe check that into the repo?
echo "use_ruby" > .envrc
direnv allow .
eval "$(direnv export bash)"

# Here $GEM_HOME should be set to $PWD/.direnv/ruby
echo "debug: $GEM_HOME"
ruby --version

# Do whatever you want
gem install bundler -N
bundle
```

**Comment by russellseymour** [comment]
It is using the `chruby` version of ruby but it is not setting the GEM_HOME properly.  This is the output of the script (I have not run the gem install or bundle):

```
+ echo 2.3.1
+ echo use_ruby
+ direnv allow .
++ direnv hook bash
+ eval '
_direnv_hook() {
  local previous_exit_status=$?;
  eval "$(direnv export bash)";
  return $previous_exit_status;
};
if ! [[ "$PROMPT_COMMAND" =~ _direnv_hook ]]; then
  PROMPT_COMMAND="_direnv_hook;$PROMPT_COMMAND";
fi'
++ [[ '' =~ _direnv_hook ]]
++ PROMPT_COMMAND='_direnv_hook;'
+ echo 'debug: /var/lib/jenkins/.gem/ruby/2.3.1'
debug: /var/lib/jenkins/.gem/ruby/2.3.1
+ ruby --version
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
```

As you can see the GEM_HOME is still in the HOMEDIR of the Jenkins user.

It looks like the `use_ruby` function is not being called because if I change the ruby-version to `2.2.2` I get the same output as above stating that 2.3.1 is in use.

If I SSH into the server and `cd` into the workspace directory then I get the expected output of `chruby: unknown Ruby: 2.2.2`.

Any ideas please?

**Comment by zimbatm** [comment]
Okay, this is wasting my time. Please re-read what I said and adjust your script accordingly. `direnv hook` is not going to work, you need to use `direnv export`.

**Comment by russellseymour** [comment]
I have got a little bit further with it.  If I explicitly source the `~/.direnvrc` file then I can manually call `user_ruby`, however it does not know where to find `layout_ruby`.

This is my updated script:

```bash
#!/bin/bash -ex
echo "2.3.1" > .ruby-version
echo "use_ruby" > .envrc
. ~/.direnvrc
use_ruby
direnv allow .
eval "$(direnv hook bash)"

echo "debug: $GEM_HOME"
ruby --version
```

I am assuming that by calling it like this I do not need the `direnv allow .` or the `eval "$(direnv hook bash)"` lines unless they should help with finding the `layout_ruby` function.  I feel this is moving away from how `direnv` was designed to work.

**Comment by russellseymour** [comment]
I am sorry - I did not see the `export`.

Apologies.

**Comment by russellseymour** [comment]
Perfect that works. Thanks.
