### ISSUE TITLE
`not a valid identifier` error when PATH contains spaces

### ISSUE THREAD

**Issue by nexbit** [direnv/direnv#229]
I work on macOS, and my PATH variable contains paths with spaces inside, like `/Applications/Araxis\ Merge.app/Contents/Utilities`.
This works perfectly fine, but when I enter in a direnv controlled dir, the following error occurs:

```
/opt/local/bin/bash: line 263: export: `Merge.app/Contents/Utilities:/Users/paolof/Library/Application': not a valid identifier
```

From now on my PATH is broken, and this prevents me from using `direnv` on my system..

Is it a known issue, or is there an alternative way to handle exports with spaces inside?

Thanks

**Comment by zeorin** [comment]
So what does your `.envrc` look like in this situation? My guess is, you're trying to prepend some directory to your path, and that you haven't quoted that directory. If it's not quoted, bash will treat your variable as a list of space-separated arguments: [Always use double quotes around variable substitutions and command substitutions: "$foo", "$(foo)"](http://unix.stackexchange.com/a/131767).

**Comment by nexbit** [comment]
Hi
my .envrc does not contain any variables.. It's as simple as

```
set -e
use node 4.4
layout node
```

The problem resides in my original PATH variable, that I set in my bash startup files. It contains some paths (like the one I mentioned in my original post) that have embedded spaces, and it works perfectly fine outside `direnv` (though it's not common in *nix world to have spaces in paths, it's more common in macOS and it's perfectly legal).

It seems that `direnv` is not able to correctly parse and tokenize the variable if it contains spaces.

P.

**Comment by zimbatm** [comment]
@nexbit can you try the master version? I just escaped a bit more things in the stdlib which should help.

**Comment by nexbit** [comment]
Just cloned and compiled it, I can confirm that works correctly when PATH initially contains spaces.

Thank you very much for your prompt response!

**Comment by zimbatm** [comment]
Alright. You might find more of there if you use more of the stdlib. Just let me know if it happens.
