### ISSUE TITLE
Fedora package building

### ISSUE THREAD

**Issue by hexgnu** [direnv/direnv#230]
I see there's no fedora package for direnv.

I could tackle this since I have a fedora project account and use fedora for my development machine. Would that be reasonable? 

Thanks!

**Comment by zimbatm** [comment]
Yes!

I've been wanting a Fedora package for a long time but didn't have the expertise or help needed.

Let me know if I can help you with anything.

**Comment by hexgnu** [comment]
Perfect I'll work on that this week hopefully have something soon.

**Comment by hexgnu** [comment]
Any way you could assign this issue to me? It helps me know what github issues I have yet to work on.

**Comment by zimbatm** [comment]
Sure thing. I created a new packaging team in the org that you need to join. Let me know if you need a repo for the fedora package descriptions as well.

**Comment by hexgnu** [comment]
thank you joined!

**Comment by dustymabe** [comment]
Looks the package is already up for review: https://bugzilla.redhat.com/show_bug.cgi?id=1358215

**Comment by zimbatm** [comment]
That's wonderful!

How do you generally keep track of releases for a project? I want to put something in place so you don't have to think about visiting direnv.net to check for new releases.

**Comment by hexgnu** [comment]
Cool beans looks like I don't have to make one after all :smile:

I think that when direnv is approved you can subscribe to an rss feed of the package updates @zimbatm 

Something like https://bodhi.fedoraproject.org/rss/updates/?packages=gcc

**Comment by zimbatm** [comment]
Thanks, I meant the reverse actually. If I make a new direnv release, how would the Fedora package maintainer be notified?

**Comment by hexgnu** [comment]
good question probably have to send an e-mail to dominic@cleal.org

**Comment by hexgnu** [comment]
That's the person who submitted the package

**Comment by dustymabe** [comment]
hey @zimbatm @hexgnu - in fedora we use https://release-monitoring.org/ and an application called "the new hotness" to monitor upstream and alert us when a new version is out. As long as dominic set up the notifications he will get an alert anytime a new release is put out. 

here is a link to the page that talks about all of this: https://fedoraproject.org/wiki/Upstream_release_monitoring

**Comment by zimbatm** [comment]
Hi @domcleal, are you behind direnv's packaging on Fedora? Just wanted to point you to this discussion in case you are (and thank you for doing the work!)

**Comment by dustymabe** [comment]
@hexgnu - once the package is through review it would be cool if you volunteered to be a co-maintainer of the package with @domcleal

**Comment by hexgnu** [comment]
Yea would love to @dustymabe

**Comment by dustymabe** [comment]
@hexgnu if you sign up for a bugzilla account then I can add you to cc for the bug and we can have a discussion there. bugzilla.redhat.com

**Comment by hexgnu** [comment]
@dustymabe I added myself thanks!

**Comment by zimbatm** [comment]
Regarding release tracking, I tag all the versions so you can consume the release atom feed: https://github.com/direnv/direnv/releases.atom

**Comment by domcleal** [comment]
Hey, thanks for the interest and package review comments. I'll update that today and hopefully we can get it in shortly.

I'd be very happy to have co-maintainers, please let me know your Fedora (FAS) usernames so I can add you when requesting the new package.

Regarding the releases, as @dustymabe noted above, we can easily enable upstream monitoring of the package once imported which will scan for tags in this repository, raises a Fedora bug against the package and tries a test build automatically.

**Comment by hexgnu** [comment]
@domcleal my FAS username is 'hexgnu' thanks!

**Comment by domcleal** [comment]
The [package](https://apps.fedoraproject.org/packages/direnv) is now built for Fedora Rawhide, and updates are being processed for F24 and F25 - please test and provide karma if they work so they're pushed to stable.

* Fedora 25: https://bodhi.fedoraproject.org/updates/FEDORA-2016-6d6d427d8a
* Fedora 24: https://bodhi.fedoraproject.org/updates/FEDORA-2016-6fca1153d8

@hexgnu I see you're not a member of the [packagers group](https://fedoraproject.org/wiki/Join_the_package_collection_maintainers#Import.2C_commit.2C_and_build_your_package), so I filed [a ticket](https://fedorahosted.org/packager-sponsors/ticket/289) to request [sponsorship](https://fedoraproject.org/wiki/How_to_get_sponsored_into_the_packager_group) for you.

**Comment by zimbatm** [comment]
Awesome, thanks a lot!

**Comment by jrobeson** [comment]
this package definitely exists now.  thanks @domcleal

**Comment by zimbatm** [comment]
Cheers!
