### ISSUE TITLE
VScode integration

### ISSUE THREAD

**Issue by rubymaniac** [direnv/direnv#231]
I am trying to create an extension for the [VSCode](https://github.com/Microsoft/vscode) editor in order to support automatic detection / loading of the *.envrc* file when one opens a project that has a *.envrc* with VSCode.

VSCode runs NodeJS so what I was trying to do is, from within the running NodeJS process, somehow to run the *.envrc*  file and then load the environment variables again.

I thought by doing something like:

```js
var exec = require('child_process').exec;

exec('direnv allow', function(err, stdout, stderr) {
    // Somehow get the changed environment (diff?) and extend process.env
});
``` 
it would be a success but I have 2 problems: 

1. `direnv allow` runs in a sub-shell so there is no way I can capture it's output, right? If I do `console.log(stdout)` I always get an empty buffer. 
2. Although `direnv allow` outputs some kind of diff it doesn't have a command to get the diff alongside with the new values of the changed environment variables.

So I would like some feedback if this is feasible (or makes sense at all) somehow.

**Comment by zimbatm** [comment]
Hi @rubymaniac, cool idea!

do you know if VSCode start one process per opened project?

I think what you want is to run `direnv export json`, capture the output, parse it with JSON, and finally replace the `process.env` with that data. But if two projects are loaded in the same process it might cause conflict. Alternatively you would have to store the wanted environment associated to each project and make sure every sub-shell for that project is running in the right environment.

`direnv export json` might fail for multiple reasons: either the script is not allowed to load in the direnv security framework, or the script itself is breaking in some ways. If the script is not allowed to load you might want to display a view that shows the content of the `.envrc` and run `direnv allow` if the user agreed with it's content. Unfortunately right now it's not possible to differentiate the failure by the `direnv export json` exit status so you will have to parse the stderr output (or submit a PR to direnv to change that).

Does it make sense?

**Comment by rubymaniac** [comment]
I am new to this VSCode thing (btw VSCode is an electron application) so I inspected what is going on. 

1. `process.pid` returned different numbers on the different windows on VSCode.
2. [Here](https://github.com/Microsoft/vscode/blob/46d90b43f17c92bd7df0d960321ddb905d1aa72b/src/vs/code/electron-main/main.ts#L404) I can see that it reads the global environment variables and assign them to the current process. Moreover it [calls](https://github.com/Microsoft/vscode/blob/a48045e050d0075ef5325ed05a3b1e0882d2e9b4/src/vs/code/electron-main/sharedProcess.ts#L32) `child_process.fork` which, according to the [Node documentation](https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options) it is independent from the parent process and has its own resources.

From the above I guess that every window has it's own `process` therefore changing `process.env` on one window doesn't change the others'. 

I tried to run `direnv export json` on a directory that has an allowed *.envrc* but it outputs nothing simply because in order to run it I first `direnv allow` so it is already loaded and no diff is produced. Know anyway I can test this command?

PS: No worries for the exit status I will figure it out by parsing the stdout for now (in the future I might make a PR on direnv to differentiate those errors).

Thanks for the help!

**Comment by zimbatm** [comment]
Perfect, sounds like it will be relatively easy to integrate direnv then.

Regarding testing you have two options:
* either remove the hook from your shell or start a different kind of shell (like zsh if you're using bash as your main shell). Before you enter the target directory.
* or run `pushd path/to/folder; direnv export json; popd` on a single line from outside of the folder so the hook doesn't trigger (the hook is executed on every prompt).

Let me know how it goes!

**Comment by rubymaniac** [comment]
Ok now we have something that works! I have some more questions though:

If I run 
```js
child_process.exec('pwd', (err, stdout, stderr) => {
    console.log(stdout);
});
``` 
in VSCode it returns `/` even though I have loaded a project with a root path `/path/to/project` (which is in my opinion weird). 

1. If I exec `cd /path/to/project` direnv's hook doesn't run (expected?). 
2. If I exec `cd /path/to/project; direnv *whatever*` works fine
3. If I exec `pushd /path/to/project; direnv *whatever*; popd;` everything works but it is annoying the output from `pushd` that is printed together with the JSON and I also think that it is not necessary to use `pushd` because of 1. i.e. because the hook never triggers when I exec `cd /path/to/project`.

Thoughts?

**Comment by zimbatm** [comment]
Nice work!

Do you have access to a variable that contains the path to the project root?
Since the process seems to be running under `/` it might be best to pass the `cwd` as a startup option:

```
project_root = "/path/to/project";
child_process.exec('pwd', {cwd: project_root}, (err, stdout, stderr) => {
    console.log(stdout);
});
```

Note that the hook only executes before a shell prompt is displayed so typically in a script you have to invoke `eval "$(direnv export bash)"` yourself. (see `direnv hook bash` to see how the hook looks like for bash).

**Comment by rubymaniac** [comment]
Yes exactly how I currently running `child_process.exec` I pass the `cwd` option with the `vscode.workspace.rootPath` which is the variable that holds the project root path.

Oh ok I guess my mind was stuck to how RVM (one of the ruby version managers) is implemented which as long as I remember overrides `cd`. Now I see that `direnv hook bash` actually calls `direnv export bash` which makes sense.

Thanks for the guidelines, I will have something pretty soon and will update this issue :)

**Comment by rubymaniac** [comment]
Hi there,

I just published the VS Code extension [here](https://marketplace.visualstudio.com/items?itemName=Rubymaniac.vscode-direnv). I welcome any feedback!

Thanks for all the help!

**Comment by zimbatm** [comment]
Nice!

I added a wiki page for it: https://github.com/direnv/direnv/wiki/VSCode which is linked from the main wiki page. It's not super discoverable right now, if you have an idea on how to do this better please let me know.

Small nitpick: I'm using `direnv` all lower-cased, not sure if you can adopt that writing in the project's page. If not it's no biggie.

Last thing, I wanted to review your code but couldn't find a link back to the project from the installation page.

**Comment by rubymaniac** [comment]
I see that you found the link to the [repo](https://github.com/rubymaniac/vscode-direnv) right?

Yes, ofc it is possible to make `direnv` all lowercase (sorry hadn't notice that :P) I will re publish. It is not super discoverable at the Wiki page but that is fine. Most VS Code users are searching the Marketplace for extensions. If you want to make all the info at the wiki more discoverable I am thinking of a section in README with links to the wiki pages (or smth like that). I'll think about it.

**Comment by zimbatm** [comment]
Ok great.

Yeah I think the README is already a bit too crowded but it would be possible to move some of the other stuff into the doc/ folder. Feel free to close this issue if you feel like you're done with this, it's always possible to open more issues later on.

**Comment by rubymaniac** [comment]
Ok perfect. I thought of that because you can include something like "Editor extensions" because I see that you have done some work for Vim and we could do some similar work for the Atom editor. 

Cheers

**Comment by zimbatm** [comment]
Thanks for reminding me, atom already has a plugin: https://atom.io/packages/000-project-shell-env

**Comment by rubymaniac** [comment]
Yeah it is not actually a direnv plugin. As I see, it never uses direnv directly. If I find some extra time I may create an Atom extension, although I never used (or planning to) Atom for development purposes.

**Comment by zimbatm** [comment]
Funny story, I added the `direnv export json` feature for that plugin.

**Comment by rubymaniac** [comment]
Aha I see.. I made the change from Direnv => direnv (all lowercase) and published it again. I would like to include some kind of logo (usually increases installs) but I see that you don't have any for direnv. Have you thought about adding a logo?

**Comment by zimbatm** [comment]
Thanks! For the logo check out this repo: https://github.com/direnv/direnv-logo

**Comment by rubymaniac** [comment]
Oh thanks didn't think that you had a different repo for the logo! I will add it next :)
