### ISSUE TITLE
Introduce configuration file

### ISSUE THREAD

**Issue by zimbatm** [direnv/direnv#233]
direnv can already be configured through environment variables. But each configuration change means reloading the environment which ironically is not that simple. For example on Linux it often means re-starting the X session.

By introducing a configuration file it opens the door to more customization like for example "safe" paths where `.envrc` are automatically allowed to load. Or more flexible logging customization.

In regards to the format I am thinking of using github.com/BurntSushi/toml since it's what's supported by github.com/urfave/cli/altsrc

**Comment by ssbarnea** [comment]
I am really looking forward to see a way to whiletlist an entire path.

**Comment by zimbatm** [comment]
That's been implemented!

See https://direnv.net/#man/direnv.toml.1 for the format

**Comment by zimbatm** [comment]
Agreed, the doc first talks about the format and how it uses sections but those are defined in the top-level.  I should probably push those in a section since it doesn't seem to be possible to close an existing section as well. Here is a quick example in the mean time:

```toml
bash_path = /usr/bin/bash
disable_stdin = true
[whitelist]
prefix = [ "/home/user/code/project-a" ]
```

Let me know if you have a good name for the sections in which bash_path and disalbe_stdin should be put
