### ISSUE TITLE
Control+C doesn't actually stop direnv export bash

### ISSUE THREAD

**Issue by mcandre** [direnv/direnv#236]
The direnv CLI claims that pressing `Control+C` during long exports will quickly interrupt the process, but on my machine, pressing `Control+C` during slow exports doesn't appear to halt anything.

Example configuration:

https://github.com/mcandre/hello-docker/blob/master/.envrc.sample

**Comment by pwaller** [comment]
@mcandre can you share what platform are you running on?

Can you also try `pgrep -INT direnv` and if that doesn't work `pgrep -INT -f direnv` and if that doesn't work substitute `-INT` with `-QUIT` and repeat.

**Comment by pwaller** [comment]
(edited above post: I meant `pkill`, not `pgrep`)

**Comment by zimbatm** [comment]
Hi @mcandre, how do I get access to the `~/.bashrc.d/direnv` files?

My hypothesis is that docker is running in one of those files, which doesn't terminate on SIGINT and blocks the whole chain (direnv waits on the .envrc bash sub-shell which in turn waits on docker to terminate).

**Comment by mcandre** [comment]
Agreed, Docker Machine is probably not responding to SIGINT.

> how do I get access to the ~/.bashrc.d/direnv files?

On my systems, I soft link certain bash configs into a directory, like https://github.com/mcandre/dotfiles/blob/master/.bashrc.d/docker-machine.sh -> `~/.bashrc.d/direnv` , in order to easily enable/disable my bash configs without requiring comments. (I like to version control my bash configs but leave the enabling/disabling of particular snippets to the individual machine in question.)

**Comment by zimbatm** [comment]
Sounds pretty handy. You could even add a shortcut in your ~/.direnvrc so that `bashrc name` load `source ~/.bashrc.d/$name`.

**Comment by zimbatm** [comment]
I've been wondering for a while now how to provide useful extension points to direnv that the community could share.
