### ISSUE TITLE
nix-shell caching

### ISSUE THREAD

**Issue by Mic92** [direnv/direnv#238]
I do not how to generalize this, but I got a great speed up,
when using the following trick to cache the output of nix-shell:

```bash
use_nix() {                                                                                                                                                                                    
  local nixcache=".direnv.$(nixos-version --hash)"                                                                                                                                                   
  if [[ ! -e "$nixcache" ]] || [[ ".envrc" -nt "$nixcache" ]] || [[ "default.nix" -nt "$nixcache" ]] || [[ "shell.nix" -nt "$nixcache" ]]; then                                                                                  
    nix-shell --show-trace "$@" --run 'direnv dump' > "$nixcache"                                                                                                                              
  fi                                                                                                                                                                                           
  direnv_load cat "$nixcache"                                                                                                                                                                  
  if [[ $# = 0 ]]; then                                                                                                                                                                        
    watch_file default.nix                                                                                                                                                                     
    watch_file shell.nix                                                                                                                                                                       
  fi                                                                                                                                                                                           
} 
```

I know, that it does not remove not the old files at the moment.
If you think this trick causes more trouble then gain, feel free to close this issue.

**Comment by zimbatm** [comment]
That's a cool idea, I added it to the wiki: https://github.com/direnv/direnv/wiki/Nix

It's not 100% fool proof because the channel revision might be different than the nixos-version.

**Comment by zimbatm** [comment]
Here is another approach that I think is quite promising: https://github.com/direnv/direnv/wiki/Nix#persistent-shell

**Comment by Mic92** [comment]
Actually a combination of both would be perfect. Be in sync with the channel and not a victim of the garbage collector.

**Comment by zimbatm** [comment]
Maybe it could tell the user when it's out of sync with the channel. It's not super practical to have all projects re-building after updating a channel, it might not be a good time to do it (eg: being offline)

**Comment by Mic92** [comment]
the update of oh-my-zsh has a state file and periodically ask, if the user wish to update.

**Comment by bkchr** [comment]
@Mic92 did you tried to create a combined version of both versions?

**Comment by Mic92** [comment]
@bkchr no, instead after a update I let direnv loop through my important projects. If you use https://github.com/direnv/direnv/wiki/Nix#persistent-shell you could also touch `shell.nix` or `default.nix` after an update.

**Comment by bkchr** [comment]
@Mic92 okay. I already use persistent shell, but it is soo slow :D

**Comment by Mic92** [comment]
@bkchr the nixcache, that I create could be added to the nix store maybe?
And a symlink to the project directory is necessary. Then direnv could load the file locally and skipping the expensive evaluation.

**Comment by rvolosatovs** [comment]
Added a solution, which is somewhat a combination of both: https://github.com/direnv/direnv/wiki/Nix#persistent-cached-shell

**Comment by Mic92** [comment]
I have a new variant that should work with both channels and nixpkgs git repositories. It also uses direnv's new dump feature, which is even faster
and avoid caching environment variables that do not come from nix.

```
# ~/.direnvrc
use_nix() {
  local path="$(nix-instantiate --find-file nixpkgs)"

  if [ -f "${path}/.version-suffix" ]; then
    local version="$(< $path/.version-suffix)"
  else
    local version="$(git -C $path rev-parse HEAD)"
  fi

  local cache=".direnv/cache-${version:-unknown}"

  if [[ ! -e "$cache" ]] || \
    [[ "$HOME/.direnvrc" -nt "$cache" ]] || \
    [[ ".envrc" -nt "$cache" ]] || \
    [[ "default.nix" -nt "$cache" ]] || \
    [[ "shell.nix" -nt "$cache" ]];
  then
    [ -d .direnv ] || mkdir .direnv
    local tmp=$(nix-shell --show-trace --pure "$@" \
      --run "\"$direnv\" dump bash")
    echo "$tmp" > "$cache"
  fi

  local path_backup=$PATH
  eval "$(< $cache)"
  export PATH=$PATH:$path_backup

  if [[ $# = 0 ]]; then
    watch_file default.nix
    watch_file shell.nix
  fi
}
```

**Comment by Mic92** [comment]
Instantiating derivations also seems faster so a different cache strategy could be to use `nix-instantiate` and invalidate the cache when the path changes.

**Comment by bkchr** [comment]
@Mic92 your new solution is really fast :) I added one improvement:
```
  local path="default.nix"

  if [ -f "default.nix" ]; then
    local version="$(stat -c %Y default.nix)"
  elif [ -f "shell.nix" ]; then
    local version="$(stat -c %Y shell.nix)"
  fi
```

This makes the cache more "static". But I think that is based on personal preferences. I for myself don't want to rebuild it when I update my nixpkgs.

**Comment by smaret** [comment]
@Mic92 @zimbatm Wouldn't it make sense to include the `use_nix()` function in `direnv`'s stdlib?

**Comment by zimbatm** [comment]
As you can see in the wiki there are many implementation with various trade-offs. Instead of growing the stdlib I would prefer to have a mechanism to distribute these snippets independently, most of the changes I make between direnv releases are stdlib-only.

**Comment by dagadbm** [comment]
this is probably a stupid question but I am using mac, I have no idea what this nix thing is. Is it possible to addapt this strategy to regular ol zsh in someway?

**Comment by Mic92** [comment]
Not quite sure what your goal is, but there is https://github.com/chisui/zsh-nix-shell

**Comment by dagadbm** [comment]
I just don't want my zsh to take ages when I enter a page with a .direnv. I
am also using asdf-direnv to manage all of that.

**Comment by Mic92** [comment]
I don't think there is a generic solution for that. It depends on what the tool does to figure out when cache invalidation needs to be done.

**Comment by shajra** [comment]
> As you can see in the wiki there are many implementation with various trade-offs. Instead of growing the stdlib I would prefer to have a mechanism to distribute these snippets independently, most of the changes I make between direnv releases are stdlib-only.

I understand that changes can lead to more releases of direnv.  I also see now that the standard library is embedded as a string with the `direnv` executable.  That degree of coupling is kind of strong, and I see how it inconveniences the release of `direnv` with small patches to the standard library.  I'd support a move to decouple that.  I think it would help the Nix situation, not sure about the other functions.

We have a lot of the same ideas in a lot of snippets with people engaged/disengaged to different degrees over time.  I think having something with a little more "standard" feel would be useful.  Like a repository under the "direnv" name.  I think this is more of a social problem than a technical one.

As for competing ideas.  There are some things like `lorri` and `sorri` that I think absolutely should be their own thing.  But there's a class of solutions that I think are largely compatible with switches to turn on/off different ideas:

- *no switch*: you get more or less what `use_nix` is now
- *-w*: you can specify watched files explicitly
- *-c*: derivations are cached and prevented from garbage collection

I think the alternative is me going through what I hand-rolled, what's in `nix-direnv` and what's in `nixify` and figuring out whether there's any real differences worth caring about.  Once I figure that out, it's really tempting to just roll those changes into what I hand-roll.  But if it were more obvious that one solution was more "official" than another, I think I'd feel more of a pull to contribute back.
