### ISSUE TITLE
tcsh - illegal variable name

### ISSUE THREAD

**Issue by danielcavanagh** [direnv/direnv#240]
hi

if you use direnv in tcsh and have a value that ends in `$` then the shell complains of an illegal variable name

this is because a semicolon is always output as the last character, leading to `$;`, which tcsh considers a valid variable and one that of course doesn't exist

eg. `export VAR=value$` to `setenv VAR value$;` to `illegal variable name`

changing line 35 in shell_tcsh.go from `";"` to `" ;"` should do the trick based on my in-shell testing (in fact tcsh automatically alters any setenv command to be exactly that when putting it into history). line 39 should probably also get the same change

**Comment by danielcavanagh** [comment]
oh, looks like it's dead easy to fork, edit and create a pull request, all from my browser. see [issue #241](https://github.com/direnv/direnv/pull/241)

**Comment by zimbatm** [comment]
sweet, thanks! merged the PR
