### ISSUE TITLE
readthedocs is out of date

### ISSUE THREAD

**Issue by xenic** [direnv/direnv#243]
The installation/hook instructions at:
`http://direnv.readthedocs.io/en/latest/install/`
are not in sync with the current (and correct) instructions that are on git.

**Comment by zimbatm** [comment]
Hi @xenic, thanks for letting me know.

How did you find about the readthedocs website? This was just an experiment which I should probably remove. The main website is http://direnv.net/

**Comment by xenic** [comment]
I can't remember the exact search quer(y|ies), but I googled `install direnv` and it shows up near the top.

**Comment by zimbatm** [comment]
Thanks for the report, I deleted the site.
