### ISSUE TITLE
log.go:47: undefined: log.Output

### ISSUE THREAD

**Issue by mc0e** [direnv/direnv#246]
I'm trying to install from the git repo:

    mc0e@mc0e-laptop ~/src/direnv $ make install
    go fmt
    go build  -o direnv
    # _/home/mc0e/src/direnv
    ./log.go:47: undefined: log.Output
    make: *** [direnv] Error 2

This is mentioned at https://digilead.jp/blog/developer/laravel/laravel0002 . I don't read japanese, but based on google translate, it appears this is unresolved by that page, but there's a guess that it might be about the version of go (I have go version go1.2.1 linux/amd64, which is the default on this Ubuntu 14.04 system).

Any suggestions?

**Comment by yermulnik** [comment]
+1

**Comment by zimbatm** [comment]
Hi,

it seems that this global method has been added in version 1.5 of the stdlib. See https://github.com/golang/go/commit/86fdcbedbcb868f7f2e8274d2b50f0ea34043c47
This is only on the default logger, any instances already has the output function so a solution would be to create a new instance and reference that instead. Direnv isn't tested against older version than 1.5 so other issues might be lurking around after that.

I would suggest to either upgrade go to version 1.5 or later or use one of the pre-compiled binaries that are available. See https://dl.equinox.io/zimbatm/direnv/stable

**Comment by mc0e** [comment]
I don't really know go at all, so excuse me if this is stating what might be obvious to someone else.

https://golang.org/pkg/log/#Output confirms that the log package does have an Output method, but I'm not sure where to look for historical documentation. On my system I have a file at `/usr/share/go/src/pkg/log/log.go` which defines the Output` method.

**Comment by zimbatm** [comment]
The issue is that before go 1.5, only instances of a Logger would have the output method. I suspect what you see in your system is the function definition of https://golang.org/pkg/log/#Logger.Output instead.

**Comment by mc0e** [comment]
OK, using go 1.6 for the build seems to work.  Thanks.
