### ISSUE TITLE
Using load_prefix in environment with empty MANPATH breaks man

### ISSUE THREAD

**Issue by mdawaffe** [direnv/direnv#247]
When `$MANPATH` is empty, `man` will use various configurations to construct an equivalent search path hierarchy. I think those configurations are platform dependent, but see, for example, [`man 5 manpath'](http://man7.org/linux/man-pages/man5/manpath.5.html).

That is, if `$MANPATH` is empty, `man` knows where to look for man pages. In contrast, If `$MANPATH` is not empty, `man` will only search in those paths.

If `$MANPATH` is empty, `load_prefix` (which calls `path_add MANPATH`), will set `$MANPATH` to a non-empty value, which will probably break `man`.

For example:
```
$ unset MANPATH
$ man man
# See man's man page
$ echo 'load_prefix foo' > .envrc
direnv: error .envrc is blocked. Run `direnv allow` to approve its content.
$ direnv allow
direnv: loading .envrc
direnv: export +CPATH +LD_LIBRARY_PATH +LIBRARY_PATH +MANPATH +PKG_CONFIG_PATH ~PATH
$ man man
No manual entry for man
```

Instead of looking in the "global" *and* "local" locations, man now only looks in the "local" locations, which is unexpected.

I'm not sure of a cross-platform way of fixing this, though `man -w` looks promising. Perhaps `path_add` could check if `$1` is `MANPATH`. See https://github.com/direnv/direnv/compare/master...mdawaffe:fix/MANPATH-prepending. I didn't make a PR because I was unsure of the approach.

**Comment by zimbatm** [comment]
Thanks for the thorough report @mdawaffe. I think your proposal makes sense, it just needs a bit more comment in the code to explain the branch's existence.

I tested `man -w` on Darwin and Ubuntu 16.04 and it seems to behave similarly. I think it's sufficiently safe to include as a solution and see if anything surfaces on other less common platforms.

**Comment by mdawaffe** [comment]
I expanded on the comment and created #248.

**Comment by zimbatm** [comment]
Ok thanks, I think we can close this issue in the mean time
