### ISSUE TITLE
Partial NodeJS version does not return highest matching version

### ISSUE THREAD

**Issue by ithinkihaveacat** [direnv/direnv#252]
To reproduce:

```
$ cat .envrc
use node 7
$ find $NODE_VERSIONS -maxdepth 1 -mindepth 1
/Users/mjs/.local/share/node/versions/node-v6.9.1
/Users/mjs/.local/share/node/versions/node-v7.1.0
/Users/mjs/.local/share/node/versions/node-v7.2.0
/Users/mjs/.local/share/node/versions/node-v7.4.0
```

Actual:

`node-v7.1.0` is matched and used.

Expected:

`node-v7.4.0` (highest version of the 7 series of releases) is matched and used.

Discussion:

The code to [find the highest matching version](https://github.com/direnv/direnv/blob/master/stdlib.sh#L510) does not work as expected. There's a few problems:

- field separator is `.`, but this appears at points in the string in locations other than the version number.
- The `-r` option of sort appears to do nothing when combined with `-k`.

**Comment by wilmoore** [comment]
Good catch. I think we can correct this with `sort -r` alone. I'll try to get a PR out when I have time to look at this closer.
