### ISSUE TITLE
load_prefix regression after adding MANPATH_add?

### ISSUE THREAD

**Issue by eddies** [direnv/direnv#257]
I use pyenv to manage python versions and direnv to load them, as per the [wiki](https://github.com/direnv/direnv/wiki/Python#-pyenv).

So, in my `~/.config/direnv/direnvrc` I have:
```bash
use_python() {
  local python_root=$HOME/.pyenv/versions/$1
  load_prefix "$python_root"
  layout_python "$python_root/bin/python"
}
```

and in my project `.envrc` I have:
```bash
use python 3.4.5
```

After upgrading direnv to v2.11.1, I now get the following output when direnv loads the above `.envrc`:
```bash
direnv: loading ~/.config/direnv/direnvrc
direnv: loading .envrc
direnv: using python 3.4.5
/Users/alice/.pyenv/versions/3.4.5
environment: line 279: /Users/alice/.pyenv/versions/3.4.5/man: bad substitution
```

As far as I can tell, this is from the new call to [`MANPATH_add "$dir/man"`](https://github.com/direnv/direnv/blob/v2.11.1/stdlib.sh#L312) in `load_prefix` that was part of #248. FWIW, I'm running direnv on OS X.

**Comment by zimbatm** [comment]
hi, sorry for the wait. This should be fixed by #256 and released as v2.11.2
