### ISSUE TITLE
Ability to silence direnv nagging about allowing an envrc 

### ISSUE THREAD

**Issue by unode** [direnv/direnv#259]
In some cases there may be an `.envrc` file that I don't want to allow.
Currently if I use this folder, direnv tells me about allowing .envrc every time I run a command on this project.

Is there any way to silence this message or otherwise reduce the amount of times it is shown?
Something like:

    direnv ignore 1d

would stop nagging for 1 day.

**Comment by zimbatm** [comment]
Hi @Unode,

this is actually a bug. direnv shouldn't try to reload the `.envrc` until the timestamp has changed or the user enters the directory.

This was the original designed but it got lost during a refactor. I will try to get around fixing it ASAP but I'm quite busy.

**Comment by kalbasit** [comment]
has any progress being done on this?

**Comment by zimbatm** [comment]
I wasn't able to fix it yet unfortunately. Anyone else wants to get their hands dirty?

**Comment by murkey** [comment]
+1 for the `ignore` command or something similar. I noticed `deny` requires the file to be `allow`ed, and I'd prefer away to just never allow it and stop nagging. Let me know if you'd prefer splitting this out into a separate feature request. Thanks!

**Comment by jpluscplusm** [comment]
Hey folks! Sorry to jump on an old issue, but is this feature anything that could be merged anytime soon? I've got a situation where a subset of users can't load a specific .envrc, and right now they're either spammed on every shell operation in the directory, or I hardcode some paths where the $PROMPT_COMMAND's `_direnv_hook` is ignored; neither is a great option!

**Comment by zimbatm** [comment]
This has been fixed in direnv 2.21+ actually.

**Comment by jayrod** [comment]
I just installed version 2.23 and this does NOT seem to be fixed. Am I missing something?

**Comment by zimbatm** [comment]
Without more context, it's hard to tell. What is it that you are seeing exactly?

**Comment by jayrod** [comment]
On bash (and xonsh) I am seeing a message "direnv: error SOMEPATH/.envrc is blocked. run direnv allow to approve it's content. 

For this particular .envrc I never want to approve it's content. And I know what you're thinking why would anyone put an .envrc ina  folder they didn't want to use. I am using cookiecutter for python to create projects and the .envrc file is a template.

**Comment by zimbatm** [comment]
Does it show the error on every prompt?

**Comment by jayrod** [comment]
Yup, with each ls command or cd into the directory.

**Comment by zimbatm** [comment]
can you give me the output of `type _direnv_hook` in your bash session? and `direnv version`

**Comment by jayrod** [comment]
# direnv --version
2.23.1
#type _direnv_hook
_direnv_hook is a function
_direnv_hook () 
{ 
    local previous_exit_status=$?;
    trap -- '' SIGINT;
    eval "$("/usr/bin/direnv" export bash)";
    trap - SIGINT;
    return $previous_exit_status
}

**Comment by jpluscplusm** [comment]
A thought occurs: are you definitely using the same binary when you run `direnv version` versus the hard-coded path in the hook?

What does `which direnv` show?

**Comment by jayrod** [comment]
which direnv does indeed point to /usr/bin/direnv
and /usr/bin/direnv --version points to 2.23.1

**Comment by marcospereira** [comment]
I'm also having the same problem, but with version 2.24.0:

```bash
$ which direnv
/usr/local/bin/direnv
$ direnv --version
2.24.0
$ type _direnv_hook
_direnv_hook is a function
_direnv_hook ()
{
    local previous_exit_status=$?;
    trap -- '' SIGINT;
    eval "$("/usr/local/bin/direnv" export bash)";
    trap - SIGINT;
    return $previous_exit_status
}
$ /usr/local/bin/direnv --version
2.24.0
```

But getting in and out of the folder keeps showing the message:

```bash
cd ..
direnv: unloading
$ cd -
/Users/user/project/folder
direnv: error /Users/user/project/folder/.envrc is blocked. Run `direnv allow` to approve its content
$ cd ..
direnv: unloading
$ cd -
/Users/user/project/folder
direnv: error /Users/user/project/folder/.envrc is blocked. Run `direnv allow` to approve its content
```

**Comment by tomdavidson** [comment]
Same here:

```shell
$ which direnv && direnv --version
/usr/bin/direnv
2.25.2

$ type _direnv_hook
_direnv_hook is a function
_direnv_hook () 
{ 
    local previous_exit_status=$?;
    trap -- '' SIGINT;
    eval "$("/usr/bin/direnv" export bash)";
    trap - SIGINT;
    return $previous_exit_status
}
```
