### ISSUE TITLE
Trailing comments in dotenv files parsed incorrectly

### ISSUE THREAD

**Issue by williamsmj** [direnv/direnv#271]
```
$ cat direnvtest/.envrc
dotenv .env
$ cat direnvtest/.env
FOO=baz   # This is a comment
$ cd direnvtest/
$ echo $FOO
baz # This is a comment
```
The `#` indicates that the rest of the line is a comment. You should get the following behaviour.
```
$ source .env
$ echo $FOO
baz
```
See #270, which fixed a related bug.

**Comment by zimbatm** [comment]
Do you mind testing master? fa1fa4fb62507ca7c879bf6fe9615d5bc24268e5 should fix it.

**Comment by williamsmj** [comment]
#fa1fa4f doesn't build for me:
```
go fmt
go build -ldflags ' -linkmode=external' -o direnv
cmd_dotenv.go:7:2: cannot find package "github.com/direnv/direnv/dotenv" in any of:
        /usr/local/Cellar/go/1.8.1/libexec/src/github.com/direnv/direnv/dotenv (from $GOROOT)
        /Users/mike/go/src/github.com/direnv/direnv/dotenv (from $GOPATH)
make: *** [direnv] Error 1
```
The previous revision builds fine.

**Comment by zimbatm** [comment]
Do you have `$GOPATH` set? This is the first time I introduce a package that's not the stdlib so it will cause a bit of issues with how direnv is being built.

Alternatively you can try to `go get github.com/direnv/direnv`

**Comment by williamsmj** [comment]
I have `$GOPATH` set, but no joy.

`go get` worked though, and I can confirm this fixes the test case above. Thanks!
