### ISSUE TITLE
Configurable "taking a while to execute" time

### ISSUE THREAD

**Issue by dharmab** [direnv/direnv#272]
I'm using direnv in conjunction with [pass](https://www.passwordstore.org/) to reference API keys which are shared between directories. For example, one of my projects has an .envrc similar to this:

```sh
#!/bin/sh
layout python3
AZURE_CLIENT_ID=$(pass Azure/ClientId)
AZURE_CLIENT_SECRET=$(pass Azure/SecretKey)
AZURE_TENANT_ID=$(pass Azure/TenantId)
AZURE_SUBSCRIPTION_ID=$(pass Azure/SubscriptionId)
export AZURE_CLIENT_ID AZURE_CLIENT_SECRET AZURE_TENANT_ID AZURE_SUBSCRIPTION_ID
```

Pass uses GPG to encrypt secrets. When the user enters the directory, pass displays the pinentry decryption prompt. If the user is using a strong passphrase, it will take several seconds for them to enter the passphrase, during which time the message `direnv: ([direnv export bash]) is taking a while to execute. Use CTRL-C to give up.` will overwrite the prompt.

If the "taking a while to execute" time was configurable, I could set it to a reasonable password entry time and avoid the overwritten prompt.

**Comment by zimbatm** [comment]
Something like #273 ? Is it ok if it's global? I don't have a clear solution to make it configurable per folder as the .envrc hasn't loaded yet at that point.

**Comment by dharmab** [comment]
Global is perfectly fine, that's actually convenient to set it in one place for many projects. Thanks for the quick response!

**Comment by zimbatm** [comment]
Alright, it's in master now. Let me know if you hit any issues.
