### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by yermulnik** [direnv/direnv#277]
```
18:34:03 [root#local][w:2][j:0][~/.../CODE/direnv]> LANG=C git pull
Already up-to-date.
[direnv/direnv](master)
18:34:17 [root#local][w:2][j:0][~/.../CODE/direnv]> LANG=C git status
On branch master
Your branch is up-to-date with 'origin/master'.

nothing to commit, working directory clean
[direnv/direnv](master)
18:34:19 [root#local][w:2][j:0][~/.../CODE/direnv]> LANG=C make
go fmt
go build  -o direnv
cmd_dotenv.go:7:2: cannot find package "github.com/direnv/direnv/dotenv" in any of:
        /usr/lib/go-1.6/src/github.com/direnv/direnv/dotenv (from $GOROOT)
        ($GOPATH not set)
make: *** [direnv] Error 1
```
Are installation instructions on the main project's page missing something or it's on my side?
How to fix the build?
Thanks.

**Comment by zimbatm** [comment]
Hi, the build instructions have changed slightly in the latest version of direnv.

```sh
export GOPATH=$HOME/go # or whatever you want
mkdir -p $GOPATH/src/github.com/direnv
git clone git@github.com:direnv/direnv.git $GOPATH/src/github.com/direnv/direnv
cd $GOPATH/src/github.com/direnv/direnv
go install
```

**Comment by zimbatm** [comment]
Fixed in 775d98c, thanks for the report!

**Comment by yermulnik** [comment]
Thanks.
And what would be the proper way to *upgrade* later?

**Comment by yermulnik** [comment]
And one would better `git clone` using `https` and **not** `ssh`, I guess...

**Comment by zimbatm** [comment]
Once these changes are in place the upgrade procedure should be as usual, `git pull` from the new location on your drive. And `$GOPATH` can be set using direnv.

Regarding SSH vs HTTPS I think it's a matter of preference. Both are valid and have different trade-offs.

**Comment by yermulnik** [comment]
Yup, `$GOPATH` is set using `direnv` =)

As for `SSH`:
```
19:24:30 [yz@local][w:1][j:0][~/.../src/direnv]> LANG=C git clone git@github.com:direnv/direnv.git $GOPATH/src/github.com/direnv/direnv
Cloning into '/data/yz/Go/src/github.com/direnv/direnv'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by michaelld** [comment]
I forgot to move the build from direnv-devel to direnv; done now in https://github.com/macports/macports-ports/commit/31483ba6ab3c8432c589784d9dfd7978d07e644e .

**Comment by zimbatm** [comment]
Good point, I fixed it in 5a9f8b5

**Comment by zimbatm** [comment]
@michaelld is it possible to checkout or symlink the source under `$GOPATH/src/direnv/direnv`? I'm asking because I'm planning to split direnv into more independent packages in the future.

**Comment by michaelld** [comment]
@zimbatm yes sure that's possible.
