### ISSUE TITLE
provide and document one-line installer

### ISSUE THREAD

**Issue by ssbarnea** [direnv/direnv#282]
Because `direnv` is not (yet) part of all major distributions ([RHEL is missing it too](https://github.com/direnv/direnv/issues/362)), it could be very handy to provide a one liner for installing it via `curl | bash` approach. 

Before someone is raising the security aspect, keep in mind that this one-line installer is only supposed to ease installation, not replace normal packaging installations with a very simple logic:

    if macos then run "brew install direnv"
    elif fedora then run "dng install direnv"
    else: git checkout, make && make install

This would not only simplify the usage, but would also simplify the documentation.

**Comment by zimbatm** [comment]
you can now run `curl https://direnv.net/install.sh | bash` to pull the latest release
