### ISSUE TITLE
more than one dir change causes pushd failures with symlinks

### ISSUE THREAD

**Issue by purpleidea** [direnv/direnv#294]
On latest Fedora 26...

If I jump deep into a directory, I get errors:

```
james@computer:~/code$ cd project/foo/bar/baz/thing/
environment: line 173: pushd: ../../../../.envrc: No such file or directory
direnv: referenced ../../../../.envrc/.envrc does not exist
environment: line 182: popd: directory stack empty
direnv: error exit status 1
```

There's a `.envrc` in `~/code/project/`

if I cd into it one dir at a time it works as expected.
This is also triggered when I do Control-Shift-T to make a new tab in gnome-terminal which opens at the same working directory as the first.

Suggestions?

**Comment by purpleidea** [comment]
Turns out this was probably related to me having a symlink in the path!

(at `~/code/project/foo` which pointed to `/elsewhere/whatever/` )

Not sure what the fix is...

**Comment by purpleidea** [comment]
```
15:36 < zimbatm> actually I suspect that it's caused by the -P argument to `pwd 
                 -P` in the stdlib
15:37 < zimbatm> see https://github.com/direnv/direnv/blob/master/stdlib.sh#L177
15:37 < zimbatm> if you can try removing the argument and let me know on the 
                 issue

```

I can confirm this is most likely the issue.

**Comment by purpleidea** [comment]
Please review: https://github.com/direnv/direnv/pull/295

**Comment by zimbatm** [comment]
thanks, all good!
