### ISSUE TITLE
[question] Can't seem to get node to load properly?

### ISSUE THREAD

**Issue by ahmedelgabri** [direnv/direnv#296]
Not sure what is wrong to be honest, I followed the steps in the [wiki](https://github.com/direnv/direnv/wiki/Node), went through a couple of issues & even tried to check the source code.

Contents of `.envrc` file:

```
set -e
use node
```

<img width="642" alt="screen shot 2017-09-23 at 17 24 49" src="https://user-images.githubusercontent.com/63876/30774707-2b4369ee-a087-11e7-83c0-4b8f2306959a.png">

**Comment by zimbatm** [comment]
Hi @ahmedelgabri,

I think it's due to a small typo (or broken docs?). In `NODE_VERSION_PREFIX` the version is in singular form.

**Comment by ahmedelgabri** [comment]
Thanks @zimbatm, actually it seems that I made this typo myself the wiki is right. Sorry for the false alarm.

**Comment by zimbatm** [comment]
no worries, the prefix should probably be the same to avoid that confusion

**Comment by ahmedelgabri** [comment]
One more thing, `NODE_VERSION_PREFIX` doesn't seem to be working with an empty string. This was fixed here https://github.com/direnv/direnv/pull/220 but then was changed back here https://github.com/direnv/direnv/pull/255 assuming accidentally, otherwise how can I remove the prefix if needed. 

I was trying [`n`](https://github.com/tj/n) instead of `nvm` & they don't have prefixes for versions.

**Comment by zimbatm** [comment]
thanks for the report, I have applied that patch again and it's now in master

**Comment by ahmedelgabri** [comment]
Thank you

**Comment by zimbatm** [comment]
Do you need a release or you're ok with compiling direnv on your own?

**Comment by ahmedelgabri** [comment]
It will be nice to have a release so everyone can benefit from it & it easy to automate. But I’m comfortable with compiling from source too.

**Comment by zimbatm** [comment]
Ok I think it's time for a release anyways
