### ISSUE TITLE
Layout within nested environments broken

### ISSUE THREAD

**Issue by elventear** [direnv/direnv#297]
I just updated to direnv v2.13.0 and I see un expected behavior. I have a tree of directories with nested environments that source the top level using `source_up`. In the highest level I have a custom Python virtualenv defined by using `layout python python2.7`. In the children I would have custom settings but I would not define a new layout for python.

Up to direnv v2.12.2 the way it worked is that if I moved into a child directory a Python virtualenv would be configured by the parent `.envrc` within a `.direnv` directory within the parent. All the children would share the same version of Python. 

When I upgraded to direnv v2.13.0, now every time I move into a child directory, a new version of the virtualenv is created within a `.direnv` directory in the children directories, instead of reusing the parent `.direnv`. 

Is this a bug or a change in behavior?

**Comment by zimbatm** [comment]
I'm trying not to break backward-compatibility so this is a bug. I know what the issue is but need a bit of time to think of a good solution.

In the mean time you work around the issue by setting this additional line at the top of the top-level `.envrc`:
```sh
direnv_layout_dir=$PWD/.direnv
```

**Comment by zimbatm** [comment]
@elventear do you mind trying https://github.com/direnv/direnv/pull/298 out?

**Comment by elventear** [comment]
#298 works for me 👍

**Comment by zimbatm** [comment]
Thanks! cutting a new release
