### ISSUE TITLE
Trouble make installing

### ISSUE THREAD

**Issue by Andreilys** [direnv/direnv#302]
I brew installed golang and make, then ran the following commands:

```
git clone https://github.com/direnv/direnv
cd direnv
make install
```

The output was:

go fmt
go build -ldflags ' -linkmode=external' -o direnv
cmd_dotenv.go:7:2: cannot find package "github.com/direnv/go-dotenv" in any of:
        /usr/local/Cellar/go/1.9.1/libexec/src/github.com/direnv/go-dotenv (from $GOROOT)
        /Users/andreilyskov/go/src/github.com/direnv/go-dotenv (from $GOPATH)
make: *** [direnv] Error 1

Not sure what to make of this, any advice?

**Comment by glasser** [comment]
(Not direnv maintainer, just a fan.)

I'm surprised that the directions tell you to just clone anywhere. If you use `go get github.com/direnv/direnv` it will clone it into your GOPATH including dependencies and build it for you.

**Comment by zimbatm** [comment]
I thought that putting things in `vendor/` would remove that requirement but no :/

@Andreilys:
```sh
export GOPATH=${GOPATH:-HOME/go}
mkdir -p $GOPATH/src/github.com/direnv
git clone https://github.com/direnv/direnv.git $GOPATH/src/github.com/direnv/direnv
cd $GOPATH/src/github.com/direnv/direnv
make install
```

**Comment by tristan957** [comment]
I am also experiencing this issue while attempting to package direnv for Solus. Let me know if I can help solve the issue

**Comment by tristan957** [comment]
Found a solution where the current directory is the tar file:

```
cd ..
mkdir src
mv direnv-$version src/direnv
export GOPATH=`pwd`
cd src/direnv
```

**Comment by kierun** [comment]
Getting the same problem and tried this:

```
; mkdir ~/go                              
; export GOPATH=~/go    
; go get github.com/direnv/direnv
# github.com/direnv/direnv
go/src/github.com/direnv/direnv/cmd_hook.go:27: undefined: os.Executable
go/src/github.com/direnv/direnv/config.go:52: undefined: os.Executable
go/src/github.com/direnv/direnv/log.go:54: undefined: log.Output
```

**Comment by zimbatm** [comment]
@kierun what version or go are you using? os.Executable is only available in go 1.4+ or something like that

**Comment by kierun** [comment]
Of course I have an old version since it is on ubuntu 14.04 LTS…

```
; go version
go version go1.2.1 linux/amd64
```

☹

**Comment by kierun** [comment]
One can update using the commands from the main [Golang repository](https://github.com/golang/go/wiki/Ubuntu) so should be more or less "safe":

```
sudo apt-get purge golang
sudo add-apt-repository ppa:gophers/archive
sudo apt-get update
sudo apt-get install golang-1.10-go
```

Then doing 

```
; mkdir ~/go                              
; export GOPATH=~/go    
; go get github.com/direnv/direnv
; cp go/bin/direnv ~/bin
```

Works just fine.

**Comment by zimbatm** [comment]
Or just download the binary that comes with the release:

```
$ curl -sfL https://github.com/direnv/direnv/releases/download/v2.17.0/direnv.linux-amd64 ~/.bin/direnv && chmod +x ~/.bin/direnv
```

**Comment by zimbatm** [comment]
2251df501ce8fdf62483938748f1685eb07db49d should help with the issue. Ping me if that doesn't work for you.
