### ISSUE TITLE
direnv.net SSL is broken in Chrome (due to HSTS?)

### ISSUE THREAD

**Issue by simonw** [direnv/direnv#305]
I just got this error trying to visit http://direnv.net/ in Google Chrome on OS X:

<img width="899" alt="privacy_error" src="https://user-images.githubusercontent.com/9599/32418442-beca070a-c21e-11e7-9ef1-fb946ae321dd.png">

It looks like there's the combination of a broken or expired TLS certificate plus an aggressive HSTS setting.

**Comment by simonw** [comment]
Interestingly it worked fine for me in OS X Safari.

**Comment by zimbatm** [comment]
I switched the CDN from CloudFlare to Fly.io today so that seems to correlate with the issues that you are seeing.

Do you mind re-trying tomorrow? https://direnv.net has a valid certificate at least on my end.

**Comment by simonw** [comment]
https://direnv.net/ is working fine for me today in Chrome OS X, Firefox OS X and Safari OS X.
