### ISSUE TITLE
"Sticky" allow?

### ISSUE THREAD

**Issue by timuckun** [direnv/direnv#307]
I allow .envrc in /foo/bar/.envrc

when I switch to /foo/bar/baz and then modify the .envrc in the parent directory I get this error

direnv: error ../.envrc is blocked. Run `direnv allow` to approve its content.

It seems like direnv is allowing permissions based on relative and not absolute paths.  If I have allowed a file shouldn't it be allowed no matter where I am?

**Comment by glasser** [comment]
Do you mean that you allowed it before you edited it? You need to rerun allow whenever you edit it.

**Comment by yermulnik** [comment]
> You need to rerun allow whenever you edit it.

Or edit it using `direnv edit` and it will implicitly `allow` it after editing.

**Comment by timuckun** [comment]
Out of curiosity.

Why do I need to allow it after an edit? Once I have allowed it shouldn't it reload automatically?

**Comment by yermulnik** [comment]
What if it gets corrupted or compromised intentionally or by accident? The system catches that file has changed and reports it for you. I'd better know that the file has changed and review it if that wasn't me who did the change.

**Comment by zimbatm** [comment]
Yes that's by design. Imagine that you git cloned a repo that contains an envrc. It looks legit so you allow it. Now upstream could push a nasty change and running `git pull` could then have disastrous effects.

**Comment by zimbatm** [comment]
Is there anything left to do for this issue?
