### ISSUE TITLE
rcPath is not escaped when called in cmd_edit

### ISSUE THREAD

**Issue by JelF** [direnv/direnv#308]
https://github.com/direnv/direnv/blob/a332ad99455f6e91b435b54aaad649db9440e8e0/cmd_edit.go#L60

As a result, when i call `direnv edit` in a folder like `"/home/jelf/My Folder"` (with `.envrc` inside), resulting command becomes `$ /usr/bin/vim /home/jelf/My Folder` instead of `$ /usr/bin/vim /home/jelf/My\ Folder`

I suggest never use printf is such cases. Sure there is a safe way to join shell command arguments in go

**Comment by zimbatm** [comment]
thanks! it's fixed in master now
