### ISSUE TITLE
Error when using dotenv command

### ISSUE THREAD

**Issue by Alex-Mann** [direnv/direnv#309]
I have a `.envrc` file which is in the same directory as my `.env` directory, and my `.envrc` contains just this:
```
dotenv
```
When I try to load my `.env` file I am getting the following error:
```
direnv: loading .envrc
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/direnv/direnv/vendor/github.com/direnv/go-dotenv.parseValue(0x0, 0x0, 0x18, 0xc4200105a0)
	/private/tmp/direnv-20170927-66024-18ms8i/direnv-2.13.1/src/github.com/direnv/direnv/vendor/github.com/direnv/go-dotenv/parse.go:70 +0x15c
github.com/direnv/direnv/vendor/github.com/direnv/go-dotenv.Parse(0xc4200de000, 0x37a, 0x37a, 0x57a, 0xc4200de000)
	/private/tmp/direnv-20170927-66024-18ms8i/direnv-2.13.1/src/github.com/direnv/direnv/vendor/github.com/direnv/go-dotenv/parse.go:52 +0x135
main.glob..func4(0xc4200104b0, 0xc42000c780, 0x2, 0x2, 0xc4200100c0, 0x3)
	/private/tmp/direnv-20170927-66024-18ms8i/direnv-2.13.1/src/github.com/direnv/direnv/cmd_dotenv.go:43 +0x103
main.CommandsDispatch(0xc4200104b0, 0xc4200100c0, 0x3, 0x3, 0xc42005df70, 0x411dc4e)
	/private/tmp/direnv-20170927-66024-18ms8i/direnv-2.13.1/src/github.com/direnv/direnv/commands.go:95 +0x364
main.main()
	/private/tmp/direnv-20170927-66024-18ms8i/direnv-2.13.1/src/github.com/direnv/direnv/main.go:16 +0x84
```
Any ideas?

**Comment by Alex-Mann** [comment]
As a temporary fix, I've done this in my `.envrc` file:
```
export $(cat .env | xargs)
```

**Comment by zimbatm** [comment]
@Alex-Mann can you share the content of the `.env` file? It looks like a parsing error.

**Comment by Alex-Mann** [comment]
@zimbatm I see, ok well I figured out the problem. I had a variable declared like so:
```
SOME_VAR=
```
Essentially as a placeholder. I figured it would either not parse this or would just result in an empty string. This is good to know though.

**Comment by zimbatm** [comment]
well it's not supposed to be something you have to know :) I have just published release v2.13.2 which should contain a fix for this

**Comment by Alex-Mann** [comment]
Awesome! Thanks for the quick update. Do you handle comments (ie. `// some comment`) in any way? Perhaps by omitting them or some other means?

**Comment by zimbatm** [comment]
Yes comments start with `# some comment` like in bash
