### ISSUE TITLE
dotenv loading issue

### ISSUE THREAD

**Issue by verginer** [direnv/direnv#313]
Since the last release the `dotenv` command raises the error 
``/bin/bash: line 108: export: `=': not a valid identifier``
on a `.envrc` file which up until now did not raise an issue.

The `.env` file both empty and with assignment for example
```
NEO_HOST="10.189.100.397"
```
raises this issue.

removing `dotenv` from the `.envrc` resolves the issue.

OS: Mac OS X

**Comment by devinus** [comment]
Just started getting this as well.

**Comment by devinus** [comment]
I can confirm this is only an issue on `v2.13.2` and not `v2.13.1`.

**Comment by zimbatm** [comment]
hi, can you give me the output of `direnv version`?

**Comment by zimbatm** [comment]
ok I found the issue: `direnv dotenv bash` also outputs `export ''='';` which is valid but probably not understood by the older version of bash that is shipped on macOS.

**Comment by verginer** [comment]
On Ubuntu `VERSION="16.04.3 LTS (Xenial Xerus)"` the command `export ''='';` raises the same issue ``bash: export: `=': not a valid identifier``.

In which bash version is this a valid command?

**Comment by zimbatm** [comment]
alright, this will be fixed in release v2.13.3 !
