### ISSUE TITLE
"direnv edit" is broken

### ISSUE THREAD

**Issue by yermulnik** [direnv/direnv#315]
Since latest (or at least some recent) release `direnv edit` command is broken:
```
> direnv help | head -1
direnv v2.13.3
> ls -la .envrc
-rw------- 1 yz yz 250 Dec  6 13:44 .envrc
> EDITOR="echo" direnv edit
$/data/epam/hcom/stash.hcom/infra/hcom-terraform-legacy-ccs3-deploy/tf/tech-ops/.envrc
> EDITOR="echo" direnv edit .envrc
$.envrc
```
I presume this `$` in the beginning of paths to `.envrc` file is something redundant and unexpected to be there.

**Comment by zimbatm** [comment]
It must be related to the change I introduced in bdca41da1f9b71bc743662a4e0a828303bf942a

**Comment by zimbatm** [comment]
@yermulnik I bet that your /bin/sh is not bash and thus doesn't support the bash escaping that I added

**Comment by yermulnik** [comment]
Yup, it's `dash` on my Linux Mint. But you *should not* rely on the idea that *all* of nix flavors have `/bin/sh`/ linked to `bash`. E.g. FreeBSD has POSIX shell for `/bin/sh`, Linux Mint has `dash`, and so on. Guess the clue might be using `/usr/bin/env bash` which is cross-distro-compatible for vast majority of nix'es.

**Comment by zimbatm** [comment]
Cutting a new release right now

**Comment by yermulnik** [comment]
> Yup, ad0bceb should fix this

Look like it did. Thanks!
