### ISSUE TITLE
Make a responsive website

### ISSUE THREAD

**Issue by hoxu** [direnv/direnv#316]
Currently the site is unusable on mobile devices.

The issue can be partially reproduced with Firefox's Responsive Design Mode.

**Comment by zimbatm** [comment]
This is too much work for me as I am not a frontend developer. Is this something that you would be open to tackle?

direnv is using https://github.com/chutsu/ditto/ for the website. If you contribute there it will also benefit others.

**Comment by zimbatm** [comment]
I just updated ditto to v0.15 which fixes the layout a bit. It's still not responsive.

**Comment by zimbatm** [comment]
Alright I think that it's good enough
