### ISSUE TITLE
encrypted variables with ssh-vault

### ISSUE THREAD

**Issue by nbari** [direnv/direnv#320]
Hi, I have the need to export variables that are stored in an encrypted vault with [ssh-vault](https://ssh-vault.com), what I am doing now is to create a file with the variables something like:

    AWS_ACCESS_KEY_ID=foo
    AWS_SECRET_ACCESS_KEY=bar

Later I create the vault 

    cat my-vars | ssh-vault create > my-encypted-vars.ssh

That allows me to add to the repository `my-encrypted-vars.ssh`  in a safer way, later when I want to use them,  to automate the load of the variables, I have this in `.envrc`

    export $(ssh-vault view $HOME/path/to/my-encrpted-vars.ssh)

That works pretty well, but when dealing with multiple stacks/environments forces me to have different files, for example:

     export $(ssh-vault view $HOME/path/to/my-encrpted-vars-PRO.ssh)
  
or for development:

      export $(ssh-vault view $HOME/path/to/my-encrpted-vars-DEV.ssh)

the pattern could be by git branch:

      export $(ssh-vault view $HOME/path/to/my-encrpted-vars-BRANCH.ssh)

Therefore wondering if probably a `layout` on the side of **dirven** could be used to read the input on `yaml` format and based on the branch load the variables.

For example, instead of having to create multiple files with something like:

     AWS_ACCESS_KEY_ID=foo
     AWS_SECRET_ACCESS_KEY=bar

Could be nice to have a single file per project with the following structture:

    master:
       AWS_ACCESS_KEY_ID=foo
       AWS_SECRET_ACCESS_KEY=bar
    develop:
       AWS_ACCESS_KEY_ID=foo
       AWS_SECRET_ACCESS_KEY=bar
    default:
       AWS_ACCESS_KEY_ID=foo
       AWS_SECRET_ACCESS_KEY=bar

This simplifies and makes cleaner the repo since I could have only one single vault and to get all the vars, I could just do:

    $ ssh-vault view $HOME/path/to/my-encrpted-vars.ssh

But the missing part is the integration with **direnv**.  Probably the `yaml` could be parsed and always use the `default` vars but when doing something like:

    $ direnv allow -env "develop"

 reload vars in `.envrc` but only the ones for the `development` environment.

Better would get from the shell (zsh) the name of the existing branch by using the content of the variable `$vcs_info_msg_0_` and based on that load the variables if any, otherwise fallback to default.
 
This is only an idea but probably are betters way to enhance this.

**Comment by zimbatm** [comment]
Hi,

this feature request resembles a lot one feature that I am planning to implement in direnv 3.0. Note that development on direnv 3.0 has barely started so this is not something that will happen tomorrow.

Essentially what you want is a way to specify multiple contexts in the same folder. This is useful when one wants to load different environment variables for different targets like staging / test / production.

In terms of UX I am thinking of something like `direnv switch <context-name>`. When entering the folder, the default context would be loaded and then after that it's possible to use `direnv switch staging` for example to load the `.envrc.staging` file instead. Commands like `direnv edit` would have to be augmented to support the contextes. direnv would also export DIRENV_CONTEXT, so that PS1 can be extended to display which context is currently loaded.

For this work to be done I need to rework some of the internals to make them more flexible, which leads to the rewrite I was talking about.

**Comment by nbari** [comment]
Hi @zimbatm looks good.  Consider  `$vcs_info_msg_0_`   it may help to automate things based on the existing branch without the need to remember to call every time `direnv switch <context-name>`

**Comment by zimbatm** [comment]
I don't know if the context should be tied to the git branch name. In that case you can also commit different `.envrc` between each branches and direnv will automatically reload when that file changes. In fact you could already do something like this today:

```sh
# reload on branch changes
watch_file .git/HEAD

branch=$(git rev-parse --abbrev-ref HEAD)
if [[ $branch != HEAD ]]; then
    export $(ssh-vault view $HOME/path/to/my-encrpted-vars-$branch.ssh)
fi
```

**Comment by nbari** [comment]
Hi @zimbatm many thanks for the example will give a try.

Just one question, the script code within `.envrc` if not using `watch_file` only is executed once or in each `direnv allow` call right?  So basically I could add any complex code/logic and not have to worry that every time is going to be executed and add extra load to the system, is this correct?

**Comment by zimbatm** [comment]
watch_file adds the files mtimes to the context which is evaluated before each prompt. If any of those files mtime changes (the .envrc and allow file are in this list by default) then direnv reloads the environment. stat()-ing a few files is not a big deal. I expect to see a slow-down after a few hundreds of files.

**Comment by nbari** [comment]
Hi @Globegitter from the `ssh-vault` side in the latest macOS there is this issue https://github.com/ssh-vault/ssh-vault/issues/31 the one is not allowing to decrypt without typing the password, don't know how from the `direnv` side this could be managed in order to enter the password requests so that once the "vault" is decrypted it could load the variables.

**Comment by zimbatm** [comment]
I just had an idea on how to implement this without extending direnv.

.envrc
```sh
context=
[[ -f .envrc.context ]] && context=$(< .envrc.context)
watch_file ".envrc.context"

if [[ -n "$context" ]]; then
  context_file=".envrc.$context"
  if [[ -f "$context_file" ]]; then
   echo "Loading context $context"
   source_env "$context_file"
  else
    echo "$context_file missing"
  fi
fi
```

Then create `.envrc.staging`, `.envrc.prod`, ... files and use for example `echo staging > .envrc.context` to switch to the staging context. Direnv will see that the file has changed and automatically reload the environment for you.

This could be further improved by creating bash aliases to switch context and move the logic into the `~/.direnvrc` file.

**Comment by sardaukar** [comment]
@zimbatm thanks, this is great. not sure how moving into `~/.direnvrc` would look like, but this is already a huge boon

**Comment by nbari** [comment]
Hi @zimbatm,  good approach 👍 , also like the idea that `direnv` still light so no need to expand it
