### ISSUE TITLE
dotenv command does not respect comments

### ISSUE THREAD

**Issue by r-bar** [direnv/direnv#321]
Ran into an issue where I had my `.envrc` sourcing `.env` and exporting an undesired value.

In `.envrc`:
```shell
dotenv .env
```

In `.env`:
```shell
VARIABLE=value
#VARIABLE=disabled_value
```

The result will be `$VARIABLE = disabled_value`.

__WORKAROUND:__ Inverting the order the variables are declared and putting the desired value last results in the desired value being populated. There is no fix if you are trying to not set a commented variable.

**Comment by zimbatm** [comment]
Hi, can you give me the output of `direnv version`?

**Comment by zimbatm** [comment]
the go-dotenv package has been rewritten recently and should support that case properly.

I have added a test in https://github.com/direnv/go-dotenv/commit/41490d485b3af2c705451d048142b0b750220691 for this and couldn't reproduce the error.

Probably upgrading direnv will fix the issue for you.

**Comment by r-bar** [comment]
@zimbatm Looks like the machine i discovered the issue on was using direnv from the Ubuntu artful apt repository. The version reported by direnv is 2.11.3. I just downloaded and compiled the latest master (with version 2.14.0) and can confirm this behavior no longer exists. Thanks for your help!

**Comment by zimbatm** [comment]
@r-bar do you know if there is a way to report the outdated version?

**Comment by r-bar** [comment]
@zimbatm I have not participated in the ubuntu packaging process. From the [package's page](https://packages.ubuntu.com/artful/direnv) it looks like it is maintained by the team that forks off the [debian testing repo package](https://packages.debian.org/buster/direnv). By updating debian testing it would filter into the next ubuntu release. From what I understand debian testing would be much easier to update. Ubuntu artful version will be frozen unless you make a backport. Sorry If I repeated what you already know. Both those links have mailing lists for their respective maintainers. Depending what you try to update I would start there.

**Comment by zimbatm** [comment]
thanks, I didn't follow that the newest Ubuntu release was starting back at A in the alphabet and assumed it was a special package set.
