### ISSUE TITLE
There is something wrong with the Wiki about +pyenv portion 

### ISSUE THREAD

**Issue by MemoryReload** [direnv/direnv#325]
## Issue description
There is something wrong with the Wiki at the "+pyenv" portion https://github.com/direnv/direnv/wiki/Python#-pyenv
### Steps to reproduce
Setting project's `.envrc`: `use python 3.6.4` results an error like this:

```
[heping@Laputa:~/Desktop/jump_automation_proj]$direnv allow
direnv: loading .envrc
direnv: using python 3.6.4
Running virtualenv with interpreter /Users/heping/.pyenv/versions/3.6.4/bin/python3
There must be only one argument: DEST_DIR (you gave /Users/heping/.pyenv/versions/3.6.4/bin/python3 /Users/heping/Desktop/jump_automation_proj/.direnv/python-3.6.4)
```

## Technical details

since the `layout python3` command is short cut, and get its default python executable path, the path parameter will raise an error.

I try to correct it like this:

```
use_python() {
  local python_root=$(pyenv root)/versions/$1
  load_prefix "$python_root"
  if [[ -x "$python_root/bin/python" ]]; then
    layout python "$python_root/bin/python"
  else
    echo "$python_root not installed."
    exit
  fi
}
```

**Comment by zimbatm** [comment]
sounds good, feel free to change the wiki!

**Comment by MemoryReload** [comment]
@zimbatm  OK, I'll give a try. :)
