### ISSUE TITLE
website should mention emacs-direnv

### ISSUE THREAD

**Issue by wbolster** [direnv/direnv#329]
the website https://direnv.net/ shows a link to a vim integration plugin.

it would be helpful if it could also link to `emacs-direnv`:

https://github.com/wbolster/emacs-direnv

thanks!

(the website is not in git it seems? otherwise i would've submitted a pr.)

**Comment by zimbatm** [comment]
@wbolster happy to accept a PR. The vim link is in docs/sidebar.md

**Comment by wbolster** [comment]
@zimbatm sorry, i didn't realise that it actually was in the same repo. i opened #330, as you suggested.

**Comment by zimbatm** [comment]
no worries, thanks!
