### ISSUE TITLE
Support for nvm, nodenv, etc.

### ISSUE THREAD

**Issue by mcandre** [direnv/direnv#335]
Would be great if direnv included built-in functions for loading the different Node.js version managers:

https://github.com/nodenv/nodenv/wiki/Alternatives

Examples:

* https://github.com/mcandre/dotfiles/blob/master/.bashrc.d/nodenv.sh
* https://github.com/mcandre/dotfiles/blob/master/.bashrc.d/nvm.sh
* https://github.com/mcandre/dotfiles/blob/master/.bashrc.d/ndenv.sh

**Comment by zimbatm** [comment]
direnv would have to do too many releases to keep up with all the other project changes. The current approach is to implement the most commonly version switcher and then let users override it with the direnvrc file. See https://github.com/direnv/direnv/wiki/Node

**Comment by thernstig** [comment]
It is possible this can be closed, unless direnv wants to maintain a use_nvm() functionality that works with many version switchers. As I explained when closing my issue https://github.com/direnv/direnv/issues/531, there are alternatives explained for adding your own functions e.g. `nvm_use`, see https://github.com/direnv/direnv/wiki/Node.

**Comment by zimbatm** [comment]
yep, thanks!

**Comment by ryenus** [comment]
For someone looking for using node installed via nvm, 
just setup `NODE_VERSION_PREFIX` as below in **~/.config/direnv/direnvrc**.

```sh
# for node installed via nvm
NODE_VERSIONS="$HOME/.nvm/versions/node"
NODE_VERSION_PREFIX=v
```

Then in **.envrc**, you can have `use node 14`.
Performance wise this feels better than [`use_nvm`][1].

[1]: https://github.com/direnv/direnv/wiki/Node#using-nvm

**Comment by EmilPi** [comment]
I've tried to put variables into `~/.config/direnv/direnvc`
<pre>
~$ cat ~/.config/direnv/direnvc 
export NODE_VERSION_PREFIX=v
export NODE_VERSIONS=/home/emil/.nvm/versions/node
</pre>
hoping .envrc in any directory will have this variables exported, but this was not the case...

**Comment by samhinshaw** [comment]
I wanted to use `nvm` with an `.nvmrc` file. This worked for me:

```sh
if [ -f $HOME/.nvm/nvm.sh ]; then
  type nvm >/dev/null 2>&1 || . $HOME/.nvm/nvm.sh
  nvm use $(< .nvmrc)
fi
```

**Comment by ngood97** [comment]
fwiw I just copied the nvm setup from my ~/.zshrc, then ran `nvm use`, which picks up the contents of the .nvmrc

```bash
export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
 nvm use
```
