### ISSUE TITLE
latest stable 2.15.0 or  2.15.1?

### ISSUE THREAD

**Issue by ilovezfs** [direnv/direnv#341]
https://github.com/direnv/direnv/releases shows 2.15.1
https://github.com/direnv/direnv/releases/latest shows 2.15.0

what is latest stable?

**Comment by zimbatm** [comment]
the release process has been broken with the go 1.10 upgrade. 2.15.1 is the latest release but doesn't have binaries attached to it. Working on a fix in #342

**Comment by zimbatm** [comment]
v2.15.2 is now the latest release!
