### ISSUE TITLE
Running direnv reload inside a shellscript

### ISSUE THREAD

**Issue by ahmedelgabri** [direnv/direnv#345]
## Issue description
Currently I have bin function that launches tmux with some specific setup & looks for a file `.mx-start` which is a shellscript & call that script if available 

```sh
#!/usr/bin/env sh

tmux send-keys "./.mx-start" C-m
```
That file will include some other `tmux` calls to create splits & stuff, in these calls I'm making sure I reload `direnv` & do some actions after.

```sh
#!/usr/bin/env sh

tmux send-keys -t"SESSION_NAME":2.1 "cd ./some/directory && direnv reload; $EDITOR" C-m
```

The problem here that `direnv reload; $EDITOR` doesn't work as expected, neither do `direnv reload && $EDITOR` both will open the `$EDITOR` before `direnv` finishes reloading.

Any clues what is the best way to deal with this?

## Technical details

* `direnv version`: 2.15.2
* OS release: macOS 10.3.3

Here is how to reproduce 

Some setup
```sh
mkdir /tmp/test-direnv && cd /tmp/test-direnv && echo "export FOO=foo" > .envrc && direnv allow && cd ~
```

Now run the following

```sh 
cd /tmp/test-direnv && eval "$(direnv export bash)"; $EDITOR
```

**Comment by zimbatm** [comment]
did you have a look at the wiki yet? https://github.com/direnv/direnv/wiki/Tmux

**Comment by ahmedelgabri** [comment]
Yes & I do have this already in `.tmux.conf` https://github.com/direnv/direnv/wiki/Tmux#alternatively but the last time I checked it didn't help when I dynamically creating splits from a shellscript

**Comment by zimbatm** [comment]
okay I didn't read your report well enough. I think that what you want is to replace the `direnv reload` bit with `eval "$(direnv export bash)"`.

**Comment by ahmedelgabri** [comment]
I assume like this?

```sh
#!/usr/bin/env sh
eval "$(direnv export bash)"

tmux send-keys -t"SESSION_NAME":2.1 "cd ./some/directory && $EDITOR" C-m
```

But this actually _kind of_ works

```sh
#!/usr/bin/env sh

tmux send-keys -t"SESSION_NAME":2.1 "cd ./some/directory && direnv reload; $EDITOR" C-m
```

But `direnv reload` just doesn't finish before the `$EDITOR` is opened, if I exit `$EDITOR` it finish `direnv reload`, so it feels that it's stuck in the middle while `$EDITOR` was called. Honestly I dunno if this a problem with `direnv reload` itself or my shell script.

**Comment by zimbatm** [comment]
I mean literally replace `direnv reload`. I think this requires a mental model of how direnv is working (assuming that you use bash):

```
$ direnv hook bash
_direnv_hook() {
  local previous_exit_status=$?;
  eval "$(direnv export bash)";
  return $previous_exit_status;
};
if ! [[ "$PROMPT_COMMAND" =~ _direnv_hook ]]; then
  PROMPT_COMMAND="_direnv_hook;$PROMPT_COMMAND";
fi
```
^^ this is what gets installed into bash, the PROMPT_COMMAND is a special hook that executes before each prompt. Essentially what it's doing is execute `eval "$(direnv export bash)"` before every prompt, this is how it's able to update the shell environment dynamically. Because your script is sending a single line to tmux, the shell doesn't have the opportunity to display the prompt.

**Comment by ahmedelgabri** [comment]
I tried that "replacing all `direnv reload` with `eval "$(direnv export bash)"` & it didn't change anything, `$EDITOR` still runs before `eval "$(direnv export bash)"` finishes

**Comment by ahmedelgabri** [comment]
Here is how the script looks like

```sh
#!/usr/bin/env sh

tmux rename-window "test"
tmux new-window -n "$EDITOR"
tmux send-keys -t"test":1.1 'cd /path/to/project/with/.envrc/ && eval "$(direnv hook zsh)"; $EDITOR' C-m
tmux select-window -t"test":1.1
```

**Comment by ahmedelgabri** [comment]
Ok here is how to reproduce 

Some setup
```sh
mkdir /tmp/test-direnv && cd /tmp/test-direnv && echo "export FOO=foo" > .envrc && direnv allow && cd ~
```

Now run the following

```sh 
cd /tmp/test-direnv && eval "$(direnv export bash)"; $EDITOR
```

**Comment by zimbatm** [comment]
I can't reproduce the issue. After running `cd /tmp/test-direnv && eval "$(direnv export bash)"; nvim -u NONE` I can type `:echo $FOO` and it outputs `foo`

**Comment by ahmedelgabri** [comment]
Yeah that worked with normal `export FOO=foo` but it doesn't work with node 🤔 

`.envrc`

```sh
set -e
use node
```

`.nvmrc`

```sh
8.9.1
```

If I do this & run `:!node -v` from inside vim it doesn't output `8.9.1` it outputs the global version not the project specific version.

**Comment by zimbatm** [comment]
is nvim messing with your PATH? try `:echo $PATH`

**Comment by ahmedelgabri** [comment]
tried `:echo $PATH` the path is missing the right node version bin, if I exit & open again `:echo $PATH` will be fixed.

**Comment by zimbatm** [comment]
can you also change the script to be `cd /tmp/test-direnv && eval "$(direnv export bash)" && nvim -u NONE` to make sure that the eval worked successfully ( `;` replaced by `&&` ).

or replace the `.envrc` with: `PATH_add something`. $PWD/something should be in the PATH after this one.

**Comment by ahmedelgabri** [comment]
This works fine, I think the problem is at my end. For now I split this into two & it works

```tmux
tmux send-keys -t"SESSION_NAME":2.1 'cd ./some/directory && eval "$(direnv export bash)"' C-m
tmux send-keys -t"SESSION_NAME":2.1 '$EDITOR' C-m
```

I'll close it & dig deeper why it's not working. Thanks very much for the help
