### ISSUE TITLE
Stdlib command for commands which return exported environment variables as a string?

### ISSUE THREAD

**Issue by danielcompton** [direnv/direnv#349]
## Issue description

I am using [envkey-source](https://github.com/envkey/envkey-source) to store and set sensitive configuration variables. The way that it works, is that when you run it, it returns a string of exported variables:

```bash
$ envkey-source
$ export 'DATABASE_PASSWORD'='abcd' 'HMAC_KEY'='efgh' # e.t.c.
```

Under normal usage, you would run `eval $(envkey-source)` to eval the returned string into your environment. You can also do this with direnv:

```
export ENVKEY=abc

if has envkey-source; then
  eval $(envkey-source --cache)
fi
```

This works fine, but feels slightly icky. Looking at the [stdlib](https://github.com/direnv/direnv/blob/master/stdlib.sh) I saw https://github.com/direnv/direnv/blob/master/stdlib.sh#L229-L235. This looked close to what I want, except that it expects the return value to be a direnv dumped version.

Is there another way to do this, or is what I've got an acceptable way of setting environment variable provided by a third-party tool?

**Comment by zimbatm** [comment]
Is the problem the repetition or something else? 

You could write a function in `~/.config/direnv/direnvrc`:
```sh
load_envkey() {
  eval $(envkey-source --cache)
}
```

Then use `load_envkey` in your `.envrc` files.

**Comment by danielcompton** [comment]
The problem was calling eval on the returned string, I just wondered if there was a more idiomatic way to do this for direnv.

**Comment by zimbatm** [comment]
not really, bash is dirty which makes direnv is a dirty tool :)

**Comment by danielcompton** [comment]
Thanks!
