### ISSUE TITLE
stdin is plumbed up, leading to bugs

### ISSUE THREAD

**Issue by philpennock** [direnv/direnv#350]
## Issue description

stdin is plumbed up, so tools which expect a filename and unexpectedly don't get one, so read from stdin, will try to do so.

### Steps to reproduce

```sh
# in direnvrc function:
[ -n "$version" ] || version="$(head -n 1 $(find_up .foo-version))"
```

If `.foo-version` exists here or up, that works great.  When it doesn't exist, the error is hidden and `direnv` blocks waiting for something on stdin.  While this is clearly a bug in the function for not handling this case, it could be easier to diagnose.

## Technical details

* `direnv version`: 2.15.2
* OS release: Darwin 16.7.0 (macOS Sierra 10.12.6)

## Recommendation

Either of:

1. Re-open stdin on `/dev/null` for the context of `.envrc`
2. Open stdin on a file-descriptor which direnv will immediately send EOF on, but can be watched to print a dire warning that something tried to read from stdin

Approach 2 will be delightful to use, but I haven't looked at direnv's code to know how practical it would be to wire up.

**Comment by zimbatm** [comment]
Thanks for the well written report.

In the current implementation it's possible to add `prompt` commands to the `.envrc`. I don't think it's a common case but that would break backward-compatibility for some users.

**Comment by philpennock** [comment]
Perhaps a direnvrc setting `disable stdin` which can default false for now?

**Comment by zimbatm** [comment]
let's do this :)

**Comment by philpennock** [comment]
Thank you!
