### ISSUE TITLE
add support for elvish

### ISSUE THREAD

**Issue by sbinet** [direnv/direnv#356]
it would be great to add support for `elvish`:
- https://elvish.io/

a fish-like shell, written in Go.

**Comment by zimbatm** [comment]
Does elvish have any hooks that direnv can use to execute before the prompt command?

Adding new output formats is fairly straight-forward. Eg: https://github.com/direnv/direnv/blob/master/shell_tcsh.go

**Comment by zimbatm** [comment]
possibly the `edit:before-readline` hook would work. TBC

**Comment by sbinet** [comment]
Let me see if I can come up with a PR...
