### ISSUE TITLE
Is there a way to have multiple sets of variables? (local, staging, production)

### ISSUE THREAD

**Issue by sardaukar** [direnv/direnv#359]
I usually keep a set of variables like:

- DB_NAME
- DB_HOST
- DB_PORT
... (etc)

And when I run a local Elixir app in an environment other than `development`, I can't re-use these variables. I end up doing:

- TEST_DB_NAME
- TEST_DB_HOST
- TEST_DB_PORT
... (etc)

Which works, but is a bit clunky. This is only a problem locally, to be fair, since my deploy script has the appropriate `DB_HOST` for each environment.

But I'd really like to be able to type `direnv switch staging` for example and have another set of values for the same variables being loaded in. I'm thinking a "state file" would be needed, and a set of `.envrc-development`, `.envrc-staging`, etc files.

Is this a worthy feature? Thanks for any feedback!

**Comment by glasser** [comment]
@zimbatm posted an idea for this literally hours before your issue :)

https://github.com/direnv/direnv/issues/320#issuecomment-388341274

**Comment by sardaukar** [comment]
Thanks, I'll try doing that!
