### ISSUE TITLE
Cascading Environments?

### ISSUE THREAD

**Issue by NeonWizard** [direnv/direnv#360]
## Issue description
I'm not sure if there's already an issue for this, but I would like to be able to have multiple layers of `.envrc`s applied to the current directory from hierarchical folders.

For example, imagine that I'm in the directory `Twitter/AltBot/`. There would be an `.envrc` in `Twitter/` with exports for all of my main account's auth tokens plus Amazon S3 auth tokens, then an `.envrc` in `Twitter/AltBot/` with my alt account's auth tokens. I would want the Amazon S3 auth token exports from the `Twitter/` directory's env file to carry on down to this directory.

* `direnv version`: 2.7.0
* OS release: Windows Bash Subsystem (the Windows part is irrelevant)

**Comment by yermulnik** [comment]
Ain't `source_env` what you're looking for?
https://github.com/direnv/direnv#user-content-loading-layered-envrc

**Comment by NeonWizard** [comment]
You are entirely right. I can't believe I missed that.

**Comment by gurjeet** [comment]
@NeonWizard, @yermulnik, wouldn't `source_up` be the better alternative here?

**Comment by eNcacz** [comment]
In these days the URL above does not contain the `source_env` phrase.
You can see [direnv-stdlib man page](https://github.com/direnv/direnv/blob/master/man/direnv-stdlib.1.md) instead.
