### ISSUE TITLE
https://direnv.net/ is down

### ISSUE THREAD

**Issue by tammersaleh** [direnv/direnv#361]
## Issue description

https://direnv.net/ is returning a 502

### Steps to reproduce

~~~ console
$ curl -i https://direnv.net/
HTTP/2 502
server: Fly.io (25081a9)
set-cookie: fly_cid=b9655374-6291-47fd-b2c1-57341a133d02; Expires=Thu, 20 May 2038 16:53:33 GMT; HttpOnly
vary: Accept-Encoding
content-type: text/plain; charset=utf-8
content-length: 0
date: Fri, 25 May 2018 16:53:36 GMT
~~~

**Comment by tammersaleh** [comment]
Looks like fly.io is down as well:

~~~ console
$ curl -i https://fly.io/
curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
~~~

**Comment by zimbatm** [comment]
http://status.fly.io/ is all green.

direnv.net and fly.io are working from my location.

maybe it's location-dependent or just a transient issue

**Comment by tammersaleh** [comment]
Yeah, must be - I just tried from within GCP, and it's fine.  Feel free to close if you want.

**Comment by glasser** [comment]
fly.io and direnv.net fail for me too. And we use fly.io for something at my work and they had another similar issue earlier this week and didn't update their status page, so I wouldn't trust that too much.

I don't think there's any action to take other than maybe contacting fly.io support.

**Comment by zimbatm** [comment]
For an open source project I am not too worried about availability, but it's good to keep an eye on it. Please keep reporting, I will keep this issue open.

**Comment by glasser** [comment]
Our issue was apparently specific to people in the SF area.

**Comment by glasser** [comment]
I contacted fly support (since we were in touch from Tuesday), they're on it.

**Comment by zimbatm** [comment]
I think we're good right?
