### ISSUE TITLE
it is not possible to perform user level installation (non root) using Makefile

### ISSUE THREAD

**Issue by ssbarnea** [direnv/direnv#363]
## Issue description
At this moment there is no option to perform a `make install --user` which would have installed the executable inside `~/.local/bin` -- the standard(ized) location of  user bin executables.

This is an important feature as it would allow users to install and use direnv without root access to the machines.

**Comment by zimbatm** [comment]
You can do the same with `make install DESTDIR=~/.local`. or `go install .` to install it in $GOPATH/bin
