### ISSUE TITLE
using direnv within cron jobs

### ISSUE THREAD

**Issue by dekhaus** [direnv/direnv#367]
Hi

I have a shell script that works great when I run it manually.  In order for it to run properly - several environment variables need to be set.   I like using direnv to set/manage environment variables.

I'd like to run is periodically by creating a cronjob.

How can I use direnv within the 'context' of a cronjob such that environment variables are read/set dynamically depending on which cronjob is run (aka controlled by the directory in which the script I want to run is contained within) ?

I realize that I can set environment variables with in crontab file - but that doesn't work because those variables will only read once - aka when the crontab file is saved.

Thanks
Dave

**Comment by zimbatm** [comment]
Hi,

I think the best solution would to wrap your script with `direnv exec <LOOKUP_PATH> <CMD> [...ARGS]`.

Let's say that you crontab looks like this:
```
5 * * * * cd /path/to/my/script && ./my_script
```

It would change to:
```
5 * * * * cd /path/to/my/script && direnv exec . ./my_script
```

**Comment by dekhaus** [comment]
Worked Perfectly !!!!

Thanks
Dave

**Comment by zimbatm** [comment]
great, glad I could help!

**Comment by dnk8n** [comment]
I seem to have to execute script directly with bash (for example)

`5 * * * * cd /path/to/my/script && direnv exec . bash ./my_script`

**Comment by dnk8n** [comment]
I actually got best results with the following apprach:

`5 * * * * (cd /path/to/my/script && direnv exec . bash ./my_script) 2>&1 | logger -t my_script`

Then to see logs of my_script:

`sudo grep my_script /var/log/syslog`
