### ISSUE TITLE
use_nix: introduce an argument to enable nix-shell's `--pure` mode

### ISSUE THREAD

**Issue by steveeJ** [direnv/direnv#368]
This is a feature suggestion which would help at debugging dependencies with the help of direnv and nix expressions.

To cite the nix-shell manual:

       --pure
           If this flag is specified, the environment is almost entirely cleared before the interactive shell is started, so you get an
           environment that more closely corresponds to the “real” Nix build. A few variables, in particular HOME, USER and DISPLAY, are
           retained. Note that ~/.bashrc and (depending on your Bash installation) /etc/bashrc are still sourced, so any variables set
           there will affect the interactive shell.

The advantage in this mode is that it becomes immediately obvious when a project depends on something which is installed globally in the system, which is ideally never the case.

/cc @zimbatm

**Comment by zimbatm** [comment]
Did you try `use nix --pure`? All extra arguments should be passed straight to `nix-shell` under the hood.

See the `"#@"` argument in https://github.com/direnv/direnv/blob/002b11e291bc1f6dd352413f52cc76c701caefea/stdlib.sh#L639

**Comment by steveeJ** [comment]
I did just now and I noticed two things:

1. It requires to add direnv as buildinputs in the shell
2. It reloads the direnv after every command.

**Comment by zimbatm** [comment]
Okay so it works but it exposes some issues :)

I think the main issue is that `direnv hook bash` doesn't expand the path of direnv so it will be looked up in the `$PATH`

**Comment by zimbatm** [comment]
@steveeJ can you try this version please? https://github.com/direnv/direnv/pull/369

**Comment by zimbatm** [comment]
Very weird, it shouldn't work! That's the direnv that is supposed to export the environment variables from withing nix-shell..

I pushed another commit that re-generates the stdlib.go file and now uses an absolute path for that direnv executable as well. It exposes another bug where direnv reloads on each prompt.

**Comment by zimbatm** [comment]
That second bug can be reproduces by adding this in an `.envrc`:
```
unset DIRENV_DIFF
unset DIRENV_DIR
unset DIRENV_WATCHES
```
I guess I should be filtering those out of the result first.

**Comment by zimbatm** [comment]
alright, try the latest version?

**Comment by steveeJ** [comment]
> alright, try the latest version?

Entering a direnv directory, working in it, and leaving it all seems to work correctly on 5a0d99b10d7b63f09a2462f19f554df01ef7ec80 :+1:

**Comment by zimbatm** [comment]
alright, thanks for testing! master should be working now

**Comment by steveeJ** [comment]
Thanks for enabling this!

**Comment by zimbatm** [comment]
Fighting for purity, one commit at a time
