### ISSUE TITLE
building and installing from source instructions are broken

### ISSUE THREAD

**Issue by ssbarnea** [direnv/direnv#370]
It seems that the instructions about how to build direnv and install it from source, as user level are broken (in multiple places). Let's address these

Aspects:
- user is likely to want to install in ``~/.local/bin`` as this is the standard/recommended (XDG) location for user binaries.
- user may **not** have GOPATH variable installed.
- ``go`` is assumed to be installed as a system build requirement, hopefully the only one.
- `git clone ...` from the readme is wrong as most users will clone to wrong location, swap it with ``go get github.com/direnv/direnv`` which will clone to expected destination
- cd should look like ``cd ${GOPATH:-~/go}/src/github.com/direnv/direnv`` which assures it works even if GOPATH is not defined.
- ``make install DESTDIR=~/.local`` currently fails with:
```
$ make install DESTDIR=~/.local
which: no go-md2man in (/usr/lib64/ccache:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/johnd/.local/bin:/home/johnd/bin)

Could not generate man page because go-md2man is missing. Run: go get -u github.com/cpuguy83/go-md2man
make: *** [man/direnv.1] Error 1
```

This indicates that build fails due to other go requirements, which should have being downloaded and installed as part of the build. 

Hopefully we will endup creating a reliable script that builds and installs direnv on most platforms.

So far, this script seems to do the dirty work of installing it:

```
go get github.com/direnv/direnv
GOBIN=${GOPATH:-~/go}/bin
if [[ ":$PATH:" != *":$GOBIN:"* ]]; then
   export PATH=$PATH:$GOBIN
fi
cd ${GOPATH:-~/go}/src/github.com/direnv/direnv
make install DESTDIR=~/.local
```

To simplify the install instructions it should be possible to move the PATH alteration inside the Makefile so we would avoid the build failure when go bin folder is not in path.

Another change that I would find nice is to avoid the need to specify DESTDIR=~/.local parameter for make install, and make it the default value for non root users.

**Comment by zimbatm** [comment]
Thanks, I fixed the instructions in 2251df501ce8fdf62483938748f1685eb07db49d

Changing the default DESTDIR seems like a good idea but it means that now I have to explain to users that `~/.local/bin` needs to be in the PATH. I also want to avoid branching based on the uid.

**Comment by zimbatm** [comment]
Closing for now

**Comment by ssbarnea** [comment]
Debian systems already have ~/.local/bin in their default user PATH, and for RPM based ones there is https://fedoraproject.org/wiki/Changes/UserPathPrioritization proposal for making it match Debian order. I only hope it will receive all votes to pass on https://pagure.io/fesco/issue/1913 -- Once it the door is open to implement same change it Red Hat and CentOS.
