### ISSUE TITLE
test/direnv-test.elv: [set|unset]-env not found

### ISSUE THREAD

**Issue by punitagrawal** [direnv/direnv#374]
[set|unset]-env used by test/direnv-test.elv don't seem to be part of elvish. I tried using elvish from debian but also when built from source.

What steps are needed to enable these utilities? If they are external dependencies please document them somewhere to help distro packaging.

**Comment by zimbatm** [comment]
deferring to @sbinet as he contributed that feature

**Comment by zimbatm** [comment]
maybe try version 0.11, I think that's the version that was tested with the feature

**Comment by sbinet** [comment]
FYI, I've developed+tested that feature against `elvish@bac2d370`.
I still see the same functions in the latest `elvish` commits (and what might become `0.12` at some point.0

so... @punitagrawal what is the version you are using (and are you sure `direnv` uses the one you've installed) ?

**Comment by zimbatm** [comment]
master is now testing against elivsh 0.12-rc2 and the tests are passing at least. 0.11 wasn't working for me though.

**Comment by zimbatm** [comment]
closing as it works with 0.12, I added a (0.12+) in the README

**Comment by punitagrawal** [comment]
@sbinet Thanks for clarifying the version requirement. The debian elvish package is based on 0.11 which is what I tried. Packages are usually based on release versions and so the set-env built-in is missing in Debian. (I also mistakenly used 0.11 when I thought I was building HEAD).

In this situation, where a released version of direnv depends on an unreleased dependency, it probably would've been best to delay the direnv package update until the dependency landed.
