### ISSUE TITLE
In WSL, getting "taking a while to execute" even without a .envrc

### ISSUE THREAD

**Issue by kergoth** [direnv/direnv#386]
## Issue description

Every time the prompt is drawn:
```
direnv: ([/home/kergoth/.local/share/go/bin/direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.
```
This is recent, it worked fine until I recently updated things.

### Steps to reproduce

Open a zsh shell under WSL with `eval "$(direnv hook zsh)"` in the zshrc. 
Ctrl-c does nothing, and there is no envrc for it to source.

## Technical details

* `direnv version`: 2.17.0
* OS release: Arch on WSL in Windows 10

**Comment by kergoth** [comment]
Unable to repro, ignore.

**Comment by MHM5000** [comment]
Rebooting the windows fixed it for me.
