### ISSUE TITLE
Separate ConfDir and AllowDir

### ISSUE THREAD

**Issue by mnacamura** [direnv/direnv#390]
## Issue description

I use direnv with Nix. I think that I will be happy if I can wrap direnv with my custom direnvrc. So I tried to do something like this:
```nix
let
  configDir = runCommand "direnv-config-dir" {} ''
    install -D -m 444 "${./direnvrc}" "$out/direnv/direnvrc"
  '';
in
buildEnv {
  name = "${direnv.name}-wrapper";
  paths = [ direnv ];
  buildInputs = [ makeWrapper ];
  postBuild = ''
    makeWrapper ${direnv}/bin/direnv $out/bin/direnv \
      --set XDG_CONFIG_HOME "${configDir}"
  '';
}
```
EDIT1: I replaced `DIRENV_CONFIG` to `XDG_CONFIG_HOME`.
EDIT2: I noticed that this wrapper is incomplete as `direnv stdlib` uses `XDG_CONFIG_HOME` at runtime and the above `configDir` is ignored.

However, this fails because `direnv allow` tries to write in a read-only directory:
```
$ direnv allow
direnv: error mkdir /nix/store/02c01g5rrvbx0rhbkv4r33yj8l2kvcz3-direnv-config-dir/allow: read-only file system
direnv: error .envrc is blocked. Run `direnv allow` to approve its content.
```

Given this, I think that it would be nice to separate ConfDir and AllowDir, or enable to load configuration file by passing its path via some environment variable. Or, is there any better and easier solution?

## Technical details

* `direnv version`: 2.17.0
* OS release: nixos-18.09pre148970.b5b11e9da43

**Comment by doronbehar** [comment]
See #406 .
