### ISSUE TITLE
Direnv in a monorepo setup 

### ISSUE THREAD

**Issue by Globegitter** [direnv/direnv#396]
## Issue description
We are having a monorepo setup with [bazel](https://bazel.build) and it has the concept of a workspace and targets within that workspace that can be built/run and I can run any target from within any other directory of the workspace. 

To make this a bit more cleare here an example:

Imagine  following dirctiroy layout:
```
/workspace-root
  /project1
    .envrc
  /project2
     .envrc
```
So each project is a subdirectory within the workspace and has a binary target, e.g. a Webserver that consumes the env variables defined in its respective .envrc file. That works fine if I go into that directory and invoke bazel there, but it is very common to invoke bazel in the workspace root and run the binary target in a subdirectory, and as mentioned I could also run the project1 binary from the project2 dir. 

So is it somehow possible to invoke direnv manually (well, it would be invoked by a wrapper script around Bazel on each run) and tell it on invokation load me the envrc from this directory? This would be ideal as then one can be in any directory, even possibly without an .envrc and it would be ensured the binary has access to the right env vars. 

One solution that I have thought of is i could just support the common case of when bazel is run in the root dir, making use of `watch_file` and `source_env`. The other solution i suppose is i could make use of `direnv exec`, but there are no plans for something like `direnv load [DIR]`? 

* `direnv version`: 2.17.0
* OS release: (eg: Ubuntu 16.04) Ubuntu 16.04

**Comment by zimbatm** [comment]
One option would be to use `direnv exec <DIR> <COMMAND>` to load the `.envrc` of that sub-folder before executing the command. Eg: `direnv exec ./project1 ./project1/bin/project1`.

Or with a `./run` wrapper:
```sh
#!/usr/bin/env bash
set -euo pipefail
# cd in the folder of the target binary
pushd "$(dirname "$0") &>/dev/null
# eval direnv in that context
eval "$(direnv export bash)"
# restore the original $PWD
popd
# execute the passed command
"$@"
```
And then invoke `./run ./project1/bin/project1`

**Comment by Globegitter** [comment]
Ahh the second option is a very interesting one I have not thought about - thanks for sharing that. I think these two options are sufficient enough to fulfill this use-caw and I can close this - thanks for the response.
