### ISSUE TITLE
direnv does not work when iTerm2 shell integration is installed

### ISSUE THREAD

**Issue by btruhand** [direnv/direnv#399]
## Issue description
It seems that iTerm2's [shell integration](https://www.iterm2.com/documentation-shell-integration.html) causes direnv to not work. After installing shell integration going into a directory that has a `.envrc` file won't load the envrc (calling `direnv reload` also does not work) and of course exiting the directory doesn't unload anything.

Interestingly if I work to run a fresh iTerm session within a directory that has a `.envrc` it does load it, but will not unload or load any other `.envrc` when going outside or into directories

### Steps to reproduce
1. Install iTerm2 shell integration
2. Go to some directory that has `.envrc`
3. Try going outside of the directory

## Technical details

* `direnv version`: v2.17.0
* OS release: Mac OS High Sierra 10.13.16

I don't know if direnv has any logs that I can look into to help debug or anything. If it's believe this is more of an iTerm issue then please tell me and feel free to close the issue

**Comment by btruhand** [comment]
@zimbatm sorry for late reply and yup moving the `PROMPT_COMMAND` worked for me. Thanks for that, had no idea how to debug it so that was a great help

**Comment by zimbatm** [comment]
no problem. If you have the time it would be good to report the issue to iTerm since they are causing the problem

**Comment by davehowell** [comment]
I've also had this issue and found adding the line _after_ the iterm2 shell integration line didn't work for me. I've raised it with the iterm2 gitlab project as suggested by @zimbatm see  https://gitlab.com/gnachman/iterm2/issues/7961
