### ISSUE TITLE
Question: Why can't direnv override prompt

### ISSUE THREAD

**Issue by haizaar** [direnv/direnv#408]
I've tried to read around how direnv works and I fail to understand why it doesn't override `PS1` (shell prompt), i.e.
```
export PS1=foo
```
in `.envrc` does not seem to have any effect. If direnv calculates the diff and applies it to the current shell environment, then why `PS1` is special?

Direnv 2.17.0.

P.S. Thanks a lot for developing this tool and making it great. It helps a lot in local development with microservices approach where each of them has separate configuration.

**Comment by zimbatm** [comment]
It's a natural question.

1. PS1 is usually a local variable and not environment variable.
2. There was a bug in macOS' bash 3.x implementation that would crash the shell if PS1 was unset.

Those two combined led me to blacklist PS1 as and environment variable that can be changes.

As a workaround, an option is to build a PS1 that understands environment variables.

Eg:
```
PS1='${CUSTOM_PS1:-default PS1}: `
```

And then in the `.envrc`: `export CUSTOM_PS1=mycustomPS1`

**Comment by haizaar** [comment]
Thanks for the explanation.
The hint you suggest does the trick obviously. May be it worth posting under "Common things people don't know"?

**Comment by zimbatm** [comment]
copied to https://github.com/direnv/direnv/wiki/PS1, thanks!

**Comment by haizaar** [comment]
Good day,

Do you know how your workaround can be applied to zsh?

**Comment by zimbatm** [comment]
It should work the same under zsh AFAIK. Have you tried it?

**Comment by haizaar** [comment]
Yes I tried and it doesn't unfortunately. The problem is that zsh does not
support functions in environment variables.
Do you have other ideas?

**Comment by krc** [comment]
Can you explain in more detail what you did, I don't understand the explanation. I am trying to see if I can get a special svn prompt in certain dirs (per .envrc), but not have it in others.

**Comment by haizaar** [comment]
Here is an example that works for me: https://github.com/direnv/direnv/wiki/Python#bash

The similar example for zsh that follows does not work for me (but I ma be missing something, since I'm not zsh user).

**Comment by mogorman** [comment]
@zimbatm could direnv issue a warning if people try to set PS1 guiding them to that wiki page?

**Comment by zimbatm** [comment]
good idea, happy to get a PR for that

**Comment by mogorman** [comment]
https://github.com/direnv/direnv/pull/483

**Comment by RoDuth** [comment]
I realise this is a long closed issue but for future reference...

(osx, zsh, a bunch of python projects using direnv to source virtual environments, I never use direnv to set PS1)

If I'm right, looking at the [wiki](https://github.com/direnv/direnv/wiki/PS1), the expected behaviour since #483 is now to get a "direnv: PS1 cannot be exported..." warning whenever I `cd` into a project where I have a .envrc that sources a python virtual environment.  To suppress it I need to add `unset PS1` to the end of each .envrc and then `direnv allow` them?

Quick fix:
```
$ cd python_projects_root_dir
$ find . -type f -name ".envrc" -execdir sh -c 'echo "unset PS1" >> .envrc; direnv allow' \;
```

**Comment by zimbatm** [comment]
I think direnv should be changed and only emit that error whenever PS1 is part of the diff.

Another workaround is to change the zsh profile configuration to only set, not export the PS1.

**Comment by doolio** [comment]
@haizaar @zimbatm FYI, I've added a generic example for updating the `PS1` to the [wiki](https://github.com/direnv/direnv/wiki/PS1) page. It avoids the use of a function. Added a link to the same wiki page from the python wiki page as well but kept the examples it offers.
