### ISSUE TITLE
.env variables are not expanded

### ISSUE THREAD

**Issue by haizaar** [direnv/direnv#411]
Good day,

Using `dotenv` from stdlib to load `.env` file does not seem to expand variables in the latter:

```sh
/tmp $ mkdir /tmp/tst; cd /tmp/tst
/tmp/tst $ echo 'FOO=${PWD}' > .env
/tmp/tst $ echo 'dotenv' > .envrc
direnv: error .envrc is blocked. Run `direnv allow` to approve its content.
/tmp/tst $ direnv allow
direnv: loading .envrc
direnv: export +FOO
/tmp/tst $ echo $FOO
${PWD}
```

I would actually expect `FOO=/tmp/tst`. At least this is what pipenv does :)

Direnv version 2.17.0

Thank you,
Zaar

**Comment by zimbatm** [comment]
hi,

yes variable expansions are currently not supported: https://github.com/direnv/go-dotenv#missing

I don't have anything against them, it's just that I didn't have the personal need for them. Happy to get a PR!

**Comment by haizaar** [comment]
I see
No worries, replaced with `source_env .env` :)

As for PR - looks like a nice thing to start with when I decide to learn Go one day. To clarify - the link you sent me is a direnv's own implementation of dotenv, right?

**Comment by zimbatm** [comment]
ok great :)

yes that's the package that direnv is using. It's quite self-contained so I decided to extract it out.

**Comment by hakamadare** [comment]
@haizaar this is fixed by #433

**Comment by zimbatm** [comment]
and merged. Thanks @hakamadare for implementing that feature!

**Comment by haizaar** [comment]
Thank you! Looking forward to test in the next release.

**Comment by hakamadare** [comment]
hey @zimbatm - any thoughts about when you might put out the next minor release?

**Comment by zimbatm** [comment]
soon ;)
