### ISSUE TITLE
Set DIRENV_WARN_TIMEOUT to never warn me

### ISSUE THREAD

**Issue by shadowrylander** [direnv/direnv#419]
## Question

Hello!
How do I set the DIRENV_WARN_TIMEOUT variable to never come up? I.E. never warn me?

## Technical details

* `direnv version`: 2.10.0
* OS release: WSL WLinux

**Comment by shadowrylander** [comment]
Holy...! That's a lotta years! Thanks!

**Comment by shadowrylander** [comment]
Whoops, forgot something: I'm using it to open another shell, with my primary being `fish`; do I have to export the variable in the other shell as well? Because it comes up either way. Or does it just go in `~/.bashrc`, without touching `~/.config/fish/config.fish`?

**Comment by zimbatm** [comment]
Environment variables are inherited from the parent process.

For example if you start X11, you could set the environment variable in `~/.xprofile`. Below that the terminal emulator might set some environment variables. Then the terminal emulator will load the shell. If the terminal emulator is set to "login" then it will also load /etc/profiles before starting the shell.

Each shell has their own environment loading mechanism. For example bash's look like this: ![bash loading](https://lh3.googleusercontent.com/proxy/9sl1V_6wd7TzdvZdKWyl5o8DhUZTio33P2oU87ayFxxcgpZ1avgmCgT2FH67XbJHcvPd5q6qjTvsWmnI5APpDCOAafTYbfzcuQ87d6cGJxu_DsdS=s0-d)

fish shell probably has it's own, I will let you look this up :)

**Comment by shadowrylander** [comment]
Thanks for the help, then!

**Comment by zimbatm** [comment]
I think this should really be a direnv configuration option.

**Comment by zimbatm** [comment]
It's an old feature and it hasn't been converted to the ~/.config/direnv/config.toml file yet

**Comment by zimbatm** [comment]
This option has now been made configurable in #489

**Comment by br4ch1st0chr0n3** [comment]
@zimbatm, is there an alternative since this option is deprecated?
