### ISSUE TITLE
direnv snap

### ISSUE THREAD

**Issue by ipolyzos** [direnv/direnv#425]
## Issue description
Snaps packaging proposal for _**direnv**_

## Proposal details
I would like to share some early work on packaging _**direnv**_ as a snap and kindly ask your feedback and thoughts. Please note this work is not complete but aim to act as a starting point toward this. You can find the source on _**https://github.com/null-box/direnv-snap**_.

**Comment by zimbatm** [comment]
Nice!

Do snap package know how to expose manpages that are part of a snap to the user? You might want to use `make install DESTDIR=${SNAPCRAFT_PART_INSTALL}` instead to build and install direnv if that is the case.

Other than that it looks good. Let me know when you think that this is stable enough and it can be added to the direnv README.md as a distribution method.

**Comment by zimbatm** [comment]
Also make sure to Watch the direnv repository for new releases. This is a new GitHub feature that might be handy for you to keep the snap package fresh.

**Comment by ipolyzos** [comment]
@zimbat, unfortunately, seems not to support man pages yet. Please refer to https://forum.snapcraft.io/t/support-for-man-pages/2299/14

I will proceed with the use of _make install_ and keep you up to date on the progress.

**Comment by ipolyzos** [comment]
I have proceeded with the changes and uploaded the releases from **2.12.0** - **2.18.2** in snapstore. You can find the latest source code at [github.com/null-box/direnv-snap](https://github.com/null-box/direnv-snap) while the snapstore entries can be accessed at [snapcraft.io/direnv](https://snapcraft.io/direnv).

You should be able to install the snap with just **snap install direnv**.

**Comment by zimbatm** [comment]
thanks! I added Snap to the list of distributions in https://github.com/direnv/direnv/pull/426

**Comment by ipolyzos** [comment]
The snap package has granted use of classic confinement from the snapcraft community.

I will go through and rebuilt the snapcraft artifact from the https://github.com/ipolyzos/direnv-snap repository.
