### ISSUE TITLE
Support virtualenvs created via "python -m venv"

### ISSUE THREAD

**Issue by pmav99** [direnv/direnv#428]
## Issue description
Unfortunately, there are more than one ways to create a virtualenv in python. 

The most common one is of course the `virtualenv` package which you can get from [PyPi](https://pypi.org/project/virtualenv/). But you can also use the `venv`  module which is [in the standard library](https://docs.python.org/3/library/venv.html). They are roughly equivalent but not 100% compatible ([example](https://bugs.python.org/issue30811#msg313131)). You could probably even say that `venv`, which is a much newer project, is the official way, even though `virtualenv` has a wider userbase.

Anyway, the current implementation of `layout python` does support `virtualenv` but not the `venv` module. The problem is easily reproduced if virtualenv is uninstalled.

My guess is that direnv assumes that the virtualenv script is always present, which might not always be the case. #376  Might also want to take this under consideration.

### Steps to reproduce

1. Make sure that `virtualenv` is not in the path (e.g. uninstalled)
2. Create a new virtualenv using the `venv` module: `python -m venv ./.venv
3. Create an `.envrc` with `layout python`
4. Activate direnv: `direnv allow`
5. You get the following error and the venv is not activated:
```
direnv: loading .envrc                                                                                                                                                                                             
environment: line 447: virtualenv: command not found
direnv: export +VIRTUAL_ENV ~PATH
```

## Technical details

* `direnv version`: 2.18.2
* OS release: 4.19.8-arch1-1-ARCH #1 SMP PREEMPT Sat Dec 8 13:49:11 UTC 2018 x86_64 GNU/Linux

**Comment by zimbatm** [comment]
Since they are not 100% equivalent it might be better to create a new layout for them. I guess `venv` is python bringing virtualenv to the stdlib and so has less support(?).

It would be nice if direnv could source stdlib functions from externally-maintained sources as I don't use python enough to make good judgement calls.

For now I recommend overriding the `layout_python` function in your `~/.config/direnv/direnvrc` with the snippet from https://github.com/direnv/direnv/wiki/Python#venv-stdlib-module

**Comment by pmav99** [comment]
Oh, I didn't know about that wiki page :)
The layout for venv works just fine. 

Not sure if I should close the issue or not though. You might want to keep it open in order to add the layout to direnv, but even if you don't, adding a configuration file is no biggie.

**Comment by zimbatm** [comment]
I will add a mechanism to direnv to allow sharing of stdlib functions instead. It's nice to have some defaults built-in but it's too much work if direnv is responsible for maintaining all of them.
