### ISSUE TITLE
[WIKI] Update Restoring PS1

### ISSUE THREAD

**Issue by okomarov** [direnv/direnv#439]
## Issue description
Restoring the PS1 as in the [wiki](https://github.com/direnv/direnv/wiki/Python#restoring-the-ps1) does not play well with manual activations of the virtual environment and appends the `(virtual_env)` twice.

This is in VSCode when opening a new terminal window (I did not type the `source ...`, is auto-executed):
![screenshot 2019-01-09 at 14 52 37](https://user-images.githubusercontent.com/3731173/50907136-88e82380-141e-11e9-94ea-e7731b33a73e.png)

This is in iTerm after cloning a repo and creating a virtual env with `mkvirtualenv`:
<img width="713" alt="screenshot 2019-01-09 at 14 59 42" src="https://user-images.githubusercontent.com/3731173/50907457-5985e680-141f-11e9-8404-1f75d618b949.png">

### Steps to reproduce
Before `cd`-ing into a folder with an `.envrc`, activate the virtual environment of that `folder`, e.g.: 
```
source path/to/virtual/env/in/folder/
cd folder
```

### Suggested solution
Append `string` if not a substring of `PS1`:
```bash
show_virtual_env () {
  if [ -n "$VIRTUAL_ENV" ]; then
    string="($(basename $VIRTUAL_ENV))"
    if [[ "$PS1" == *"$string"* ]]; then
      echo $string
    fi
  fi
}
```

* `direnv version`: 2.18.2
* OS release: macOS 10.14.2

**Comment by zimbatm** [comment]
I updated to wiki to also check if `$DIRENV_DIR` is set as well. This assumes that you would either use virtualenv, or direnv with virtualenv, but not nest direnv and virtualenv.

**Comment by okomarov** [comment]
@zimbatm Thanks for looking into this!

The current solution was compaining `show_virtual_env:[:1: ']' expected` so I added another set of `[]` but this does not yield the desired result:

<img width="621" alt="screenshot 2019-01-10 at 11 47 53" src="https://user-images.githubusercontent.com/3731173/50966691-ae803600-14cd-11e9-914a-6985e091e4db.png">

**Comment by okomarov** [comment]
@zimbatm Thanks for looking into this!

The current solution was compaining `show_virtual_env:[:1: ']' expected` so I added another set of `[]` but this does not yield the desired result:

<img width="621" alt="screenshot 2019-01-10 at 11 47 53" src="https://user-images.githubusercontent.com/3731173/50966691-ae803600-14cd-11e9-914a-6985e091e4db.png">

**Comment by zimbatm** [comment]
Thanks I fixed the wiki.

Ok so you *are* activating the virtualenv manually from within a .envrc-loaded folder. Can you also add a check for `&& -z "$_OLD_VIRTUAL_PS1"` to the condition list ?

Alternatively you could create another `.envrc` in the sub-folder with:
```sh
# load the parent .envrc
source_up
# let direnv handle the virtualenv
layout python
```

**Comment by okomarov** [comment]
It's VSCode, for whatever reason executes the source when opening a new terminal window.

@zimbatm Thanks the `&& -z "$_OLD_VIRTUAL_PS1"` actually solves the issue.
