### ISSUE TITLE
Wiki can be edited by anyone without approval process

### ISSUE THREAD

**Issue by jottr** [direnv/direnv#444]
## Issue description
I was able to change content on the wiki pages, without anyone having to review my changes

I edited the python page on the wiki. The changes went live without anyone approving the changes. 
Someone could sneak in malicious code into configuration examples. 
I suggest that changes to the wiki should be approved before publishing.

**Comment by zimbatm** [comment]
I believe that most people are good people. So far it hasn't been a problem and people have been respectful. Also, Github's only toggle on the Wiki is to restrict the access to committer people. It means that everyone else is locked out of the wiki.

**Comment by zimbatm** [comment]
added a footer to let people know that the wiki is open to everyone
