### ISSUE TITLE
layout_go: same gopath is concatinated twice

### ISSUE THREAD

**Issue by acuteaura** [direnv/direnv#447]
## Issue description

`layout_go` will append the gopath to an already set one, even if it's the same

```
$ echo $GOPATH
/Users/gant/go
$ direnv allow
$ echo $GOPATH
/Users/gant/go /Users/gant/go
```

### Steps to reproduce

1. use an envrc at the root of your gopath with only `layout_go`.
2. get a terminal with GOPATH already set (i.e. using the integrated terminal in GoLand which inherits the IDE environment)

## Technical details

* `direnv version`: 2.19.0
* OS release: (eg: Ubuntu 16.04) macOS 10.13.2

**Comment by zimbatm** [comment]
This is actually true for all calls to `PATH_add` and `path_add`. direnv doesn't try to de-duplicate entries and only prepends the new paths.

Practically speaking the new GOPATH is valid but it would sure be nice to clean that up. Happy to take a PR to remove the last entry when one is duplicated.

The main reason that it wasn't implemented before is that doing such thing in Bash is generally not very nice.
