### ISSUE TITLE
Export/loading output displayed with any command

### ISSUE THREAD

**Issue by jc00ke** [direnv/direnv#458]
## Issue description

I upgraded from 2.14.x today to 2.19.1 and when I run any command the `direnv` output is displayed.

### Steps to reproduce

1. Install 2.19.1 and set up for `fish`. Run any command in a dir with a `.envrc`.
1. Downgrade to 2.19.0 and the output goes away. See screenshot.

## Technical details

With 2.19.1

![image](https://user-images.githubusercontent.com/18191/52515326-dcd95a00-2bce-11e9-8700-43eb8b1424ae.png)

With 2.19.0

![image](https://user-images.githubusercontent.com/18191/52515306-98e65500-2bce-11e9-96f5-a694a5795c03.png)

* OS release: Manjaro + i3

**Comment by zimbatm** [comment]
thanks, this should be fixed by #457. Cutting a release right now.

**Comment by jc00ke** [comment]
Ah yeah, I had just added a symlink.
