### ISSUE TITLE
`direnv export json` output malformed when .envrc not yet allowed

### ISSUE THREAD

**Issue by Profpatsch** [direnv/direnv#467]
## Issue description

When running `direnv export json` in a directory with a modified `.envrc`, an error message is appended to the json on stdout, breaking the json output.

For `direnv-mode` in Emacs that means the mode globally disables itself for all buffers because it can’t parse the output of direnv. 

### Steps to reproduce

In a shell *without* direnv hook enabled:
```
$ mkdir repro && cd repro
repro$ echo "export FOO=BAR" >> .envrc
repro$ direnv export json
# direnv export json
{
  "DIRENV_DIFF": "eJyqVipQsqqu1VHKU7KqVnLxDHL1C4t38QxSslLS1c_Iz03VL8jIzMks0M_OL9Evzy_K1i8pT01M18_JLyrK1M9LLddPy89Xqq0FBAAA__9Bixhq",
  "DIRENV_DIR": "-/home/philip/kot/work/tweag/lorri/new/foo",
  "DIRENV_WATCHES": null,
  "FOO": null
}direnv: error .envrc is blocked. Run `direnv allow` to approve its content.
```

## Improvement

The `direnv export json` output should always return a valid json file on stdout, and nothing else on stdout or stderr. All other messages should be included in the structured json.

For that I suggest a redesign of the json message, in that every json message output by `direnv` is wrapped in an object with meta-information about the message:

```json
{ "direnv-version": "2.19.2"
, "type": "export"
, "success": true
, "result": {
     "DIRENV_DIFF": …
  } }
```

or in case of an error:

```json
{ "direnv-version": "2.19.2"
, "type": "export"
, "success": false
, "error":
    { "type": "not-allowed"
    , "file": "/path/to/repro/.envrc" }
}
```

whereby `{ "type": "xyz", … other fields }` is a crude representation of sum types.

## Technical details

* `direnv version`: 2.19.2
* OS release: nixos master

**Comment by zimbatm** [comment]
the bug here is that DIRENV_WATCHES shouldn't be empty. emacs would load the empty environment and only attempt to reload if the .envrc gets changed. This would mean fixing #224

**Comment by Profpatsch** [comment]
> emacs would load the empty environment and only attempt to reload if the .envrc gets changed.

So that might be an issue, but right now `emacs-direnv` disables itself because of the non-parsable json. I’ll change the error message to be put to `stderr` for now.

**Comment by Profpatsch** [comment]
The error message is in fact output on `stderr`, I was mislead by the way it appended to the json output. So `direnv` does the right thing here.
