### ISSUE TITLE
layout_pipenv missing from docs

### ISSUE THREAD

**Issue by thernstig** [direnv/direnv#471]
## Issue description

It seems layout_pipenv is missing from https://direnv.net/#man/direnv-stdlib.1 but it exists and works fine.

https://github.com/direnv/direnv/blob/2e7828b48b5ad82981bb355d1e67d95a85e6df53/stdlib.sh#L502-L526)

Awesome tool by the way!

**Comment by zimbatm** [comment]
Thanks!

Do you mind submitting a PR? the doc is under man/direnv-stdlib.1.md

**Comment by mUtterberg** [comment]
Dropping a link to [the repo wiki entry](https://github.com/direnv/direnv/wiki/Python#pipenv) for `layout_pipenv` in case someone wants to submit the PR. (I'll have time at the end of the month, if need be.)

This is the second docs issue in a row I've run across this morning. Thoughts on adding a `docs` label? Not crucial, but I'm a fan of categorizing that separately.
