### ISSUE TITLE
direnv allow has no effect when i have a .envrc file

### ISSUE THREAD

**Issue by coulonxyz** [direnv/direnv#476]
## Issue description

I'm running Ubuntu 18.04. This is a new installation.

When I issue the command direnv allow in a directory with a.envrc file, nothing happens:
```
➜  ts git:(master) ✗ ls .envrc 
.envrc
➜  ts git:(master) ✗ direnv allow .
➜  ts git:(master) ✗ cat .envrc    
export FOO=foo
➜  ts git:(master) ✗ echo $FOO

➜  ts git:(master) ✗ 
```

When there is no .envrc file, it complains though:
```
➜  Projects ls .envrc     
ls: cannot access '.envrc': No such file or directory
➜  Projects direnv allow .
direnv: error .envrc file not found
```

I've install direnv from apt-get and added the following line to .zshrc:

```
# direnv
eval "$(direnv hook bash)"
```

### Steps to reproduce

New installation. install from apt-get and follow instructions

## Technical details

* `direnv version`:v2.15.0
* OS release: Ubuntu 18.04

**Comment by coulonxyz** [comment]
Well, it works with bash but not zsh... even if I have do the eval "manually", nothing happens when i get in the directory or type direnv allow.

**Comment by zimbatm** [comment]
@coulonxyz the hook is shell-specific, so it should be `eval "$(direnv hook zsh)"` bash => zsh

**Comment by sheeeng** [comment]
@coulonxyz, it is also explained in this [section](https://github.com/direnv/direnv#zsh).

**Comment by coulonxyz** [comment]
oh my. What an idiot. Thanks a lot.

**Comment by zimbatm** [comment]
it happens to the best of us :)

**Comment by zigomi** [comment]
@coulonxyz I agree with you - you're an idiot.

**Comment by hraban** [comment]
Extremely niche reason this could happen: for bash, direnv hooks itself into the `PROMPT_COMMAND`. If you override that in your own bashrc _after_ direnv is loaded, without appending the original value, you'll lose direnv integration with the shell.

Wrong:

```bash
PROMPT_COMMAND='echo "I am a custom prompt command"'
```

Correct:

```bash
PROMPT_COMMAND='echo "I am a custom prompt command"'"${PROMPT_COMMAND+;$PROMPT_COMMAND}"
```

Or you can just make sure that the `eval direnv hook` line is at the bottom of your bashrc :)

P.S.: For completeness: if you look at the direnv hook itself they have a neat trick to handle the alternative scenario where PROMPT_COMMAND is an array which is pretty slick:

```bash
  if [[ "$(declare -p PROMPT_COMMAND 3>&1)" == "declare -a"* ]]; then
    PROMPT_COMMAND=(_direnv_hook "${PROMPT_COMMAND[@]}")
  else
    PROMPT_COMMAND="_direnv_hook${PROMPT_COMMAND:+;$PROMPT_COMMAND}"
  fi
```

I guess if you really wanna go full maximal interoperability on your own bashrc, this is something to explore. :D
