### ISSUE TITLE
Direnv requires globstar?

### ISSUE THREAD

**Issue by armarti** [direnv/direnv#477]
## Issue description
Direnv finally works on my computer, and I think it's only because I added `shopt -s globstar` to my `~/.bashrc`.

### Steps to reproduce
1. Add `shopt -u globstar` to the end of `~/.bashrc`
2. Open a new terminal
3. Go somewhere where direnv should work
4. It might not work (mixed results on my computer)

## Technical details
Nothing hard

* `direnv version`: 2.19.0
* OS release: macOS 10.14 Mojave

So yeah, direnv worked great a few months ago, then I made a lot of changes to my .profile & .bashrc, and it didn't work anymore. Now that I've added enabled globstar in my .bashrc, it suddenly works.

I can't be 100% sure that this is the reason it started working again, but it's the only change I've made to my terminal init scriptas, and now suddenly I'm prompted to run `direnv allow`.

So a two-parter here:
1. Can a developer confirm globstar is required for direnv to work?
2. If so, could this be made more obvious during the installation process, or perhaps show a warning whenever a user runs `eval "$(direnv hook bash)"` when globstar is not enabled?

Super useful tool though. Keep up the good work.

**Comment by zimbatm** [comment]
@armarti it's possible, I am not aware of that requirement though.

Can you explain what the symptoms were?

**Comment by zimbatm** [comment]
Running `shopt -s globstar` and then entering a directory is working fine

**Comment by zimbatm** [comment]
I am missing too much context to reproduce this issue. Closing
