### ISSUE TITLE
Annoying loading and unloading messages. How to mute?

### ISSUE THREAD

**Issue by smeagolthellama** [direnv/direnv#481]
## Issue description

I am using direnv to make a game, (please, don't comment on this, I have my reasons.), and I sort-of need it to not print the loading/unloading messages. 
```
direnv: loading .envrc
[...]
direnv: unloading
```

is there any way to suppress these messages?

### Steps to reproduce

Any .envrc that I have seen does this.

## Technical details

* target shell: bash
* `direnv version`:2.10.0
* OS release: devuan ASCII

**Comment by zimbatm** [comment]
> (please, don't comment on this, I have my reasons.)

I would love to hear more about this :)

Setting `export DIRENV_LOG_FORMAT=` in your ~/.bashrc or profile should do what you want.

**Comment by smeagolthellama** [comment]
can I do this in the relevant .envrc? (say, I want to have certain directories in which it does say these things, and some others where it doesn't) Or will it only apply afterwards?

**Comment by zimbatm** [comment]
it has to be set externally, direnv is already displaying some logs before it loads the `.envrc`

**Comment by sumitkumar1209** [comment]
> > (please, don't comment on this, I have my reasons.)
> 
> I would love to hear more about this :)
> 
> Setting `export DIRENV_LOG_FORMAT=` in your ~/.bashrc or profile should do what you want.

This worked for me. My primary reason to disable this was `oh-my-zsh` was filling half of screen at any new terminal window talking about this log. While I need this still to show direnv is working, that particular warning created a lot of productivity problems for me. I cannot disable that warning as it shows usable messages too.
