### ISSUE TITLE
`direnv exec`: impossible command line

### ISSUE THREAD

**Issue by Profpatsch** [direnv/direnv#492]
`exec [DIR] COMMAND [...ARGS]:`

Means that both `DIR` and an unspecified amount of `ARGS` are optional.
It should be impossible for `direnv` to figure out whether the second argument is a `DIR` or `COMMAND`.

And indeed:

```
> direnv exec echo a b c
direnv: error stat echo: no such file or directory
> direnv exec $PWD echo a b c
direnv: loading .envrc
a b c
```

* target shell: fish
* `direnv version`: 2.19.2
* OS release: NixOS 18.09

**Comment by zimbatm** [comment]
yes it's not great, the result of organic growth. But I don't want to break backward-compatibility now.

The best solution is to always pass the DIR and use `.` as the default.

**Comment by Profpatsch** [comment]
Since the behavior always requires `DIR` in practice, we can just mark it as non-optional in the docs.

**Comment by Profpatsch** [comment]
Oh wait … wait

https://github.com/direnv/direnv/blob/e05d32acd87bce0adfee2191c4dbae078218acb4/cmd_exec.go#L33-L43

**Comment by zimbatm** [comment]
yeah, it's bad...

**Comment by Profpatsch** [comment]
The “just a command” case is broken at the moment however:

```
> direnv exec bash
direnv: error stat bash: no such file or directory
```

I think that needs to be fixed nonetheless.

**Comment by zimbatm** [comment]
Ok, let's make the DIR mandatory then. It must have been broken for a long time and nobody complained.
