### ISSUE TITLE
Using layout_pipenv causes "direnv: error exit status 1" in new directory

### ISSUE THREAD

**Issue by metafeather** [direnv/direnv#500]
**Describe the bug**
Using **`layout_pipenv`** causes `direnv: error exit status 1` in a new directory.

This is due to `layout_pipenv` raising the error when trying to determine if a virtualenv already exists, and `set -e` is activated in the .envrc sub-shell (see #245)

**To Reproduce**
1. `cd $(mktemp -d -t my_python_package)`
2. `touch Pipfile`
3. `echo "layout_pipenv" > .envrc`
4. `direnv allow`
5. `fail: direnv: error exit status 1`

**Expected behavior**
On first run of direnv allow a new virtualenv should be created and activated. On subsequent runs the virtualenv should be activated.

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14.5 using builtin Terminal.app
 - `bash --version`: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin18)
 - `direnv version (installed via Homebrew): 2.20.1`
 - `pipenv --version (installed via Homebrew): pipenv, version 2018.11.26`

**Additional context**
This is probably not the most common scenario since users probably create the Pipefile using pipenv which implicitly creates the virtualenv. However it is common enough (for my users at least) when checking out a project containing a Pipfile and .envrc.

**Comment by metafeather** [comment]
For end users this issue can be worked around by using `! layout_pipenv` in the .envrc file instead. This causes `set -e` to ignore the error ([ref](https://stackoverflow.com/questions/11231937/bash-ignoring-error-for-a-particular-command))

The actual `error exit status 1` is from `layout_pipenv()` in stdlib.sh (#314):

`venv=$(pipenv --bare --venv 2>/dev/null)`

and this can also be suppressed by prefixing with ! with no other side-effects.

Users may alternatively  override `layout_pipenv()` in their own `.direnvrc` until fixed in a release.

**Comment by JacobHayes** [comment]
@metafeather I was able to repro with the system bash 3.2, but it works fine with bash 5.0 from brew. Given `pipenv --bare --venv` returns 1 in both versions, it seems it _should_ be broken in bash 5.0.

Can you try out the version in https://github.com/direnv/direnv/pull/510 and see if that fixes your issue? You should be able to test with the following:

`/usr/bin/make build && mv /usr/local/bin/direnv /usr/local/bin/direnv.bak && mv direnv /usr/local/bin/direnv`

(I couldn't get it working with `make` from brew without renaming `GNUmakefile` -> `Makefile`, hence the `/usr/bin/make`)

**Comment by metafeather** [comment]
@JacobHayes this looks good.

```
/usr/bin/make --version: GNU Make 3.81
/usr/local/bin/go version (installed via Homebrew): go version go1.12.5 darwin/amd64
./direnv --version: 2.20.1
```

Running through the original steps I no longer get an error and the venv is created automatically when it does not exist, and activated when it does:

4. `direnv allow`
5. `direnv: loading .envrc`
   ` Creating a virtualenv for this project…`
    `...`
    `direnv: export +PIPENV_ACTIVE +VIRTUAL_ENV ~PATH`
