### ISSUE TITLE
All screencasts on screencasts page have been archived

### ISSUE THREAD

**Issue by kbd** [direnv/direnv#507]
Every screencast linked on https://direnv.net/#/docs/screencasts is unavailable, with the text:

> This recording has been archived
> All unclaimed recordings (the ones not linked to any user account) are automatically archived 7 days after upload.

**Comment by zimbatm** [comment]
Thanks for reporting this!

I remember very well creating the account and having the recording associated to it. Now the recordings are lost and I have to start all over again.

**Comment by zimbatm** [comment]
It looks like I could use the JS player and then keep the archive in the repo for more safety.

https://github.com/asciinema/asciinema-player

**Comment by Profpatsch** [comment]
There is a new website now, which doesn’t mention the screencasts anymore.

**Comment by zimbatm** [comment]
Maybe one day when I have the energy I'll re-create them. Closing for now.
