### ISSUE TITLE
direnv.net is down again (2019-06)

### ISSUE THREAD

**Issue by ssbarnea** [direnv/direnv#508]
It project domain is down [again](https://github.com/direnv/direnv/issues/361).

**Comment by zimbatm** [comment]
Is it still not working for you?

https://www.githubstatus.com/ doesn't have mentions on github pages issues.

**Comment by ssbarnea** [comment]
It happened again and I am sure it was a DNS related issue not website. For some reason the direnv.net DNS stops responding and causing this. Initially I believed that it was my local DNS messed but after investigating it started to work without any changes. I had not encountered the same issue with other sites. See
```
$ nslookup direnv.net                                                                                                                                                     [13:24:16]
;; Got SERVFAIL reply from 2a02:8010:61a9:33::1, trying next server
Server:		192.168.33.1
Address:	192.168.33.1#53

** server can't find direnv.net: SERVFAIL

$ nslookup direnv.net                                                                                                                                                     [13:28:26]
Server:		2a02:8010:61a9:33::1
Address:	2a02:8010:61a9:33::1#53

Non-authoritative answer:
Name:	direnv.net
Address: 185.199.111.153
Name:	direnv.net
Address: 185.199.108.153
Name:	direnv.net
Address: 185.199.109.153
Name:	direnv.net
Address: 185.199.110.153
```
The only difference was 4 minutes in between. I found that by random chance as the tab remained opened since I found the issue first time.

**Comment by Profpatsch** [comment]
It has always been up when I tried to reach it.

**Comment by zimbatm** [comment]
I think /etc/resolv.conf has two entries. When it's using the LAN DNS resolver on `192.168.33.1` it fails. When it's using the other DNS it's working. I don't think there is much I can do about this.
