### ISSUE TITLE
Q: umask

### ISSUE THREAD

**Issue by yermulnik** [direnv/direnv#509]
Is there any workaround to set `umask` via `.envrc`?

**Comment by zimbatm** [comment]
can you describe your use-case a bit more?

the `.envrc` file is just a bash script so you should be able to invoke `umask 0022` at the top of the `.envrc` for example. Or put it in the `~/.config/direnv/direnvrc` if you want the mask to apply to all the .envrc files.

**Comment by yermulnik** [comment]
```
> direnv version
2.20.1
> umask
0077
> echo umask 0022 > .envrc
direnv: error .envrc is blocked. Run `direnv allow` to approve its content.
> direnv allow
direnv: loading .envrc
> cd ..
direnv: unloading
> cd -
/tmp/qqq
direnv: loading .envrc
> umask
0077
> cat .envrc
umask 0022
```
There might be something im my bash profile that interferes with `direnv` but to be honest I cannot figure out whet exactly =(

**Comment by zimbatm** [comment]
Ok I see now. I assumed that you wanted the `umask` to apply in the `.envrc` execution context.

direnv only deals with environment variables. the `.envrc` is loaded in a bash sub-shell and then the diff is re-exported to your current shell. This is to allow support for many types of shells.

**Comment by yermulnik** [comment]
Yep, I know. Just was thinking there might be some workaround. Thanks.

**Comment by zimbatm** [comment]
you could add something like this in your `.bashrc`:

```sh
set_umask() {
  if [[ $UMASK ]]; then umask "$UMASK"; else umask 0022; fi
}

eval "$(direnv hook bash)"
export PROMPT_COMMAND=$PROMPT_COMMAND;set_umask
```
assuming that 0022 is the default umask and you can export UMASK in the .envrc.

**Comment by yermulnik** [comment]
> assuming that 0022 is the default umask

this is the main culprit for me =) thanks for the great tool and a will to help. appreciate it.

**Comment by laggardkernel** [comment]
Wrote a zsh version based zimbatm's code, improvement is made for macOS, where the default umask value is `077`.

https://gist.github.com/laggardkernel/38566f4473068c065f1a1ef15e6e1b4a
