### ISSUE TITLE
direnv.net docs rendering broken

### ISSUE THREAD

**Issue by glensc** [direnv/direnv#516]
The content is rendered as raw markdown instead of html:

1. visit https://direnv.net/
2. follow links:
- https://direnv.net/docs/hook.md
- https://direnv.net/docs/installation.md

![image](https://user-images.githubusercontent.com/199095/64120904-1d383980-cda6-11e9-840f-bbbb50ae0c22.png)

**Comment by zimbatm** [comment]
Where did you get these links from?

If you drop the .md extension you will get the rendered version. Eg: https://direnv.net/docs/hook

**Comment by zimbatm** [comment]
nevermind, on the homepage...

**Comment by zimbatm** [comment]
thanks, fixed!
