### ISSUE TITLE
`source_up` doesn't look in the current directory, whereas `find_up` does

### ISSUE THREAD

**Issue by evhan** [direnv/direnv#517]
**Describe the bug**
The behaviour of `source_up` and `find_up` differ in that `source_up` starts its search in the parent directory, whereas `find_up` looks in the current working directory first. Is this intended? By my reading of `man direnv-stdlib` this is a bug, particularly given this:

> source_up [filename]: Loads another ".envrc" if found with the find_up command.

**To Reproduce**
``` bash
cd /tmp
echo echo hello from baz > baz
find_up baz # => result 0, finds baz
source_up baz # => result 1, doesn't find baz, no file sourced, no message printed
```

**Expected behavior**
Given any argument, if `find_up` finds a file, `source_up` should find (and source) it too.

**Environment**
 - OS: Ubuntu 18.04
 - Shell: bash
 - Direnv version: 2.20.1

**Additional context**
Happy to be corrected about the intended behaviour (although I think the current one is confusing) and in that case the man page should probably be changed.

**Comment by zimbatm** [comment]
This is probably an issue with the documentation.

The default case for `source_up` is to look for an `.envrc` file. But if it looks in the current directory it will recurse.

**Comment by evhan** [comment]
Ah, true enough. I've updated the PR #518 to fix the documentation instead.

Would you be interested in another patch that makes it look in the current directory but avoids looping? I don't know how involved this would be; if `direnv` already keeps track of sourced files it may not be too hard.

**Comment by zimbatm** [comment]
I'm not sure. I don't want to break the `source_up` backward-compatibility and it's hard to know if people now rely on that behaviour or not.

In what scenario you don't know what other files are in the current directory? Otherwise you could use `source_env myotherfile`.

**Comment by evhan** [comment]
Yeah, it doesn't really add the ability to do anything you can't already do, it would just be for consistency. But it's probably best to leave it. Anyway, thanks for looking!
