### ISSUE TITLE
README: "states wront path export statement

### ISSUE THREAD

**Issue by casaper** [direnv/direnv#522]
In [The stdlib](https://github.com/direnv/direnv/blob/master/README.md#the-stdlib) second paragraph the readme states:

```sh
export $PATH=$PWD/bin:$PATH
```

Which will be a typo. AFAIS at least :wink:

```sh
export PATH="$PWD/bin:$PATH"
```

Nothing grave, since you actually suggest using the helper `PATH_add`. But still, it's a typo.

**Comment by zimbatm** [comment]
nice catch, thanks :)
