### ISSUE TITLE
Direnv with use node and use_nvm example for fish - is it necessary?

### ISSUE THREAD

**Issue by thernstig** [direnv/direnv#531]
Regarding https://github.com/direnv/direnv/wiki/Node#using-nvm-with-automatic-discovery

I have no idea why this version is needed? All I needed to do after installing fish-nvm was to set this:

```fish
set -gx NODE_VERSIONS ~/.config/nvm
set -gx NODE_VERSION_PREFIX ''
```

And in a project dir:

```sh
~/code/test> cat .nvmrc
12.13.0
~/code/test> cat .envrc
use node
```

And then everything works.

**Comment by zimbatm** [comment]
no idea, sorry. Hopefully a fish user will chime in.

**Comment by thernstig** [comment]
I am closing this, as I believe I can explain this myself. That version in the link lets you use both nvm.sh (for bash shells) and nvm.fish (for fish shells) with the same `nvm use` command. Also, when it uses nvm.sh, it calls `nvm use` which is superior to just updating the environment variables.

However, nvm.fish has recently been updated to 2.0, and the current implementations explained at https://github.com/direnv/direnv/wiki/Node for nvm.fish is outdated. I might try to create a new issue to fix this.
