### ISSUE TITLE
Could "layout python-venv" be made available by default?

### ISSUE THREAD

**Issue by nottrobin** [direnv/direnv#537]
I'm not sure why  we need to create the `layout_python-venv` bash function ourselves (as per https://github.com/direnv/direnv/wiki/Python).

Would it be possible to provide `layout python-venv` by default? As it's probably superior to `layout python` for modern use-cases.

**Comment by tlgs** [comment]
Agreed, since `venv` is part of the Python Standard Library I think it makes a lot of for it to be supported natively.

I would even argue that `layout python` should use it instead of `virtualenv` but I understand Python's environment management is VERY messy and that a lot of solutions rely on older approaches...

**Comment by zimbatm** [comment]
I try to keep direnv as backward-compatible as possible. If you can make that change without breaking existing users then why not. This should include users who used and old installation of direnv and upgraded.

**Comment by tlgs** [comment]
It seems `venv` is already being used for `layout python` in the [master branch](https://github.com/direnv/direnv/blob/master/stdlib.sh#L489); it just hasn't made it to release yet. It was added by @eddies.

I don't think it works as the `python-venv` in the community wiki though...

**Comment by zimbatm** [comment]
I am going to cut a release soon so let me know if it needs some fixing

**Comment by NilsIrl** [comment]
From what I understand, on the latest release thanks to #505 `layout python` will use `venv`.

**Comment by NilsIrl** [comment]
So this can be closed I guess
