### ISSUE TITLE
New Conda layout for local environments

### ISSUE THREAD

**Issue by captainmalloc** [direnv/direnv#538]
**Is your feature request related to a problem? Please describe.**
I'd like to have an integrated solution to activate a project-local Conda environment.

**Describe the solution you'd like**
I'd like to include a new layout description in the direnv stdlib:

```
# Usage: layout local_anaconda <path/to/env> <path/to/environment.yml>
#
# Loads a conda virutal environment under "<path/to/env>" .
# If the environement doesn't exist,
# create it using the description in "<path/to/environment.yml>"
#
layout_local_anaconda() {
  local env_path=${PWD}/.condaenv
  if [ -n "$1" ]; then
    env_path=$1
  fi

  if [ -d ${env_path} ]; then
    source activate ${env_path}
  else
    local env_parent=$(dirname ${env_path})
    local env_yml=${env_parent}/environment.yml
    if [ -n "$2" ]; then
      env_yml=$2
    fi
    conda env create -p ${env_path} -f ${env_yml}
    source activate ${env_path}
  fi
}
```

**Describe alternatives you've considered**
My current solution is to integrate the proposed layour in '~/.direnvrc'

**Comment by tysonclugg** [comment]
@captainmalloc: This issue should be fixed by https://github.com/direnv/direnv/pull/717 - can you please confirm and close this issue?

**Comment by captainmalloc** [comment]
@tysonclugg I tested the new `layout_anaconda` and it allows creating prefix-based conda environments.

From a personal point of view I would have preferred a more explicit approach to avoid confusion, i.e. `layout anaconda .condaenv` will create a named conda env while `layout anaconda ./.condaenv` will create a prefix based conda env.

For the record, since when I opened this request I slightly changed my approach, I currently do not use the `layout_anaconda` anymore and prefer a more explicit custom approach in my projects, here above a `.envrc` example for a basic Python conda env:
```
local env_path=${PWD}/.condaenv
if [ -d ${env_path} ]; then
    source activate ${env_path}
else
    conda create -y -p ${env_path} python=3.7.1
    source activate ${env_path}
    pip install -r ${PWD}/requirements.txt
fi 
```
This approach let me also avoid creating `environment.yml` thus allowing `venv` compatible environments.

**Comment by tysonclugg** [comment]
> @tysonclugg I tested the new `layout_anaconda` and it allows creating prefix-based conda environments.

Great, thanks for confirming this.

> From a personal point of view I would have preferred a more explicit approach to avoid confusion, i.e. `layout anaconda .condaenv` will create a named conda env while `layout anaconda ./.condaenv` will create a prefix based conda env.

Understood, but the approach I took is exactly the same as `conda activate ...` uses.  At least it's consistent in that regard.

I'm not an admin on this project, can this be closed now?
