### ISSUE TITLE
[Question] get the direnv command starting directory

### ISSUE THREAD

**Issue by divramod** [direnv/direnv#540]
Hey, thx for the awesome project!

I am not sure if my question is at the right place here, but i hope so.

So i wanted to ask, how i can get the name/path of the direnv starting directory.

My usecase:

```
| parent-directory/
  - .envrc
  - child-directory/
```

When i cd into /parent-directory/child-directory, the /parent-directory/.envrc is called.
Now my question: how can i get the path/name of the child-directory from where direnv allow was called.
I like to use the name/path of the child-directory to be able to load things depending on the directory name to avoid having a .envrc for every child-directory i use.

Thx again for the work on the project!

**Comment by zimbatm** [comment]
the current design requires you to add a `.envrc` per folder that needs a different context. When the `.envrc` is loaded, `$PWD` gets changed to the folder where the `.envrc` resides (so always `parent-directory` in your case).
