### ISSUE TITLE
direnv can not find python

### ISSUE THREAD

**Issue by flip111** [direnv/direnv#547]
i'm on ubuntu 16.04. Before i had direnv 2.7 but since it's a bit old i installed 2.20 instead. Both versions can not find python with the following message:

```
direnv: loading .envrc                                                                                                                                                   
/bin/bash: /usr/local/bin/virtualenv: /usr/bin/python3.6: bad interpreter: No such file or directory
direnv: export +VIRTUAL_ENV ~PATH
```

On ubuntu 16.04 python3.5 is the latest python version. I had python3.6 previously installed from this ppa https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa I uninstalled python3.6 now and installed python3.8. How can i make direnv find python3.8 instead?

**Comment by zimbatm** [comment]
That's not really a problem with direnv but with your setup. I assume that 
/usr/local/bin/virtualenv has its shebang hard-coded to /usr/bin/python3.6 or that the virtualenv created by direnv is still referring to the old version of python.

Try re-installing virtualenv and deleting the `.direnv` folder in your project.

**Comment by flip111** [comment]
i removed `/usr/local/bin/virtualenv` since it was a leftover of an old python3.6 installation and then setup venv https://github.com/direnv/direnv/wiki/Python#venv-stdlib-module for python3.8 now everything works smoothly. Thank you for the help
