### ISSUE TITLE
an error message references XDG_RUNTIME_DIR but the value from XDG_DATA_DIR is what is being used

### ISSUE THREAD

**Issue by NorthIsUp** [direnv/direnv#557]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Environment**
 - OS: [e.g. macOS Mojave, Ubuntu 18.04, ...]
 - Shell: [e.g. bash, zsh, ...]
 - Direnv version [e.g. 2.20.0]

**Additional context**

**Comment by zimbatm** [comment]
there is a reason why I added a bug template. Please help me help you
