### ISSUE TITLE
v2.21.0 Missing Binary Release

### ISSUE THREAD

**Issue by osterman** [direnv/direnv#560]
## what

* [v2.21.0 is missing binary release asset](https://github.com/direnv/direnv/releases) on GitHub

## why
* 99% of people will not download and compile a release
* Binary releases are essential for adoption
* We use the [binary releases to package our updates to alpine](https://github.com/cloudposse/packages) =) and this [fails our automatic updates](https://github.com/cloudposse/packages/pull/322)

**Comment by zimbatm** [comment]
Interesting. I didn't know alpine was depending on the binary releases.

I switched the build system to use GitHub actions and need to bring the binary releases back.

**Comment by zimbatm** [comment]
fixed!
