### ISSUE TITLE
PS1 export warning without attempting to change prompt

### ISSUE THREAD

**Issue by kclejeune** [direnv/direnv#570]
On the 2.21.* releases, direnv is giving a warning regarding a variable that I'm not modifying with `.envrc`.  Is there a way to suppress this output if PS1 is not being modified?

**To Reproduce**
- Install direnv on macOS
- make a virtual python environment with
  ```bash
  virtualenv ./venv && echo source venv/bin/activate | tee -a .envrc && direnv allow
  ```

**Expected behavior**
In previous versions, this has worked as expected to load and unload the virtual environment with no other messages.  

**Environment**
 - OS: macOS Catalina
 - Shell: zsh
 - Direnv version 2.21.2 (also happened on 2.21.1)

**Comment by zimbatm** [comment]
I'm pretty sure the culprit is venv/bin/activate which sets the PS1.
If you add `unset PS1` on the next line it should fix the error message.

**Comment by kclejeune** [comment]
That makes sense — I didn’t think about that because running the activation has never actually changed my prompt.  I’ll give it a shot and close this if it works.  Thanks!

**Comment by kclejeune** [comment]
Confirmed, this works.  It might be a good idea to add a note about this in [the documentation](https://github.com/direnv/direnv/wiki/PS1) since that's the link that the error gives as reference for the issue.

**Comment by zimbatm** [comment]
thanks!
