### ISSUE TITLE
Incorrect behavior with the environment variable using the command `echo`

### ISSUE THREAD

**Issue by Yegorov** [direnv/direnv#579]
**Describe the bug**
Environment variables are not loaded using the command `echo`

**To Reproduce**
```bash
$ mkdir ~/my_test_direnv && cd ~/my_test_direnv
$ echo 'export MY_VAR=somevalue' > .envrc
$ direnv allow .

$ cd ..

$ direnv exec ./my_test_direnv ruby -e 'puts ENV["MY_VAR"]'
direnv: loading ~/my_test_direnv/.envrc
somevalue # is ok

$ direnv exec ./my_test_direnv python -c 'import os; print(os.environ["MY_VAR"])'
direnv: loading ~/my_test_direnv/.envrc
somevalue # is ok

$ direnv exec ./my_test_direnv printenv | grep MY_VAR
direnv: loading ~/my_test_direnv/.envrc
MY_VAR=somevalue # is ok

$ direnv exec ./my_test_direnv/ echo $MY_VAR
direnv: loading ~/my_test_direnv/.envrc

# but why?
```

**Expected behavior**
Show env var using command `echo`

**Environment**
 - OS: Ubuntu 18.04
 - Shell: bash
 - Direnv version: 2.21.2

**Comment by zimbatm** [comment]
It should be `direnv exec ./my_test_direnv/ bash -c 'echo $MY_VAR'`. "/bin/echo" doesn't know how to interpolate variables. Most likely the variable gets interpolated by the surrounding shell before invoking direnv even.

**Comment by Yegorov** [comment]
@zimbatm thanks. If I understand correctly, the launch should be in another process.
Ok, but if i'm inside the folder, this working as expected:

```bash
$ cd my_test_direnv/
direnv: loading ~/my_test_direnv/.envrc
direnv: export +MY_VAR
~/my_test_direnv$ echo $MY_VAR
somevalue
~/my_test_direnv$ direnv exec . echo $MY_VAR
direnv: loading ~/my_test_direnv/.envrc
somevalue
```

**Comment by zimbatm** [comment]
It's because the surrounding bash replaces the variable and then invokes `direnv exec . echo somevalue`

**Comment by Yegorov** [comment]
@zimbatm ok, thanks.
