### ISSUE TITLE
With a NFS homedir, direnv climbs path and causes hang.

### ISSUE THREAD

**Issue by bitmagewb** [direnv/direnv#580]
I have an NFS mounted homedir on servers I ssh to.  I'm running into an issue where direnv will hang when I login, displaying the "use CTRL-C to give up" message.  CTRL-C does not fix the hang, leaving the shell unusable and me unable to login.

I logged in forcing a different shell and then ran a strace on direnv.  It appears to be climbing the directory tree looking for a .envrc, eventually reaching the automounter root (/r).  That is causing a hang in autofs on this system.  I can work around this by creating a .envrc in my homedir, but I'm not sure why it is trying all the paths above that dir at all.  I've put the strace below.

newfstatat(AT_FDCWD, "/bin/bash", {st_mode=S_IFREG|0755, st_size=939344, ...}, 0) = 0
newfstatat(AT_FDCWD, "/r/NFSserver/vol/homedirs/users/buser/.envrc", 0xc00008c9f8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/r/NFSserver/vol/homedirs/users/.envrc", 0xc00008cac8, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/r/NFSserver/vol/homedirs/.envrc", 0xc00008cb98, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/r/NFSserver/vol/.envrc", 0xc00008cc68, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/r/NFSserver/.envrc", 0xc00008cd38, 0) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/r/.envrc", direnv: ([direnv export bash]) is taking a while to execute. Use CTRL-C to give up.

**Comment by zimbatm** [comment]
Thanks for this interesting report. Does `/r/.envrc` really exist or is it just a quirk of NFS that pretends that it's there?

**Comment by bitmagewb** [comment]
It does not.  /r is the root directory for the automounter on this system, so it's trying to find/mount a .envrc share there.

On February 4, 2020 6:19:46 AM EST, zimbatm <notifications@github.com> wrote:
>Thanks for this interesting report. Does `/r/.envrc` really exist or is
>it just a quirk of NFS that pretends that it's there?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/direnv/direnv/issues/580#issuecomment-581861974

--Brian

**Comment by zimbatm** [comment]
What do you get when you run `stat /r/.envrc`? I am trying to understand why it doesn't return ENOENT or how I could differentiate that from a normal file.

**Comment by bitmagewb** [comment]
It hangs with no output (which is an issue with the automounter on this system, that shouldn't happen).  But I don't follow why direnv is climbing the tree at all, since it should only be applying things from the .envrc in the current dir?

**Comment by zimbatm** [comment]
It's because you want to be in the same environment when entering sub-folders of a project.

Let's say your project is checked-out under ~/code/myproject and there is an .envrc at the top of "myproject" where you setup the project's build environment. Then if you `cd ~/code/myproject/src/some/sub/folder`, it should still load the `.envrc` under ~/code/myproject.

Potentially I could change the algorithm a bit so that it stops once it reaches either $HOME or / instead of just /. It might break backward-compatibility for other users though, I don't know what everyone is doing with direnv.

**Comment by bitmagewb** [comment]
Thanks, I hadn't considered that.  Maybe as a config file option of stop_at_home or something?  In any case, this is an unusual situation as the automounter shouldn't respond with a hang, and I can work around it with an empty ~/.envrc.  Which basically acts as that config file option anyway, other than the "direnv: loading .envrc" prompt.  Thanks for taking a look at it!

**Comment by zimbatm** [comment]
If you control the system config you might also try to mount something at /r/.envrc using a bind-mount or a tmpfs :)
