### ISSUE TITLE
stdlib uses XDG_CONFIG_DIR instead of XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by ronnyws** [direnv/direnv#595]
**Describe the bug**

The stdlib of direnv uses the environment variable XDG_CONFIG_DIR instead of XDG_CONFIG_HOME to determine the location of the user defined configuration directory.

**To Reproduce**

```bash
% direnv stdlib | grep XDG_CONFIG
direnv_config_dir=${XDG_CONFIG_DIR:-$HOME/.config}/direnv
```

**Expected behavior**

```
% direnv stdlib | grep XDG_CONFIG
direnv_config_dir=${XDG_CONFIG_HOME:-$HOME/.config}/direnv
```

The expected behaviour is that direnv uses XDG_CONFIG_HOME as stipulated by the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

**Environment**
 - OS: macOS Catalina 10.15.3
 - Shell: bash
 - Direnv version 2.21.2

**Additional context**

This issue was introduced by some refactoring in [pull request #488](https://github.com/direnv/direnv/pull/488).

**Comment by zimbatm** [comment]
thanks for the report!
