### ISSUE TITLE
typo when running "direnv version"

### ISSUE THREAD

**Issue by slashfoo** [direnv/direnv#598]
**Describe the bug**
When running "direnv version VERSION_AT_LEAST" where VERSION_AT_LEAST is a newer version, the output has a typo. For example, if ran with a VERSION_AT_LEAST of 2.21.3 and the current version installed is 2.21.2, the output reads:

`direnv: error v2.21.2 it older than the desired v2.21.3`

It should read:

`direnv: error v2.21.2 is older than the desired v2.21.3`

or better yet:

`direnv: error current version v2.21.2 is older than the desired version v2.21.3`

**To Reproduce**
1. Install direnv 2.21.2
2. type "direnv version 2.21.3" in the command prompt and press `enter`

**Expected behavior**
Output without typo.

**Environment**
 - OS: Debian
 - Shell: zsh
 - Direnv version [e.g. 2.20.0]

**Additional context**
N/A

**Comment by zimbatm** [comment]
thanks for the report!
