### ISSUE TITLE
I'm getting similar error `(eval):1: bad pattern: ^[[31mdirenv:` when ever I have `.envrc` file which is not allowed and when ever I run `direnv deny`.

### ISSUE THREAD

**Issue by zimbatm** [direnv/direnv#600]
I'm getting similar error `(eval):1: bad pattern: ^[[31mdirenv:` when ever I have `.envrc` file which is not allowed and when ever I run `direnv deny`.

_Originally posted by @turboMaCk in https://github.com/direnv/direnv/issues/176#issuecomment-588890795_

**Comment by zimbatm** [comment]
Hi, can you paste a screenshot of the interaction so I can have a better understanding of what is going on?

**Comment by turboMaCk** [comment]
Hello @zimbatm,
I've realized I might be using old version of direnv. I've [currently switched my setup to direnv from nixos-unstable](https://github.com/turboMaCk/Dotfiles/commit/861d0d6acbf6e13dabbdb8f356c5872a6cd6451d). I'll report back later if that did/didn't solved the problem.

**Comment by turboMaCk** [comment]
Interestingly this solved the issue for me despite the [existence of this condition](https://github.com/turboMaCk/Dotfiles/commit/861d0d6acbf6e13dabbdb8f356c5872a6cd6451d#diff-addb47fcbbf3184051f779fb97ec006cL10). Anyway problem is resolved for me so I think this issue can be closed.

**Comment by zimbatm** [comment]
alright! not all mysteries are worth uncovering in life :)
