### ISSUE TITLE
Error while trying to add direnv zsh hook

### ISSUE THREAD

**Issue by korrat** [direnv/direnv#608]
**Describe the bug**
When I execute `eval $(direnv hook zsh)`, as noted in the documentation, I get an error:
```shell
$ eval $(direnv hook zsh)
zsh: parse error near `typeset'
```

**To Reproduce**
1. Execute `eval $(direnv hook zsh)`

**Expected behavior**
The direnv hook should be installed, so that I can use direnv in zsh

**Environment**
 - OS: ArchLinux
 - Shell: zsh
 - Direnv version: 2.21.2

**Additional context**
I've found that adding a semicolon before both invocations of `typeset` fixes the issue. It seems that eval disregards the line breaks in the output of `direnv hook zsh`.

**Comment by zimbatm** [comment]
Where did you see it being without the quotes around the value?

It should look like this: `eval "$(direnv hook zsh)"`

**Comment by korrat** [comment]
That was the error. Thanks for clarifying. I should have checked the documentation more carefully.
