### ISSUE TITLE
I think direnv should be changed and only emit that error whenever PS1 is part of the diff.

### ISSUE THREAD

**Issue by zimbatm** [direnv/direnv#618]
I think direnv should be changed and only emit that error whenever PS1 is part of the diff.

Another workaround is to change the zsh profile configuration to only set, not export the PS1.

_Originally posted by @zimbatm in https://github.com/direnv/direnv/issues/408#issuecomment-610387778_

**Comment by nickray** [comment]
Even if PS1 is part of the diff, I feel it's too noisy to emit this warning. For instance, activating Python virtualenvs triggers this warning.
Given it's easy to locate the ticket and the wiki entry on this topic, I would suggest reverting https://github.com/direnv/direnv/pull/483 entirely.
