### ISSUE TITLE
Cannot get latest version: module contains a go.mod file, so module path should be github.com/direnv/direnv/v2

### ISSUE THREAD

**Issue by KateGo520** [direnv/direnv#629]
## Background
The `github.com/direnv/direnv` uses [Go modules](https://github.com/golang/go/wiki/Modules) and the current release version is `v2`. And it’s module path is `"github.com/direnv/direnv"`, instead of `"github.com/direnv/direnv/v2"`. It must comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. Quoting the specification:
> A package that has opted in to modules _must_ include the major version in the import path to import any v2+ modules
> To preserve import compatibility, the go command requires that modules with major version v2 or later use a module path with that major version as the final element. For example, version v2.0.0 of _example.com/m_ must instead use module path _example.com/m/v2_.
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

## Steps to Reproduce
GO111MODULE=on, run `go get` targeting any version >= v2.21.0 of the `direnv/direnv`:
```
$ go get github.com/direnv/direnv@v2.21.2
go: finding github.com/direnv/direnv v2.21.2
go: finding github.com/direnv/direnv v2.21.2
go get github.com/direnv/direnv@v2.21.2: github.com/direnv/direnv@v2.21.2: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```
run `go get github.com/direnv/direnv`, the version will stuck in v2.20.1:
```
$go get github.com/direnv/direnv
go: downloading github.com/direnv/direnv v0.1.154
go: downloading github.com/direnv/direnv v2.20.1+incompatible
go: github.com/direnv/direnv upgrade => v2.20.1+incompatible 
```
SO anyone using Go modules will not be able to easily use any newer version of `direnv/direnv`.

### 1. Kill the go.mod files, rolling back to GOPATH.
This would push them back to not being managed by Go modules (instead of incorrectly using Go modules).
Ensure compatibility for downstream module-aware projects and module-unaware projects projects

### 2. Fix module path to strictly follow SIV rules.
Patch the `go.mod` file to declare the module path as `github.com/direnv/direnv/v2` as [per the specs](https://github.com/golang/go/wiki/Modules#semantic-import-versioning). And adjust all internal imports.
The downstream projects might be negatively affected in their building if they are module-unaware (Go versions older than 1.9.7 and 1.10.3; Or use third-party dependency management tools, such as: Dep, glide,govendor…).

If you don't want to break the above repos. This method can provides better backwards-compatibility.
Release a v2 or higher module through the major subdirectory strategy: Create a new v2 `subdirectory` (github.com/direnv/direnv/v2) and place a new go.mod file in that subdirectory. The `module path` must end with `/v2`. Copy or move the code into the v2 subdirectory. Update `import statements` within the module to also use `/v2` (import "github.com/direnv/direnv/v2/…"). Tag the release with `v2.x.y`.

### 3.  Suggest your downstream module users use hash instead of a version tag.
If the standard rule of go modules conflicts with your development mode. Or not intended to be used as a library and does not make any guarantees about the API. So you can’t comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. 
Regardless, since it's against one of the design choices of Go, it'll be a bit of a hack. Instead of `go get github.com/direnv/direnv@version-tag`, module users need to use this following way to get the `direnv/direnv`:
   (1) Search for the `tag` you want (in browser)
   (2) Get the `commit hash` for the `tag` you want
   (3) Run `go get github.com/direnv/direnv@commit-hash`
   (4) Edit the go.mod file to put a comment about which version you actually used
This will make it difficult for module users to get and upgrade `direnv/direnv`.

## Summary
You can make a choice to fix DM issues by balancing your own development schedules/mode against the affects on the downstream projects.

For this issue, `Solution 2` can maximize your benefits and with minimal impacts to your downstream projects the ecosystem. 

## References
* https://github.com/golang/go/wiki/Modules#semantic-import-versioning
* https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
* https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by zimbatm** [comment]
Thanks for the detailed explanation. Since direnv is mostly a "main" package I am not too worried about external usage. If you want to send a PR that makes the breaking change I would be happy to merge it.
