### ISSUE TITLE
direnv does not work with zsh

### ISSUE THREAD

**Issue by nandub** [direnv/direnv#64]
direnv works great on bash, but it does not work on zsh.

I get the following error:

```
Unknown target shell '/Users/fortiz/.localrc'
```

The .localrc file is where I set the `eval "$(direnv hook $0)"` which is called by `.zshrc`

Mac OS X Lion - zsh 4.3.11 (i386-apple-darwin11.0) or brew zsh 5.0.2

**Comment by miked0004** [comment]
This works for if your default is $SHELL is zsh or bash. However, it fails if you run `bash -l` when your default shell is zsh.
The solution documented in the README is the best. Explicitly reference the shell from the appropriate rc file (bashrc, zshrc, etc...)
