### ISSUE TITLE
More flexibility for reloading environments

### ISSUE THREAD

**Issue by piegamesde** [direnv/direnv#647]
**Is your feature request related to a problem? Please describe.**
I have a rather obscure use case: My environments sometimes do some pretty heavy stuff and thus make use of caching. I'd like to have an option to trigger reloads/rebuilds for certain environments without having to `cd` into every directory where there is a `.envrc`.

**Describe the solution you'd like**
I'm not sure about how I would want to use this feature. I think a `direnv reload [PATH]` or `direnv reload [PATHS…]` would do. But maybe there should be a distinction between *reloading* and *rebuilding* (because if I reload a foreign path, what should happen with the generated environment?).

**Additional context**

I'm using `nix-direnv` and want to rebuild all `shell.nix` that are managed through direnv after a channel upgrade (I usuall don't pin `nixpkgs`).

**Comment by zimbatm** [comment]
You can implement a script using `direnv exec`. Eg:

`reload-all.sh`
```sh
#!/usr/bin/env bash
set -euo pipefail

# get the list of all your projects somehow
for dir in $HOME/code/* ; do
  echo "--- $dir"
  direnv exec "$dir" echo OK
done
```

**Comment by piegamesde** [comment]
I got it to work with this, thank you.

```bash
#!/usr/bin/env bash
set -euo pipefail

for entry in $XDG_DATA_HOME/direnv/allow/*; do
  file=$(cat $entry)
  if [ ! -f $file ]; then
    echo "--- Skipping $entry because $file does not exist. Maybe run ``direnv prune``?"
  else
    hash=$((echo $file;cat $file) | shasum -a 256 | awk '{ print $1 }')
    if [ "$hash" == "$(basename $entry)" ]; then
      dir=$(dirname $file)
      echo "--- Checking $dir …"
      direnv exec "$dir" echo "… OK"
    else
      echo "--- Skipping $entry because the content of $file content has changed. Wait for #494 to be fixed."
    fi
  fi
done
```

It was a lot less ugly before I ran into #494. (Alternatively, a command that lists all allowed folders would be nice as well).

**Comment by zimbatm** [comment]
Glad you found a solution!

For 494, I am not likely to fix it myself but would accept a PR.
