### ISSUE TITLE
Exit code zero even on failure

### ISSUE THREAD

**Issue by piegamesde** [direnv/direnv#648]
**Describe the bug**

I have a `.envrc` that fails building for some reasons (nix build error). However, `direnv` still quits with an exit code of zero, indicating that all went well (which it didn't).

**To Reproduce**

1. Create direnv setup
2. Make that setup fail
3. Run `direnv reload` or `direnv exec "THAT_FOLDER" echo "OK"`

If this does not reproduce it, try creating a `use_nix` environment and put a build failure into the `shell.nix`.

**Expected behavior**

An exit code other than zero would indicate that something failed. Ideally, the value somehow encodes the general type of failure.

**Environment**
 - OS: Arch Linux
 - Shell: Zsh
 - Direnv version 2.21.3

**Additional context**

This is really important when automating things in shell scripts.

**Comment by zimbatm** [comment]
I am not able to reproduce:
```
$ direnv allow test/scenarios/failure/

$ direnv exec test/scenarios/failure echo OK && echo OK
direnv: loading ~/go/src/github.com/direnv/direnv/test/scenarios/failure/.envrc
direnv: error exit status 5
```

**Comment by piegamesde** [comment]
I can reproduce it with `echo OK && false` in the `.envrc`.

Maybe `set -e` or similar is missing when sourcing the `.envrc` (I don't know how this is handled internally)?

**Comment by zimbatm** [comment]
Yes, this has to be explicitly enabled for backward-compatibility reasons. See [strict_env](https://direnv.net/man/direnv.toml.1.html#codestrictenvcode)

**Comment by piegamesde** [comment]
I set `strict_env` and now *all* envrcs fail:

```
direnv: loading ~/.envrc
direnv: error exit status 1
```

The `.envrc` only contains `use_nix`. I use direnv-nix. I tested this on folders that *didn't* fail, but this seems irrelevant, because it doesn't even try to do anything. So, basically `strict_env` turns my original problem into the opposite one :D

**Comment by zimbatm** [comment]
oops :p

I don't have time to debut this right now, let me know if you figure it out.

**Comment by zimbatm** [comment]
One suggestion for you is to add `set -x` at the top of the `.envrc` to trace where it is failing.
