### ISSUE TITLE
"layout pipenv" does nothing

### ISSUE THREAD

**Issue by bferg88** [direnv/direnv#649]
**Describe the bug**
When I enter the directory with the pipenv layout, it does not load.

**To Reproduce**
1) Create a new directory, cd to it.
2) Run `pipenv --python 3.8` to create a new Pipfile and virtual environment.
3) Run `direnv edit .` and add `layout pipenv` to the new .envrc file.
4) Observe that no environment loads.

**Expected behavior**
After adding the pipenv layout, I expect the pipenv environment to load.

**Environment**
 - OS: 20.04 LTS on WSL2
 - Shell: bash
 - Direnv version: 2.21.2

**Additonal context**
I was using this page as a reference:
https://github.com/direnv/direnv/wiki/Python
It doesn't look like any additional stuff is supposed to be added to a ".direnvrc" -- is that correct?

**Comment by zimbatm** [comment]
I don't have time to debug this with you right now. One suggestion is to add `set -x` at the top of the .envrc to try and find out what it does.

**Comment by bferg88** [comment]
This was my fault. I had recently reinstalled this WSL and forgot to add the books back into bash.
