### ISSUE TITLE
Special characters in exported values cause unexpected differences in exported values

### ISSUE THREAD

**Issue by mgrecar** [direnv/direnv#650]
**Describe the bug**
If you need to export a value that contains `$` or `#` characters, you get surprising results

**To Reproduce**
Create and allow an `.envrc` file with the following contents:
```
export envrc_value=datadatadata$extradata#donewithdata
```
Trying to echo that value, via `echo $envrc_value`, gives you `datadatadata#donewithdata`, which is missing the middle section of the string.  Even adding quotes around the value, like:
```
export envrc_value="datadatadata$extradata#donewithdata"
```
Doesn't change the behavior.

**Expected behavior**
I would expect the data value not to be modified from it is in the `.envrc` file

**Environment**
 - OS: Ubuntu 18.04.4 LTS
 - Shell: GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
 - Direnv version: 2.15.0

**Additional context**
I was surprised by this when I tried to store a password, and it wasn't working because it was being mangled coming through direnv.  I could see special characters having unexpected meaning, but it was really surprising that adding quotes around the value didn't help at all.

**Comment by zimbatm** [comment]
The issue is that the .envrc is a bash script, and that bash will evaluate $extradata as if it was a variable. So when it reads `export envrc_value=datadatadata$extradata#donewithdata` it sees `export envrc_value=datadatadata#donewithdata` after the substitution.

To prevent bash from substituting variables, the string must be surrounded by single ticks.

```
export envrc_value='datadatadata$extradata#donewithdata'
```

**Comment by mgrecar** [comment]
Ah, yeah, that's totally correctly.  I forgot it wasn't some magic other world, but just bash.  Wrapping a value that contains a `$` in single quotes lets it pass through unaltered.  Thanks!
