### ISSUE TITLE
"layout pipenv" does not load ".env"

### ISSUE THREAD

**Issue by bferg88** [direnv/direnv#651]
**Describe the bug**
using "layout pipenv" with direnv does not load variables from ".env"

**To Reproduce**
In a directory that uses pipenv, add "layout pipenv" to your ".envrc"

**Expected behavior**
The variables from ".env" should  be loaded into the environment.
I understand that I could just put them into ".envrc", but since this is a shared project, I'm not sure I want to enforce direnv as a dependency for setting up the environment.

**Environment**
 - OS: Ubuntu 20.04 via WSL 2
 - Shell: bash
 - Direnv version: 2.21.2

**Comment by bferg88** [comment]
I found the dotenv command hidden in some docs, so I just need
```
layout pipenv
dotenv
```
in the .envrc, which means I'm all good.

It may be useful to infer "dotenv" when using "layout pipenv" since that's how pipenv works.

**Comment by gretel** [comment]
@bferg88 thanks!
