### ISSUE TITLE
Check for .git/index.lock before reload

### ISSUE THREAD

**Issue by blaggacao** [direnv/direnv#653]
It would be helpful if any reload would be paused during the existence of a `.git/index.lock`.

Though I'm not sure if I'm pointing into the right direction, so here is the problem:

When I do a git rebase and it stops at some point to do a merge resolutions, it might happen so that `direnv` reloads the environment in the middle of such git operation.

This is certainly annoying, and most certainly never intended by the user.
The most annoying point is that is blocks the command line for a couple of seconds.

Can we solve this?

There must be other well known git files that convey state of an ongoing git transaction.

**Comment by zimbatm** [comment]
I see your point. Especially if the merge conflict is on one of the dependencies of the .envrc, the reload might leave the user with a broken environment.

Now if the language version has changed between commits, and direnv brings the compiler/interpreter into the environment, it might be confusing if the code no longer runs. This is sometimes needed to check on top of resolving the merge conflict. So reloading is still necessary in some cases.

If the reload was really quick, this wouldn't be as much of a problem.

Another possibility would be to add a prompt in direnv to ask if the user wants to reload the environment on some checks (like the .git/index.lock)

**Comment by blaggacao** [comment]
> So reloading is still necessary in some cases.

Would it be possible to delay reloading to after those presumed well-known git state files are removed? (Only at the additional condition that a watched file chaged _at some point_ during the process.)

**Comment by blaggacao** [comment]
Actually with things like cached-nix-shell and https://github.com/direnv/direnv/issues/654 fixed, I don't think this is any more desirable: I came to the conclusion that direnv shouldn't care what downstream executables do.

We could imagine a case where somebody explicitly watches a .git lock file and want's to reload something based on that.

with nix flakes, or a kind of preview behaviour of it's caching with cached-nix-shell, downstream executables behave more conveniently for use with direnv.

Since I don't think direnv should do anything about it, I'm closing it.
