### ISSUE TITLE
"not a valid identifier" - direnv 2.21.3

### ISSUE THREAD

**Issue by blaggacao** [direnv/direnv#654]
<details>
<summary><code>.envrsc</code></summary>

Note that in reality `rm -rf "$temp_dir"` in `direnv_load` was commented to analyze the temporary script file

Using this cached shell approach: https://github.com/xzfc/cached-nix-shell

```shell
if command -v cached-nix-shell &> /dev/null; then
  direnv_load cached-nix-shell --run "$(join_args "$direnv" dump)"
else
  use nix
fi

```

</details>

<details>
<summary>in shell</summary>

`[...]` not in original output.

```console
/tmp/direnv.rBtT6L/script: line 1: export: `








HOST_PATH=/nix/store/qfh1cvn123nlnmyfhc14902a4yz9aqzy-python3-3.8.3-env/bin[...]': not a valid identifier
```

</details>

<details>
<summary>in <code>/tmp/direnv.rBtT6L/script</code></summary>

`[...]` not in original output.

```console
[...]export $'NIX_CC_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu'=1;export $'\n\n\n\n\n\n\n\n\nHOST_PATH'=$'/nix/sto[...]
```

</details>

**Comment by zimbatm** [comment]
It's a little bit hard to identify the problem without a reproducible step. What happens if you replace the `.envrc` with just `use_nix`?

**Comment by blaggacao** [comment]
Oh sorry! I tacitly assumed something: it's going down the `cached-nix-shell` path. Sorry.

`use nix` works as expected without any error.

I can procide the whole default.nix + shell.nix  where this is happening. Shall I?

**Comment by zimbatm** [comment]
I would advise you to report the issue to https://github.com/xzfc/cached-nix-shell in that case. It doesn't scale if I have to debug all the third-party code.

**Comment by blaggacao** [comment]
Ref: https://github.com/xzfc/cached-nix-shell/issues/17

**Comment by blaggacao** [comment]
will be fixed in cached-nix-shell
