### ISSUE TITLE
Nix shellHook using trap with EXIT signal is invoked during loading of environment

### ISSUE THREAD

**Issue by dejanr** [direnv/direnv#657]
**Describe the bug**
Currently it is not possible to use trap within the nix shellHook, as it is called during the loading of environment, instead when environment is unloaded.

I have created reproducible example here:

https://github.com/dejanr/direnv-trap-EXIT

**To Reproduce**
Create shell.nix and shellHook with trap hook for EXIT signal

```nixpkgs
  shellHook = ''
    trap "echo trap called?" EXIT
  '';
```
Given that direnv is allowed, when entering the directory, trap hook is called:
```
direnv: loading projectdir/.envrc
trap called?
direnv: export +AR +AS +CC +CONFIG_SHELL +CXX +HOST_PATH +IN_NIX_SHELL +LD +NIX_BINTOOLS +NIX_BINTOOLS_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_BUILD_CORES +NIX_BUILD_TOP +NIX_CC +NIX_CC_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_ENFORCE_NO_NATIVE +NIX_HARDENING_ENABLE +NIX_INDENT_MAKE +NIX_LDFLAGS +NIX_STORE +NM +OBJCOPY +OBJDUMP +RANLIB +READELF +SIZE +SOURCE_DATE_EPOCH +STRINGS +STRIP +TEMP +TEMPDIR +TMP +TMPDIR +buildInputs +builder +configureFlags +depsBuildBuild +depsBuildBuildPropagated +depsBuildTarget +depsBuildTargetPropagated +depsHostHost +depsHostHostPropagated +depsTargetTarget +depsTargetTargetPropagated +doCheck +doInstallCheck +name +nativeBuildInputs +nobuildPhase +out +outputs +patches +phases +propagatedBuildInputs +propagatedNativeBuildInputs +shell +shellHook +stdenv +strictDeps +system ~PATH
```

**Expected behavior**
Trap hook should be called only once we unload direnv environment, not when we load the direnv environment

```
$ cd projectdir
direnv: loading projectdir/.envrc
direnv: export +AR +AS +CC +CONFIG_SHELL +CXX +HOST_PATH +IN_NIX_SHELL +LD +NIX_BINTOOLS +NIX_BINTOOLS_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_BUILD_CORES +NIX_BUILD_TOP +NIX_CC +NIX_CC_WRAPPER_TARGET_HOST_x86_64_unknown_linux_gnu +NIX_ENFORCE_NO_NATIVE +NIX_HARDENING_ENABLE +NIX_INDENT_MAKE +NIX_LDFLAGS +NIX_STORE +NM +OBJCOPY +OBJDUMP +RANLIB +READELF +SIZE +SOURCE_DATE_EPOCH +STRINGS +STRIP +TEMP +TEMPDIR +TMP +TMPDIR +buildInputs +builder +configureFlags +depsBuildBuild +depsBuildBuildPropagated +depsBuildTarget +depsBuildTargetPropagated +depsHostHost +depsHostHostPropagated +depsTargetTarget +depsTargetTargetPropagated +doCheck +doInstallCheck +name +nativeBuildInputs +nobuildPhase +out +outputs +patches +phases +propagatedBuildInputs +propagatedNativeBuildInputs +shell +shellHook +stdenv +strictDeps +system ~PATH
$ exit
exit
trap called?
```

**Environment**
 - OS: NixOS
 - Shell: zsh/bash
 - Direnv version 2.21.2

**Additional context**
By using plain nix-shell, trap hook works as expected. Its only called once we exit the nix-shell

**Comment by zimbatm** [comment]
yup, that's by design. Note that the .envrc is loaded in a fresh bash process and direnv handles the translation between the host shell and that .envrc. See also https://github.com/direnv/direnv/issues/73 for more context.

**Comment by dejanr** [comment]
@zimbatm is it possible for use_nix to do a cleanup somehow differently? or i have to implement a custom direnv hook inside .envrc for this use case?

**Comment by zimbatm** [comment]
I don't know. What kind of cleanup do you have in mind?

**Comment by dejanr** [comment]
Usually with nix shell i start few background jobs, and with trap signaling i kill those when nix shell is exited.

**Comment by zimbatm** [comment]
I see. One issue with direnv is that you can have many shells loaded so the logic would be more complicated. Direnv doesn't have a long-running process to manage those sub-processes.

Usually, the solution is to start a second shell which tracks those services.

**Comment by dejanr** [comment]
Thanks for answering, i will close this, as it's not a bug

**Comment by TheColorman** [comment]
> Usually, the solution is to start a second shell which tracks those services.

Sorry to necropost, but how would this be achieved? I have the exact same use case - I want to start a Docker container when the shell is activated (checks are in place to see if it is running) and kill it upon exit.
