### ISSUE TITLE
direnv is not reentrant

### ISSUE THREAD

**Issue by layus** [direnv/direnv#658]
**Describe the bug**
I have a nix shell hook that contains `exec zsh`. When I configure direnv to `use nix`, it keeps running direnv and zsh forever, as each new zsh shell starts a new direnv instance, and conversely. 

**To Reproduce**
add `exec $SOME_SHELL` to your nix `shellHook`.

**Expected behavior**
A fix to prevent self-execution, or a documentation warning about executing sub shells.

**Environment**
 - OS: NixOS
 - Shell: zsh
 - Direnv version 2.21.3

**Additional context**
N/A

**Comment by layus** [comment]
Hmmmm. Of course, just dropping `exec zsh` works flawlessly, because then I remain in my original zsh shell thanks to direnv :-D

That's what you get for mixing direnv style and hacky style :-).

**Comment by zimbatm** [comment]
If you want to keep both modes, you can detect if the script is being executed inside of direnv and switch like this:
```sh
if [[ -z "${DIRENV_IN_ENVRC:-}" ]]; then
  exec zsh
fi
```

**Comment by layus** [comment]
Good to know. Thanks !
