### ISSUE TITLE
Local variables, relative to direnv top directory

### ISSUE THREAD

**Issue by aklsh** [direnv/direnv#672]
**Is your feature request related to a problem? Please describe.**
I'm not sure if I read the docs wrong, but I believe `$DIRENV_DIR` contains the top directory for the current direnv. So, declaring environment variables as `export VAR1=$DIRENV_DIR/dir1/executable1` will point to the executable `executable1` in directory `dir1`, which is present at the root of the direnv.

So, even if I move the whole direnv project to another location, the `$DIRENV_DIR` would automatically change and the variables would adjust to point to correct place.

However, if I put `export VAR1=$DIRENV_DIR/dir1/executable1` in .envrc and load it, and ask `which executable1`, I get `execeutable1 not found`.

**Describe the solution you'd like**
Environment variables and other aliases, functions etc. to have values relative to the root of the `direnv` project.

**Describe alternatives you've considered**
Right now, I hardcode the absolute path to the executable, and every time I move the project to a different location, I have to manually change the variables.

**Additional Context**
One more thing I noticed was this:
```shell
echo $DIRENV_DIR
-/home/...<path to direnv project>
```
instead of
```shell
echo $DIRENV_DIR
/home/...<path to direnv project>
```
There's an extra `-` in the beginning - I believe this might be a bug, and this prevents the above problem from being solved.

**Comment by zimbatm** [comment]
`$PWD` in the context of the `.envrc` points to the folder that contains that file. `$DIRENV_DIR` is only meant to be used by direnv itself. I had to add `-` in front of it because zsh.

**Comment by aklsh** [comment]
Oh! Thanks a lot! So using `export var1=$PWD/bin` would solve my problem then...

I'll close the issue

**Comment by NikosAlexandris** [comment]
I have a somewhat similar concern. I want to define `export BIB=resources/references.bib`, `resources` being a sub-directory to the "root" directory where the `.envrc` file exists. `BIB` can be then used by [scholarref](https://adamsgaard.dk/scholarref.html) inside [nvim](https://neovim.io/), i.e.:

> The scholarref program ..  If called with the -a option, the reference is directly inserted into the system bibliography. The full path to the bibliography file (.bib) is assumed to be set in the $BIB environment variable, ..
> 
> ```
> $ echo $BIB
> /home/ad/articles/own/BIBnew.bib
> $ scholarref -a 'damsgaard egholm ice flow dynamics'
> Citation Damsgaard2016 added to /home/ad/articles/own/BIBnew.bib
> ```

However, if I am not editing a file from within the project's "root" directory, then obviously `scholarref -a` won't work as it cannot find the file in question. Hence, I am looking for a way to define the _project directory_. I know now that $DIRENV_ENV won't work. Is there really no way to "save" the root directory in a variable which can then be re-used?

**Comment by NikosAlexandris** [comment]
Indeed, using the `$PWD` answers my question too. Example:
```
export BIB="${PWD}/resources/references.bib"
```
