### ISSUE TITLE
layout go and strict_env results in a failure and doesn't set GOPATH

### ISSUE THREAD

**Issue by offbyone** [direnv/direnv#675]
**Describe the bug**
When loading an `.envrc` with `strict_env = true` and `layout go` the `GOPATH` is not set and bash shows an error:

```
> direnv allow
direnv: loading ~/projects/gmailfilters/.envrc
/bin/bash:353: !1: unbound variable
direnv: export +IFS
```

**To Reproduce**
1. Set `strict_env = true` in `~/.config/direnv/direnv.toml`
2. Create an `.envrc` with `layout go`
3. `direnv allow`

**Expected behavior**

When I unset `strict_env`: 

```
❯ direnv allow
direnv: loading ~/projects/gmailfilters/.envrc
direnv: loading ~/projects/.envrc
direnv: export +GOPATH +PROJECT_MARKER_FILE ~PATH
```

**Environment**
 - OS: macOS Catalina
 - Shell: fish
 - Direnv version 2.20.0

**Additional context**

**Comment by zimbatm** [comment]
Hi, can you try #676?

**Comment by offbyone** [comment]
Took me a few minutes to figure out how to build and use direnv in place of the Homebrew one, but I got there. Yeah, that works!

**Comment by zimbatm** [comment]
thanks
