### ISSUE TITLE
PATH in direnv exec

### ISSUE THREAD

**Issue by fredrikekre** [direnv/direnv#692]
I am trying to use `direnv` in VSCode, specifically for the Julia plugin to specify Julia versions using https://github.com/direnv/direnv/pull/666. For the Julia plugin there is a setting for the executable path to Julia, so I am writing a wrapper script that uses `direnv exec` to set up the correct `PATH` and then `exec julia`, and use this wrappers script as the "Julia executable". Here is a working version of that:

```bash
#!/bin/bash

export PATH=$PATH
exec direnv exec "$PWD" julia "$@"
```

This seem to work, except that I cannot understand why I need to explicitly `export PATH` here and I am trying to understand this,  hence this "issue".

Without the explicit export I get:
```
direnv: error can't find bash: "exec: \"bash\": executable file not found in $PATH"
```
so this tells me that (i) `PATH` must be "reasonable" on `exec direnv` since otherwise `direnv` would not be found and (ii) that `PATH` is messed up inside `direnv` since `/bin/bash` is not found. Indeed, adding some debugging statements to the script and to direnv; here is `PATH` on the line before `exec direnv` in the script above:
```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

but dumping `PATH` from inside `direnv` (printed it from here: https://github.com/direnv/direnv/blob/fa60ed09b21bac5dbc27f7afdeaa921c5bbc166c/config.go#L145) I see that it is completely empty.

Explicitly setting `export DIRENV_BASH=/bin/bash` just pushes the error further down since other utilities are not found, e.g.
```
/bin/bash:233: dirname: No such file or directory
/bin/bash:234: basename: No such file or directory
```

I can not really replicate this behavior from outside VSCode, but something like this results in the same errors:
```bash
#!/bin/bash

export DIRENV_BASH=/bin/bash
export PATH=""
exec direnv exec "$PWD" julia "$@"
```

What am I missing here? Why wouldn't `PATH` be inherited by the `exec`d `direnv` process?

**Comment by fredrikekre** [comment]
(I am not claiming this is a bug, I am just trying to understand how it behaves after scratching my head for far too long)

**Comment by zimbatm** [comment]
Do you mind trying https://github.com/direnv/direnv/pull/693 to see if it fixes your problem?

**Comment by zimbatm** [comment]
For the PATH issue, I don't know. It's possible that the target shell only sets PATH as a local variable, which would be a bug on their side.

**Comment by fredrikekre** [comment]
> Do you mind trying #693 to see if it fixes your problem?

That fixes it in the shell when I explicitly `unset PATH` but still something is strange in VSCode;
```
direnv: error command 'julia' not found on PATH
```
so not sure why that happens. This should be after direnv has set up the the julia path.

> For the PATH issue, I don't know. It's possible that the target shell only sets PATH as a local variable, which would be a bug on their side.

Yea, some further investigation seems to indicate that PATH is not exported as one might expect (see https://github.com/julia-vscode/julia-vscode/issues/1704) so I think I will just stick to adding `export PATH=$PATH` which seems like the easiest solution.

**Comment by fredrikekre** [comment]
With your branch, I inspect `newEnv["PATH"]` here https://github.com/direnv/direnv/blob/2577856416e69ec3e77febf073dc398c94616eb0/cmd_exec.go#L62 but the variable is still empty... Is there something funky going on when direnv's subshell laucnhes without PATH set or something? It seems like the variable is `export`ed properly in the subshell at least: https://github.com/direnv/direnv/blob/2577856416e69ec3e77febf073dc398c94616eb0/stdlib.sh#L397 but this does not seem to propagate back.

**Comment by fredrikekre** [comment]
I can't find a MWE without using VSCode. This example should replicate it exactly (at least it has all the same values of PATH etc that I can observe):

Dummy path to add:
```bash
$ cat .envrc
PATH_add $PWD/bin
```
with a simple exe on this added path:
```bash
$ cat bin/exe-on-path 
#!/bin/bash
echo "Hello from executable found on new PATH"
echo "PATH in exe-on-path"
echo "PATH=$(declare -p PATH)"
```

Wrapper script to run `direnv exec`:
```bash
$ cat wrapper 
#!/bin/bash
echo "PATH in wrapper script:"
echo "PATH=$(declare -p PATH)"
/home/fredrik/dev/direnv/direnv exec "$PWD" exe-on-path
```

This works in my regular shell:
```bash
$ ./wrapper 
PATH in wrapper script:
PATH=declare -x PATH="/home/fredrik/bin:/home/fredrik/.local/bin:/home/fredrik/bin:/home/fredrik/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
direnv: loading ~/dev/direnv/.envrc
Hello from executable found on new PATH
PATH in exe-on-path
PATH=declare -x PATH="/home/fredrik/dev/direnv/bin:/home/fredrik/bin:/home/fredrik/.local/bin:/home/fredrik/bin:/home/fredrik/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin"
```

To mimic the variables I see when the script is ran by VSCode:
```bash
$ unset PATH

$ ./wrapper 
PATH in wrapper script:
PATH=declare -- PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
direnv: error can't find bash: "exec: \"bash\": executable file not found in $PATH"

$ export DIRENV_BASH=/bin/bash

$ ./wrapper                                                       
PATH in wrapper script:
PATH=declare -- PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
direnv: loading ~/dev/direnv/.envrc
Hello from executable found on new PATH
PATH in exe-on-path
PATH=declare -x PATH="/home/fredrik/dev/direnv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
```

This is the same as I observe in VSCode (in particular the `PATH` with missing `-x`. The difference is that from VSCode `exe-on-path` is not found.

**Comment by zimbatm** [comment]
Nice debugging. By the way, you can use `PATH_add bin` and direnv will automatically expand the `bin` to its full location.

I need to read your messages a bit more carefully to provide more ideas.

**Comment by zimbatm** [comment]
> I will just stick to adding export PATH=$PATH which seems like the easiest solution.

Just `export PATH` is enough to transform a local variable to an environment variable.

**Comment by fredrikekre** [comment]
Yea, not sure it is very coherent, just putting down my debugging notes. I will try some more but my needs are essentially satisfied with making sure `direnv` and `bash` are in `PATH` in my wrapper script so not sure it is worth spending too much time on.

**Comment by zimbatm** [comment]
Okay. I think that the issue lies in the VSCode and Julia LS side. It helped find the direnv dependency on coreutils so that's good.

**Comment by zimbatm** [comment]
Maybe direnv also has some assumption that the PATH environment variable exists so I will have to check that.

**Comment by fredrikekre** [comment]
Arrghhhhh. Finally figured out the problem -- VSCode spawns the script with different `$PWD` on different times... so
```
exec direnv exec "$PWD" julia "$@"
```
didn't actually find an `.envrc` file... I will have to figure out a different way to find the correct `.envrc` file I think.

I will close this, don't think there is anything wrong in `direnv`, but thanks for #693!
