### ISSUE TITLE
Support for additional/alternative .envrc filenames?

### ISSUE THREAD

**Issue by pwaller** [direnv/direnv#70]
It would be useful if it could be made to automatically pick up a `bin/activate` in any directory below `$PWD`.

**Comment by imomaliev** [comment]
Is there a way to do this in current versions? Something like AUTOENV_ENV_FILENAME in autoenv? I have existing project structures where I store env variables and other bash functions in .dotfiles/.bashrc file in project folder.

**Comment by zimbatm** [comment]
It wouldn't be too hard to expand the direnv config to pass additional places to look for. The stdlib would also have to be extended a bit to remove the `.envrc` assumptions about the file to look for.

**Comment by imomaliev** [comment]
@zimbatm You mean this is going to be implemented in direnv or I could do that with existing customisation?

**Comment by zimbatm** [comment]
I don't have any plans on implementing this right now. If you're up to it, I am happy to accept a PR.

**Comment by offero** [comment]
I use dotenv `.env` file and it would be great if direnv would pick it up also.
