### ISSUE TITLE
Error message after every shell command in a directory

### ISSUE THREAD

**Issue by tokudan** [direnv/direnv#704]
**Describe the bug**
Since upgrading to NixOS 20.09, I get errors when accessing my sshfs automounter:
`direnv: error open /home/X/sshfs/.envrc: no such device or address`
On NixOS 20.03 this error was silent, but probably still there, as the automounter should never find a server named .envrc and even if - it would be a directory.

**To Reproduce**
1. Setup an automounter using sshfs using these commands:
```
mkdir -p $HOME/sshfs
/nix/store/9plmiqxl4b2vymhy2vli45fi1ch1184v-afuse-0.4.1/bin/afuse -o mount_template='/nix/store/p7a05h86qpn49495qg91v9qw0gnk1yvp-sshfs-fuse-3.7.0/bin/sshfs %r:/ %m' -o unmount_template='fusermount -u -z %m' $HOME/sshfs
```
2. Access $HOME/sshfs or any subdirectory like $HOME/sshfs/myserver/tmp and watch the errors on every execution of direnv.

**Expected behavior**
No errors showing up for files that do not exist.

**Environment**
 - OS: NixOS 20.09.1486.5596cbfb9e9 (Nightingale)
 - Shell: /nix/store/xadrr3l5jvkkm3g3lb2g81j5wz51zqdv-bash-interactive-4.4-p23/bin/bash
 - Direnv: /nix/store/hvz0jnr3iyxi86yv2d8s8yzblpddc064-direnv-2.22.0/bin/direnv

**Comment by zimbatm** [comment]
The only way I can explain this is that `stat /home/X/sshfs/.envrc` returns info, and that `cat /home/X/sshfs/.envrc` would then fail. Do you mind testing that theory?

**Comment by zimbatm** [comment]
Or try to use that branch: https://github.com/direnv/direnv/pull/new/open-instead-of-stat . `nix-shell --run "go install"` and then `eval "$(~/go/bin/direnv hook bash)"` should do the trick.

**Comment by tokudan** [comment]
Good catch about the stat vs. open:
```
[X@ashe:~/sshfs]$ stat .envrc
  File: .envrc
  Size: 0               Blocks: 0          IO Block: 4096   directory
Device: 47h/71d Inode: 2           Links: 1
Access: (0750/drwxr-x---)  Uid: ( 1000/  X)   Gid: (  100/   users)
Access: 1970-01-01 01:00:00.000000000 +0100
Modify: 1970-01-01 01:00:00.000000000 +0100
Change: 1970-01-01 01:00:00.000000000 +0100
 Birth: -
direnv: error open /home/X/sshfs/.envrc: no such device or address

[X@ashe:~/sshfs]$ cat .envrc
cat: .envrc: No such device or address
direnv: error open /home/X/sshfs/.envrc: no such device or address
```

I tried using the open-instead-of-stat variant and it solves this issue.
```
[X@ashe:~/sshfs]$ "/nix/store/5z20qmk33dh41ky13d080z424rhhy76i-direnv-2.23.1-bin/bin/direnv" export bash

[X@ashe:~/sshfs]$ /run/current-system/sw/bin/direnv export bash
direnv: error open /home/X/sshfs/.envrc: no such device or address
```

**Comment by zimbatm** [comment]
thanks for testing the change!
