### ISSUE TITLE
Nix flake error 'environment:766: use_flake: command not found'

### ISSUE THREAD

**Issue by mudrii** [direnv/direnv#705]
**Describe the bug**
Try to use direnv with nix flackes and I am getting below error

```sh
direnv: loading ~/src/dev-env2/.envrc

direnv: using flake

environment:766: use_flake: command not found
```

**To Reproduce**

```sh
{
  description = "Pytyhon Development playground";
  inputs = {
    stable.url = "github:NixOS/nixpkgs/nixos-20.09";
    unstable.url = "github:NixOS/nixpkgs/nixos-unstable";
  };

  outputs = inputs:
    let
      lib = inputs.stable.lib;
      system = "x86_64-linux";
      pkgs = inputs.unstable.legacyPackages.${system};
      app = pkgs.poetry2nix.mkPoetryApplication {
        projectDir = ./.;
      };
      env = pkgs.poetry2nix.mkPoetryEnv { projectDir = ./.; };
    in {
      devShell."${system}" = pkgs.mkShell {
        buildInputs = with pkgs; [
          env
          poetry
          pulumi-bin
        ];
      };
    };
}
```

**Expected behavior**

```sh
$  poetry 
The program ‘poetry’ is currently not installed. It is provided by
several packages. You can install it by typing one of the following:
  nix-env -iA nixos.poetry
  nix-env -iA nixos.python37Packages.poetry
  nix-env -iA nixos.python38Packages.poetry

$ nix develop
warning: Git tree '/home/mudrii/src/dev-env2' is dirty

$ poetry
Poetry version 1.1.0
```

**Environment**
 - OS: NixOs 20.09 
 - Shell: fish/bash
 - Direnv version 2.22.0

**Additional context**

**Comment by zimbatm** [comment]
What is the content of the `.envrc`? `use_flake` is not part of the stdlib so it should be provided by something else.

**Comment by mudrii** [comment]
content of the .envrc is 

```
use flake
```

**Comment by zimbatm** [comment]
Something has to provide the `use_flake` function. Where did you copy this from?
One implementation is in https://github.com/nix-community/nix-direnv, which has to be installed independently.

**Comment by malteneuss** [comment]
@zimbatm Is that project (https://github.com/nix-community/nix-direnv) now obsolete? `use nix` and `use flake` options seem to be available in regular direnv now https://github.com/nix-community/nix-direnv.

**Comment by zimbatm** [comment]
nix-direnv is not necessary, but caches things a bit better, especially with `use nix`

**Comment by zimbatm** [comment]
@mudrii make sure to upgrade to the latest version of direnv to fix your issue

**Comment by peterbecich** [comment]
Thanks, upgrading from `direnv` 2.25 to 2.30 fixed it for me
