### ISSUE TITLE
direnv: referenced .envrc does not exist while executing direnv allow .

### ISSUE THREAD

**Issue by goostleek** [direnv/direnv#707]
**Describe the bug**

I'm not able to pass the [quick-demo](https://github.com/direnv/direnv#quick-demo). After the `direnv allow .` step I got the following error:
```
direnv: referenced C:\Users\goost\direnv-test\.envrc does not exist
```

**To Reproduce**

* Install latest version by `scoop install direnv`
* Execute the `direnv hook bash | clip` command
* Append the clipboard content to the `~/.bashrc`
* Execute the commands:
```
mkdir direnv-test && pushd direnv-test
echo export FOO=foo > .envrc
direnv allow .
```

**Actual behaviour**
```
direnv: referenced C:\Users\goost\direnv-test\.envrc does not exist
```

**Expected behaviour**
Direnv hook should load the created `.envrc` file from the current directory and execute it.

**Environment**
 - OS: `Windows 10.0.19042 N/A Build 19042`
 - Shell: `bash`
 - Direnv version `2.23.1`

**Additional context**

![image](https://user-images.githubusercontent.com/7780330/98351497-0f6eeb80-201d-11eb-8dc4-cf095ee9be95.png)

**Comment by zimbatm** [comment]
Direnv for Windows is unfortunately in a bad shape and not officially supported. Since I am not using Windows myself it's difficult to really improve things. I would like to support it if somebody was willing to do the work and add a CI.

**Comment by jbmeslin** [comment]
it works with Release v2.23.0 but not with le latest

**Comment by pjos** [comment]
The problem seems to have been introduced in v2.23.1 release of direnv 
https://github.com/direnv/direnv/compare/v2.23.0...v2.23.1

**Comment by pjos** [comment]
This code, introduced in 2.23.1 direnv release, is unable to handle windows paths. 

https://github.com/direnv/direnv/blob/b1f99bef3b809d7f85b6ce7d5c14535717225262/stdlib.sh#L122-L137

**Comment by pjos** [comment]
Go seems to pass native windows path, that has been working until `basename` has been replaced by pure linux bash code as referenced above https://github.com/direnv/direnv/issues/707#issuecomment-734174488.  To modify that part would require a skilld bash wizard. To avoid messing around with the code written purely for linux paths I will publish a PR with simpler fix.

**Comment by goostleek** [comment]
I have just updated to the latest `2.25.0` but it didn't fix the problem. Could you please reopen the issue, @zimbatm?

![image](https://user-images.githubusercontent.com/7780330/101763273-d96ecc80-3ade-11eb-84d1-103a139afea0.png)

**Comment by pjos** [comment]
Seems that the released version still has this bug. Probably make related?  Recompiling 2.25.0 generates a binary with a fix to this issue.  I've noticed that the makefile is unable to generate winodows binary without going via linux 
```
$ rm stdlib.go; make clean; GOOS=windows GOARCH=amd64 make
rm -rf \
        .gopath \
        direnv
cat stdlib.sh | ./script/str2go main StdLib stdlib.sh > stdlib.go
exit status 1
GNUmakefile:67: recipe for target 'stdlib.go' failed
make: *** [stdlib.go] Error 1
```

However, following works fine ....

```
$ rm stdlib.go; make; make clean; GOOS=windows GOARCH=amd64 make
cat stdlib.sh | ./script/str2go main StdLib stdlib.sh > stdlib.go
go build  -o direnv
rm -rf \
        .gopath \
        direnv
go build  -o direnv.exe
```

**Comment by goostleek** [comment]
Thx for the fast response (@pjos) and fix (@zimbatm).

I have tested the latest `2.25.1` release and, unfortunately, the fix does not resolve the issue. What's worse, the version reported by the `direnv version` is (wait for it....) `2.24.0`:

![image](https://user-images.githubusercontent.com/7780330/101905419-b7954880-3bb7-11eb-9b0d-077629c7dadc.png)

So it seems we have 2 issues now.

At first, I thought the version was wrongly updated in the [scoop bucket](https://github.com/ScoopInstaller/Main/blob/master/bucket/direnv.json#L8) but it's not.

When you download the latest `amd64` version directly from the release page (by using the link https://github.com/direnv/direnv/releases/download/v2.25.1/direnv.windows-amd64.exe) then it seems the compiled version is `2.24.0`:

![image](https://user-images.githubusercontent.com/7780330/101906162-d34d1e80-3bb8-11eb-9732-5c694552c330.png)

**Comment by zimbatm** [comment]
Can somebody else repro the issue? The Linux binary reports the right version so I'm not 100% sure what this is about. If the release contains an old version of direnv then it would indeed still have this issue.

**Comment by zimbatm** [comment]
@goostleek It's very likely that the old version is in the PATH.

**Comment by goostleek** [comment]
The `PATH` is not an issue here. I've never had that version (`2.24.0`) installed on this machine. And it started being reported after installing the release.

**Comment by goostleek** [comment]
Both issues (this one and the #731) are gone after update to the latest release (`2.25.2`) 🍾. Thank you @zimbatm and @pjos ✋.
