### ISSUE TITLE
after upgrading from 2.20.1 to 2.23.1, export no longer works when value contains "?"

### ISSUE THREAD

**Issue by macrozone** [direnv/direnv#712]
**Describe the bug*

we have a shell tool that (let's name it `printenv`) prints env vars in the form

```
export XXX='xyz'
export VAR"='abc'

```
etc.

in .envrc we have

```
eval $(printenv)
```

this used to work flawlessly until recently a collegue said that _some_ vars are not exported using this method. I could not reproduce that until i updated direnv to 2.23.1. Now i have the same problem. We identified that questionmarks `?`  (and maybe other chars) in the values will break direnv:

export VAR"='abc?xxx'

**To Reproduce**
1. create a file with this content named 'testenv'

```
export FOO='foo'
export BAR='bar?'
```

2. in the same folder, put an .envrc file with this content: `eval $(cat testenv)`

3. invoke `direnv allow`.

you will see that only one env var is exported (FOO)

**Expected behavior**

both env vars are exported

**Environment**
 - OS: macOS catalina
 - Shell: zsh
 - Direnv version 2.23.1. Bug was not present in older versions (not sure which one breaked)

**Comment by macrozone** [comment]
workaround is to add quotes:

```
eval "$(cat testenv)"
```

**Comment by zimbatm** [comment]
This is likely triggered by the new `shopt -s nullglob` and `shopt -s extglob` that changes the expansion rules of bash.

The core issue is that the sub-command wasn't escaped properly as you noticed. This is a common issue and related to the mental model that people have with Bash.

A command like:
```sh
eval $(echo "export FOO=*")
```
At the evaluation, it will expand to
```console
$ eval export FOO=*
$ echo $FOO
CHANGELOG.md cmd_allow.go cmd_apply_dump.go cmd_current.go cmd_deny.go cmd_dotenv.go cmd_dump.go cmd_edit.go cmd_exec.go cmd_export.go cmd_fetchurl.go cmd_help.go cmd_hook.go cmd_prune.go cmd_reload.go cmd_show_dump.go cmd_status.go cmd_stdlib.go cmd_version.go cmd_watch.go cmd_watch_list.go CNAME commands.go config.go _config.yml const.go default.nix dist docs env_diff.go env_diff_test.go env.go env_test.go file_times.go file_times_test.go GNUmakefile go.mod go.sum gzenv install.sh LICENSE log.go look_path.go main.go man nix rc.go rc_test.go README.md result script shell_bash.go shell_elvish.go shell_fish.go shell.go shell_gzenv.go shell_json.go shell.nix shell_tcsh.go shell_test.go shell_vim.go shell_zsh.go sri stdlib.go stdlib.sh test vendor version.go version.txt xdg
```
you can try this in your shell, if you `echo $FOO`, it will contain the listing of the files of the current directory.

Now compare with:
```console
$ eval "$(echo 'export FOO=*')"
$ echo "$FOO"
*
```

So the right solution was indeed to properly escape.

**Comment by macrozone** [comment]
@zimbatm thank you for your explanation, we will update our envrc. files, thx

**Comment by pwaller** [comment]
I've just filed #1135 to try and argue that to have nullglob in effect in `.envrc` is potentially not the optimal user experience, because it doesn't respect the user's shell configuration and causes the shell to behave differently from the users shell in a surprising and difficult to discover way.
