### ISSUE TITLE
shell-init: error retrieving current directory

### ISSUE THREAD

**Issue by EricCrosson** [direnv/direnv#719]
**Describe the bug**

When direnv is loading a `.envrc` file, it prints these messages and does not load the .envrc file

```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Bad file descriptor
pushd: error retrieving current directory: getcwd: cannot access parent directories: Undefined error: 0
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Undefined error: 0
```

**To Reproduce**

I've simplified my zsh configs down to the following:

.zshrc
``` zsh
eval "$(direnv hook zsh)"
```

.zshenv
``` zsh
path=("/usr/local/bin" $path)  # this is where homebrew installs direnv
export -U PATH
```

~/workspace/.envrc
``` shell
export AWS_PROFILE=development
```

Install direnv 
```shell
$ brew install direnv
```

Then start a new shell and cd into ~/workspace and permit the envrc file to be loaded
```shell
$ cd ~/workspace
$ direnv allow
```

**Expected behavior**

I expect direnv to set AWS_PROFILE with the value `development`, but I see AWS_PROFILE is still unset and there are errors printed to the console, described above.

**Environment**
 - OS: macOS Big Sur, and also macOS 10.15.7
 - Shell: zsh 5.8 (x86_64-apple-darwin20.1.0) from homebrew, and also zsh 5.8 (x86_64-apple-darwin20.0) stock with macOS
 - Direnv version: 2.24.0 from homebrew, and also 2.23.1 (built from source) and 2.23.0 (built from source) and 2.22.0 (built from source)

**Additional context**

I have been using direnv on this same machine for some time, I'm not sure exactly what broke it. I thought at first it was one of my configs but after stripping away all my configs, removing and re-installing direnv, and still running into this issue I fear I'm in above my head. 

I have isolated the messages to be coming from the shell hook, which on my machine is defined as

```zsh
$ direnv hook zsh
_direnv_hook() {
  trap -- '' SIGINT;
  eval "$("/usr/local/bin/direnv" export zsh)";
  trap - SIGINT;
}
typeset -ag precmd_functions;
if [[ -z ${precmd_functions[(r)_direnv_hook]} ]]; then
  precmd_functions=( _direnv_hook ${precmd_functions[@]} )
fi
typeset -ag chpwd_functions;
if [[ -z ${chpwd_functions[(r)_direnv_hook]} ]]; then
  chpwd_functions=( _direnv_hook ${chpwd_functions[@]} )
fi
```

I'm not familiar enough with zsh to know what the hooks are doing, however when I run `direnv export zsh` manually I get no output 🤔 seems like nothing would be `eval`d then

**Comment by EricCrosson** [comment]
Too bad, on an Ubuntu machine that has direnv still working, `direnv export zsh` prints nothing too, so that seems to be a red herring

**Comment by zimbatm** [comment]
`getcwd: cannot access parent directories: Bad file descriptor` is really weird. It might be a Golang regression on the Big Sur kernel as Go does its own syscall mapping.

**Comment by zimbatm** [comment]
A simpler way to replicate the error would be to disable the direnv hook, and then run `direnv export zsh` in the test folder. That should also show the same problem.

**Comment by zimbatm** [comment]
It looks like it's an issue with bash actually. Eg: https://unix.stackexchange.com/questions/557479/why-we-get-shell-init-error-retrieving-current-director-when-using-egrep

**Comment by EricCrosson** [comment]
> getcwd: cannot access parent directories: Bad file descriptor is really weird. It might be a Golang regression on the Big Sur kernel as Go does its own syscall mapping.

Mind you I only updated to Big Sur _because_ my old pal direnv wasn't working 😢 

> It looks like it's an issue with bash actually. Eg: https://unix.stackexchange.com/questions/557479/why-we-get-shell-init-error-retrieving-current-director-when-using-egrep

I landed on this link and a dozen others like it, suggesting I'm running a command inside a directory that doesn't exist anymore -- but I have no idea which directory that would be. Every dir I'm working with still clearly exists! If it's some dir in the hook I am not sure what or how it broke

> A simpler way to replicate the error would be to disable the direnv hook, and then run direnv export zsh in the test folder. That should also show the same problem.

Can confirm this reproduces the error and gives me som additional output -- though, it mostly looks unhelpful

```sh 
shell-init: error retrieving current directory: getcwd: cannot access parent directories: Bad file descriptor
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
pushd: error retrieving current directory: getcwd: cannot access parent directories: Undefined error: 0
job-working-directory: error retrieving current directory: getcwd: cannot access parent directories: Undefined error: 0
export DIRENV_WATCHES=$'eJx8zrFOw0AMANB_8RzVdu-SXLMzIrEwIQbH56oRIYfs0CIh_p0dpP7A03v5hifZLzABPod5oPmi6i2ibXhr_hYfooYH266u0MFjq_vybjDxQP2Qj4VzBw9fS-wB0-6f9tPdEw9rU1kxLuKGdXHbrijr2m5IpeixJyKeec5WKVGt5aQDn8c-KWse2dJZmOZBOJVRaq_MY1IqKZ_k_y0x8Z_b628AAAD__-gSS5A=';export DIRENV_DIFF=$'eJw0ys1ugjAAAOB36VkispUhyQ5FUAqi_EwULo1AGcVosVVBjO--0-7fC3TAfL0n4ALMF7Bx7GxSYuMYmECZ7iQVckoFK0vBpeSXac_FSXbHkoLJP96jn4XrJMAE1BuMUSy3vYoCtLGIEY9pdVeSwzoYsXB6HBUu1HmMs1qqC9yQTq268AupHw_YsDpfj8gKeQV5eGY601hxaARpsprzzNV0_a4Gy_ZKHs-itYco1KL2Mx2tfl4nSm-pil7Pb2Hl9HOxm52G9d1fVQe3EKwV2hnijrLBe_qUlnDvp6sbPEb2xSgVfy-pVnn5eZtbWy-Nj1cSZDN89XNyIk91MHJS6JqBELIJUX6TBKJv8H7_BQAA__8d2WaK';export DIRENV_DIR=$'-/Users/ericcrosson/workspace';  
```

**Comment by zimbatm** [comment]
can you try to `brew install bash` to get a more modern version of it? macOS ships with a 12 years old version

**Comment by zimbatm** [comment]
Is it possible that there is a symlink somewhere in that path? `/Users/ericcrosson/workspace/.envrc`

**Comment by EricCrosson** [comment]
Holy smokes, that did it! I was just about to post that

```
Upgrading bash is futile, I am starting with bash version GNU bash, version 5.0.18(1)-release (x86_64-apple-darwin19.6.0), and homebrew says my bash is already installed and up to date. But let me try anyway
```

So I ran 

```
brew reinstall bash
```

and the same version installed but now direnv is working again! 

I was also skeptical that this would have any effect since I'm using zsh not bash, and direnv is written in go? But I will take it! This issue is resolved. 

Great thinking @zimbatm . Thank you for helping me debug this, and thank you for your work creating such a useful tool!

**Comment by zimbatm** [comment]
Glad we got this sorted!

Direnv actually loads the `.envrc` with bash and then re-exports the result into the target shell. So that explains why bash was being used ;)
