### ISSUE TITLE
switch envs according to git branch

### ISSUE THREAD

**Issue by pyfs** [direnv/direnv#721]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
.envrc is ignored by git, how can i switch env variables between different branch;

for example, database connections are always the same variable name but different values, it need to be changed between "master" and "develop" branches;

**Comment by 24601** [comment]
.envrc being ignored by git is a "good" thing in the sense you probably don't want runtime secrets & config in git. 

I use $(git branch --show-current) to accomplish this.

For example, a variable that needs to be set by-branch could look something like this:

```
export APP_BASE_URL=https://$(git branch --show-current).domain.com
```

You could also get freakier with things like look up tables, etc, etc that use the output from git branch --show-current to resolve some other value.

**Comment by pyfs** [comment]
> I use $(git branch --show-current) to accomplish this.
> 
> For example, a variable that needs to be set by-branch could look something like this:
> 
> ```
> export APP_BASE_URL=https://$(git branch --show-current).domain.com
> ```
> 
> You could also get freakier with things like look up tables, etc, etc that use the output from git branch --show-current to resolve some other value.
> https://gist.github.com/flesler/a2f5d1286fbb8fd467dc25824d564485


Glad to see your reply which  light up my idea;

Thank you very much;

**Comment by dzintars** [comment]
I believe, you could also use `post-checkout` Git hook to achieve something like that. Just make sure you tidy env things up after you leave/switch off particular project.
