### ISSUE TITLE
64-bit ARM on Linux

### ISSUE THREAD

**Issue by jwillikers** [direnv/direnv#724]
**Is your feature request related to a problem? Please describe.**

There are currently no 64-bit ARM binaries available for Linux, and I would like to use direnv on my Pinebook Pro.

**Describe the solution you'd like**

It would be great if there were binaries available on the GitHub releases page. This would work with how the asdf direnv plugin retrieves the direnv binaries, allowing me to install direnv that way.

**Describe alternatives you've considered**

I can build from source, but that isn't very convenient.

I'm using Manjaro and there is a package available from the AUR, but it does not list  support for 64-bit ARM.

**Comment by rmorgans** [comment]
I've updated the aur to add aarch64 to the PKGBUILD. Does this help?

**Comment by zimbatm** [comment]
related issue: https://github.com/mitchellh/gox/issues/146

**Comment by jwillikers** [comment]
@rmorgans It builds without a hitch from the AUR on my Pinebook Pro, thanks!

**Comment by zimbatm** [comment]
Do you mind trying the latest release? https://github.com/direnv/direnv/releases/tag/v2.25.0

**Comment by jwillikers** [comment]
@zimbatm This is fantastic! 🥳 It's working great on my Pinebook Pro. I really appreciate it!
