### ISSUE TITLE
Providing strict_env compatible version of dotenv

### ISSUE THREAD

**Issue by aneeshusa** [direnv/direnv#728]
**Is your feature request related to a problem? Please describe.**
I noticed `strict_env` was [recently added](https://github.com/direnv/direnv/pull/572) with the intent to eventually be the default, which I fully support.
I audited my existing `.envrc` file and was able to change `source_env` to `source_env_if_exists` but didn't see an equivalent for `dotenv`.
Here is my `.envrc` for context:
```
dotenv .env
dotenv .env.development
dotenv .env.local
source_env_if_exists .envrc.local
```
This is a `.envrc` file I use across many repos, which may or may not have `.env`, `.env.development`, or `.env.local` files; the goal is to opportunistically load them if present.
So, I'd like advice on the best way to future-proof the `dotenv` invocations in .envrc file for a future with `strict_env` by default.

**Describe the solution you'd like**
My current thinking is that we could add a `dotenv_if_exists` function in the stdlib.
From skimming `stdlib.sh`, it doesn't seem like many other functions would need `_if_exists` versions
beyond the existing `source_env_if_exists` and a proposed `dotenv_if_exists`.

**Describe alternatives you've considered**
I could tweak the `.envrc` in each repo to only mention the .env files present, but that seems easy to forget to update if a file is added or removed. I'd like to be able to have the same contents in every repo.

I could have some inline if statements to check if the file exists before calling `dotenv`, but it seems better to pull it into a function instead of copy/pasting that 3x per repo.

We could make `dotenv` not error if the file doesn't exist, but that would be a behavior change.

With the `dotenv_if_exists` approach, there may be a large number of additional stdlib functions that would need `if_exists` versions (like maybe `layout_pipenv`?),
in which case there may be a more general solution that would be preferred than having 2x copies of each function.
(I'm fairly new to direnv so not sure what the accepted best practice/style is.)

**Additional context**
Thanks for direnv, it's been really nice to start using it (had known about it for a while from Nix but just set up it a week or two ago)! Trying to spread its usage at work now and want to future-proof before I do so :)

**Comment by zimbatm** [comment]
Thanks for summarizing your thoughts. Everything you said makes sense, and you have good questions.

I haven't thought deeply about this particular subject yet.

For the short term, I would recommend transforming the `.envrc` to:
```sh
strict_env
[[ ! -f .env ]] || dotenv .env
[[ ! -f .env.development ]] || dotenv .env.development
[[ ! -f .env.local ]] || dotenv .env.local
source_env_if_exists .envrc.local
```
Notice the negative tests. This is necessary because `[[ -f .env ]] && dotenv .env` would early-exit if the file doesn't exist, and return 1, which leads to bash killing the main script (due to `set -e`). Anyways, that's the backward-compatible approach.

For the future, I think it makes sense to add `dotenv_if_exists`. If you send in a PR, I would accept it. It's a bit of a mouthful to write but has the benefit of being explicit.

**Comment by aneeshusa** [comment]
AIUI we'd also need to `watch_file` each file like `source_env_if_exists` which is a bit more boilerplate: https://github.com/direnv/direnv/blob/29612990db729f638230d3dd96d96d29b3dc4b6b/stdlib.sh#L352-L355

Can try to put together a PR for `dotenv_if_exists` since it sounds like the best path forward but might take a few days. Happy to have someone else jump in in the meantime.
