### ISSUE TITLE
test/stdlib.bash fails if /tmp is noexec

### ISSUE THREAD

**Issue by etcusrvar** [direnv/direnv#729]
**Describe the bug**
* Running `./test/stdlib.bash` fails with exit status 1, with no output.

```sh
$ ./test/stdlib.bash
--- find_up
--- source_up
direnv: loading ~/direnv/test/.envrc
--- direnv_apply_dump
--- PATH_rm
--- path_rm
--- expand_path
--- semver_search
--- use_julia
$ echo $?
1
```

**To Reproduce**
* `sudo mount -o remount,noexec /tmp`
* `./test/stdlib.bash`

**Expected behavior**
* At least display something, rather than exiting with no output.

**Environment**
 - OS: Arch Linux
 - Shell: zsh
 - Direnv version: 2.25.0

**Additional context**
* /tmp is mounted with noexec option
    > `$ mount | grep -w \/tmp`
    > tmpfs on /tmp type tmpfs (rw,nosuid,noexec,noatime,inode64)
* workaround: set $TMPDIR as described in [mktemp.1](https://jlk.fjfi.cvut.cz/arch/manpages/man/core/coreutils/mktemp.1.en)
    > `$ TMPDIR=$XDG_RUNTIME_DIR ./test/stdlib.bash`
* To see an actual error message to figure out why it was failing, I had to run `bash -x ./test/stdlib.bash`

**Comment by etcusrvar** [comment]
This issue causes installs/upgrades from AUR to fail on Arch, without workarounds (either setting TMPDIR, or remounting /tmp with exec option).

**Comment by RouNNdeL** [comment]
Remounting `/tmp` as executable did not fix the issue for me.

**Comment by megawebmaster** [comment]
Unfortunately the fix still doesn't work for me on ArchLinux even though I tried installing 2.27.0 (which is supposedly fixed). @zimbatm could you please take a look again?

**Comment by zimbatm** [comment]
I would need more debug info. `direnv version` and `type -f _direnv_hook` at minimum

**Comment by megawebmaster** [comment]
@zimbatm - sorry I didn't provide it earlier. I wasn't able to get it to run, so I have no idea why I have such problems.

```
$ direnv version
2.23.1
$ type -f _direnv_hook
_direnv_hook () {
	eval "$(direnv export zsh 2> >( egrep -v -e '^direnv: (loading|export|unloading)' ))"
}
```

Here's output from `bash -x ./test/stdlib.bash`: https://gist.github.com/megawebmaster/60f2fc0900f001b2650e42282d9f3f10

Let me know what else I can give you to resolve the issue :muscle:
