### ISSUE TITLE
Wrong version reported for direnv.windows-amd64.exe (2.25.1)

### ISSUE THREAD

**Issue by goostleek** [direnv/direnv#731]
At first, I thought the version was wrongly updated in the [scoop bucket](https://github.com/ScoopInstaller/Main/blob/master/bucket/direnv.json#L8) but it's not.

When you download the latest `amd64` version directly from the release page (by using the link https://github.com/direnv/direnv/releases/download/v2.25.1/direnv.windows-amd64.exe) then it seems the compiled version is `2.24.0`:

![image](https://user-images.githubusercontent.com/7780330/101906162-d34d1e80-3bb8-11eb-9732-5c694552c330.png)

**Comment by zimbatm** [comment]
Looks like there was an issue during the release. I re-generated the exe and replaced it in the release.

**Comment by zimbatm** [comment]
Can you try https://github.com/direnv/direnv/releases/tag/v2.25.2 ?

**Comment by pjos** [comment]
> Can you try https://github.com/direnv/direnv/releases/tag/v2.25.2 ?
I've downloaded and tried 2.52.2 release and it look good over here !

**Comment by goostleek** [comment]
I don't have access to my laptop over the weekend. I'll check the release tomorrow morning.

**Comment by goostleek** [comment]
Ok, I can confirm the fix is working as expected ❤️. I have just updated to the latest version (`2.25.2`) and now it reports proper version. What's more, it seems that the latest release resolved #707 as well 🚀. Thank you!

**Comment by zimbatm** [comment]
Perfect, thanks!
