### ISSUE TITLE
Add support for Apple Sillicon

### ISSUE THREAD

**Issue by vestimir** [direnv/direnv#738]
Currently there's no native ARM version of direnv for macOS. What would be needed to add support for M1 macs?

**Comment by zimbatm** [comment]
Go probably needs to be updated, I don't know if it already supports that target or not. The update the `dist` target in the GNUMakefile to also generate that platform.

**Comment by zimbatm** [comment]
Depends on Go 1.16 which hasn't been released yet: https://github.com/golang/go/issues/38485#issuecomment-747633830

**Comment by leungbk** [comment]
Go 1.16 is now out: https://golang.org/doc/go1.16#darwin

**Comment by zimbatm** [comment]
the latest release includes the darwin/arm64 build. Does somebody want to test it out?

**Comment by zimbatm** [comment]
link to release: https://github.com/direnv/direnv/releases/tag/v2.28.0

**Comment by wingrunr21** [comment]
I tested it when I opened the PR. Works fine on my M1 Mac Mini
