### ISSUE TITLE
fish: Expected end of the statement, but instead found end of the input

### ISSUE THREAD

**Issue by amir20** [direnv/direnv#742]
**Describe the bug**
`eval (direnv hook fish)` produces an error on fish

**To Reproduce**
Run `eval (direnv hook fish)` with version `2.26.0` direnv. 

Error: `fish: Expected end of the statement, but instead found end of the input`

**Expected behavior**
No error

**Environment**
 - OS: [e.g. macOS Mojave, Ubuntu 18.04, ...] Mac Os 11.1
 - Shell: [e.g. bash, zsh, ...] fish 3.1.2
 - Direnv version [e.g. 2.20.0] 2.26.0

**Additional context**

**Comment by jerome-laforge** [comment]
I just upload my Manjaro (linux based Archlinux), and I have the same problem.
It broke all my dev env. It is really painful.

**Comment by ruslandoga** [comment]
Seems like the command now is

```sh
direnv hook fish | source
```

**Comment by jerome-laforge** [comment]
thx @ruslandoga, it works perfectly.

**Comment by ariasuni** [comment]
I had the same problem and using `direnv hook fish | source` fixed it. Maybe this change should be mentioned in the GitHub release notes and CHANGELOG.md.

**Comment by wderezin** [comment]
I tracked down the issue and will push a PR shortly to maintain backward compatibility.   The issue was eval not handling the comments I added.

**Comment by zimbatm** [comment]
I am cutting a new release right now. Unfortunately, I was also doing a bit of cleanup in master which changes how things are packaged, so it might take a bit longer for package managers to update to this release.

**Comment by reitzig** [comment]
Should the documentation be changed back to `eval`?

**Comment by zimbatm** [comment]
`direnv hook fish | source` is what is supported going forward

**Comment by reitzig** [comment]
Okay, thanks for clarifying! :pray:
