### ISSUE TITLE
Docs: https://direnv.net/man/direnv-stdlib.1.html lists "use node" twice

### ISSUE THREAD

**Issue by thernstig** [direnv/direnv#746]
It has both `use node [<version>]` and `use node <version>` in two different sections, when the first one should be sufficient.

The text for `use node [<version>]` should also be updated, as now it is slightly confusing in that it mentions it loads from a version file `.node-version` or `.nvmrc`, but the heading as well as the second paragraph indicates it can be used with a version number to specify a specific version (not looking in the version file).

**Comment by zimbatm** [comment]
thanks!
