### ISSUE TITLE
[Feature/Question] Nested directory envrc support

### ISSUE THREAD

**Issue by Pk13055** [direnv/direnv#757]
**Is your feature request related to a problem? Please describe.**
I don't know if this is currently possible (didn't find any documentation in the wiki), but would it be possible to support nested dirs (`.envrc` inside child folders) as a cascade?

**Describe the solution you'd like**
For eg, in the following strcuture: 
```
foo
├── .envrc
└── bar
    └── .envrc
1 directory, 2 files
```
Entering foo will load whatever statements are present in the top level .envrc and further cd-ing into bar will load additional statements in the child `.envrc` without unloading the prior ones.

**Additional context**
Shell: zsh
direnv version: 2.15.0

**Comment by zimbatm** [comment]
It is possible but not automatic. In bar/.envrc, add `source_env ..` or `source_up` to the file so it sources the parent folder. There are a number of builtin functions like that available in https://direnv.net/man/direnv-stdlib.1.html

**Comment by Pk13055** [comment]
Oh, that's awesome! Guess I missed this link ^ Thanks :D

**Comment by dzintars** [comment]
The issue with `source_env` is that it reads the whole parent file. If you use something like `secret-tool lookup` it will trigger all the lookups you have in the root and if you have notifications enabled about secret access, then you will be flooded with the notifications for root secret access which you don't even need currently.
It could be neat, if nested `.envrc` SOMEHOW MAGICALLY could read just "imported" root secrets.

**Comment by iloveitaly** [comment]
> If you use something like `secret-tool lookup` it will trigger all the lookups you have in the root

Yup, running into this exact problem. Were you able to find a cleaner solution here?

**Comment by danielo515** [comment]
So I want this to happen without having to modify the current `.envrc` file. I have a bunch of projects under a parent folder that I want to provide some environment variables, but I don't want to modify those projects .envrc files to read from my parent environment. Is this possible somehow? A command like `direnv allow .` but for letting it know that  it should read from parent env too will be awesome
