### ISSUE TITLE
OpenBSD package is now unupdatable - mirror on proxy.golang.org?

### ISSUE THREAD

**Issue by fagg** [direnv/direnv#762]
Hello there,

I'm the maintainer of the direnv package for OpenBSD.

Since v2.27.0 no longer vendors the dependencies, I cannot update the OpenBSD ports package to the latest version due to the way our ports system works.

Because the dependencies now need fetching, we can no longer just point our port to pull in the release tarball from Github. This is due to a policy regarding how our dependencies are fetched - packages are *not* allowed to pull during build time, the dependencies must be fetch ahead of time. Thus, downloading and untarring and then trying to go build results in errors from our packaging system because it cannot download the dependencies it needs.

The way this is currently achieved for our go packages is to pull from proxy.golang.org - in fact, it is my understanding that this is the only supported method for such things (I have sought clarification on that).

It seems that there is a very old version of direnv on proxy.golang.org. Would it be possible for future releases to be accompanied by a corresponding submission to proxy.golang.org? This would make continued maintenance of the OpenBSD port trivial.

I can only speak specifically to OpenBSD's package/port requirements, however my research indicates that OpenBSD ports may not be the only system with such a restriction.

Thanks,

ajf

**Comment by qbit** [comment]
Bit more info on this. The OpenBSD ports system can also use the new Go modules stuff to create a port, however, because direnv has not switched to [v2](https://github.com/direnv/direnv/issues/629), the ports framework (as well as Go tooling like `go get`) only sees [the old version](https://proxy.golang.org/github.com/direnv/direnv/@latest).

@fagg an alternative is to "vendor" the dependencies and roll our own distfile. I can offer up space to host said file if you need.

The basic process for rolling your own is:
1. `git clone repo repo-vx.y.z`
2. `cd repo-vx.y.z; git checkout vx.y.z`
3. `go mod tidy; go mod vendor`
4. `cd ../; tar -czvf dist-vx.y.z.tar.gz repo-vx.y.z`

**Comment by zimbatm** [comment]
Hello, thanks for the report. If it makes things easier for you I don't mind switching to v2. Thanks also for re-linking to that old issue, I hadn't fully understood the impact on my previous read. Just let me know what is the preferred route and I am happy to follow on that one.

**Comment by fagg** [comment]
Jonas Chevalier <notifications@github.com> writes:

> Hello, thanks for the report. If it makes things easier for you I
> don't mind switching to v2. Thanks also for re-linking to that old
> issue, I hadn't fully understood the impact on my previous read. Just
> let me know what is the preferred route and I am happy to follow on
> that one.

Hi Jonas,

Thanks for being receptive. Ideally if you could make that change,
that'd make life much easier for us.

The current version in ports is only 2.26, so we aren't far
behind. Basically, if it isn't going to be too long before you can make
these appropriate changes, we will just skip the current version and
update when we can. But if it's going to be a longer-term thing, I'm
able to do what Aaron suggested and just host my own vendored
distribution for our ports builds to use.

If you need help with anything or would like me to test anything, please
feel free to reach out.

Cheers,

Ash

**Comment by zimbatm** [comment]
Created https://github.com/direnv/direnv/pull/765 .

Is there a way for you to test this before I merge it to master?

**Comment by qbit** [comment]
I don't think there is a way to test prior to it landing.. unfortunately.

**Comment by fagg** [comment]
Aaron Bieber <notifications@github.com> writes:

> I don't think there is a way to test prior to it landing.. unfortunately.

Yeah I was just looking at that...the most I could do is just check if
it builds with OpenBSD, but I couldn't test any of the ports-related
changes described in my original post.

**Comment by zimbatm** [comment]
Ok, I merged it to master. Can you give it a shot before I cut another release?

**Comment by qbit** [comment]
You’ll have to tag the new version before the Go ecosystem will pick it up. A full GitHub releas is not needed yet though.

It can be tested easily with Go 1.16 (older versions need to have the GO111MODULE=on env var set) and:

    go get github.com/direnv/direnv@vX.Y.Z

**Comment by fagg** [comment]
Aaron Bieber <notifications@github.com> writes:

> You’ll have to tag the new version before the Go ecosystem will pick it up. A full GitHub releas is not needed yet though.
>
> It can be tested easily with Go 1.16 (older versions need to have the GO111MODULE=on env var set) and:
>
>     go get github.com/direnv/direnv@vX.Y.Z

Additionally: if you tag the version as Aaron describes, I can update my
port diff. Once the final release is cut, then I can submit it for
review and commit.

I probably won't get to that until the weekend though.

**Comment by zimbatm** [comment]
this is actually fixed now

**Comment by vitaly-zdanevich** [comment]
> packages are _not_ allowed to pull during build time, the dependencies must be fetch ahead of ti

The same for Gentoo :(
