### ISSUE TITLE
Use direnv in continuous integration

### ISSUE THREAD

**Issue by henrik242** [direnv/direnv#764]
I have not figured out if I can use `direnv` in a continuous integration system such as [Travis](https://en.wikipedia.org/wiki/Travis_CI).

Would that be possible?  Just adding something like `direnv apply` in Travis' `before_install` would be awesome.

**Comment by zimbatm** [comment]
Yes, the best way is to use `direnv exec . xxx` where `.` is the path to the folder that contains the `.envrc`, and `xxx` the command that you want to run in CI.

**Comment by henrik242** [comment]
@zimbatm That's possible, but I'd like the PATH to be set in the current before many other commands are run, without wrapping them all in a script.  I guess that's not within direnv's scope :)

**Comment by henrik242** [comment]
In case anyone else needs this:  I created a small shell script that does just what I need.  Called as `before_install: eval $(evaluate-envrc.sh)`  in travis.yml:

```
#!/usr/bin/env bash

set -o errexit -o pipefail -o nounset

#
# Set current shell environment according to direnv's .envrc
#
# Usage: eval $(tools/finnbuild/evaluate-envrc.sh)
#

newpaths=""
while read -r line; do
  case $(echo $line | cut -d\  -f1) in
    export)
      echo $line
      ;;
    PATH_add)
      newpaths+="\$PWD/$(echo $line | cut -d\  -f2):"
      ;;
    *)
      echo "# Unsupported .envrc command: $line"
      ;;
  esac
done < .envrc

echo "export PATH=$newpaths$PATH"
```

**Comment by zimbatm** [comment]
Usually, I try to wrap complicated steps into scripts. That way they can be tested directly from the developer's machine without going through CI. That's where `direnv exec . ./ci.sh` would shine.

Another approach is to eval direnv at the start of the script like that:
```sh
eval "$(direnv export bash)"

# put the CI steps here
```

**Comment by henrik242** [comment]
Ahh, thanks! I thought that would do the trick, but `direnv export bash` didn't seem to output anything for me.... until I tried in a shell where direnv wasn't already enabled.  Now it works.  Thanks!
