### ISSUE TITLE
direnv: unloading after each command and I am unable to find out where this comes from

### ISSUE THREAD

**Issue by a4z** [direnv/direnv#771]
**Describe the bug**
everything was working nicely, and all the sudden I get
```
direnv: unloading
```
after every shell command in what ever direnv enabled folder I am in

**To Reproduce**
I am not sure ... ?

**Expected behavior**
as before, no `direnv: unloading` after each command in direnv environments

**Environment**
 - OS: [e.g. macOS Mojave, Ubuntu 18.04, ...]
 - Shell: [e.g. bash, zsh, ...]
 - Direnv version [e.g. 2.20.0]

**Additional context**

I tried to chain some direnvs, with `source_up` and `layout python3` to share python pips between different envs.
The I removed it

I also run `direnv hook zsh` and `direnv hook bash` today,  just to see what those command do, 

but I have since then restated my machine, so I seriously can not guess where this is coming from.

Any debug command I could execute?

**Comment by a4z** [comment]
mabye this as additional info, to demonstrate the problem

```
-> cd tmp/denv 
direnv: loading ~/tmp/denv/.envrc
direnv: export +USERENV ~PATH
direnv: unloading                                                                                                                                                                                                                                    

[a4z@mach2:~/tmp/denv] (17:58:27) (direnv)
-> ls
direnv: unloading                                                                                                                                                                                                                                    

[a4z@mach2:~/tmp/denv] (17:58:30) (direnv)
-> ls -a
.      ..     .envrc
direnv: unloading                                                                                                                                                                                                                                    

[a4z@mach2:~/tmp/denv] (17:58:35) (direnv)
-> cat .envrc 


export USERENV=direnv

PATH_add $(pwd)


```

**Comment by a4z** [comment]
just found https://github.com/direnv/direnv/issues/726 describing the same problem

**Comment by a4z** [comment]
it seems I can silence the message by putting a `export DIRENV_LOG_FORMAT=` into the `.envrc` file .
but that is not nice

**Comment by zimbatm** [comment]
Closing as duplicate. Let's continue the convo there. :+1:
