### ISSUE TITLE
Setting ulimit via direnv on fish does not seem to work

### ISSUE THREAD

**Issue by taranlu-houzz** [direnv/direnv#777]
**Describe the bug**
I'm trying to set the file descriptor limit via `direnv` using this `.envrc`:
```
# .envrc
ulimit -n 10000
```

This does not seem to work on `fish`. Other statements in `.envrc` work, such as `export MYVAR="snarf"` or `echo hello`.

I am not sure if this is a bug, but I have not been able to figure out how to make it work.

**To Reproduce**
- Ensure `ulimit` is less than 10000
- Try using `direnv` with the above `.envrc`

**Expected behavior**
`direnv` should set the `ulimit` as expected.

**Environment**
 - OS: macOS 10.14.6 (Mojave)
 - Shell: fish (alacritty -> fish -> tmux -> fish)
 - Direnv version: 2.27.0

**Comment by zimbatm** [comment]
direnv can only set environment variables. The .envrc is executed in a bash sub-shell and then the env vars re-exported to the target shell.

**Comment by taranlu-houzz** [comment]
Ah, okay, I misunderstood that then. I was actually trying to follow the troubleshooting section for `pants`: https://www.pantsbuild.org/docs/troubleshooting, so it seems their documentation is wrong as well.

Thank you for clarifying that for me.
