### ISSUE TITLE
Sourcing setup.zsh created by catkin fails

### ISSUE THREAD

**Issue by jbreitbart** [direnv/direnv#786]
**Describe the bug**
I am trying to source a setup.zsh as it is generated by catkin, but I get the following error messages:

```
devel/setup.zsh: line 7: cd: -q: invalid option
cd: usage: cd [-L|[-P [-e]] [-@]] [dir]
devel/setup.zsh:8: emulate: command not found
```

My .envrc file looks like
```
ᨂ cat .envrc
source devel/setup.zsh
```

and the content of setup.zsh is:

```
ᨂ cat devel/setup.zsh
#!/usr/bin/env zsh
# generated from catkin/cmake/templates/setup.zsh.in

CATKIN_SHELL=zsh

# source setup.sh from same directory as this file
_CATKIN_SETUP_DIR=$(builtin cd -q "`dirname "$0"`" > /dev/null && pwd)
emulate -R zsh -c 'source "$_CATKIN_SETUP_DIR/setup.sh"'
```

If I just source the file in my shell I get no error message.

**To Reproduce**
Create a minimal ROS project and try to source the setup.zsh file. I can provide additional information if it will be necessary.

**Expected behavior**
That sourcing the file works.

**Environment**
 - OS: Ubuntu 18.04
 - Shell: zsh
 - Direnv version 2.28.0

**Comment by zimbatm** [comment]
It's because direnv evaluates the .envrc with bash, and then re-exports all the environment variables to the target shell. Try sourcing `devel/setup.sh` if that exists instead.

**Comment by jbreitbart** [comment]
Thanks a lot! There actually is a setup.sh (and a setup.bash) and that seems to fix the issue.
