### ISSUE TITLE
Stacked .envrc

### ISSUE THREAD

**Issue by alexander-myltsev** [direnv/direnv#789]
I looked at other issues but I didn't find the resolution.

**Describe the bug**
I have a root directory for different projects. All projects share the same environment variables. But I also want them to have specific ones. Then I go to a project, it resets `.envrc` from the parent directory.

**To Reproduce**
```bash
$ cd project-root
$ ls
subproject
$ cat .envrc
export ROOT_VAR=1
$ echo $ROOT_VAR
1
$ cd subproject
$ cat .envrc
export SUB_VAR=2
$ echo ${ROOT_VAR-nope}
nope
$ echo SUB_VAR
2
```

**Expected behavior**
I expect `echo ${ROOT_VAR-nope}` from the subproject directory to return 1.

**Environment**
 - OS: macOS BigSur 11.2.3
 - Shell: zsh 5.8 (x86_64-apple-darwin20.1.0)
 - Direnv version: direnv v2.27.0

**Comment by noel-yap** [comment]
This is a dup of https://github.com/direnv/direnv/issues/772
