### ISSUE TITLE
Force Export

### ISSUE THREAD

**Issue by mbrevda** [direnv/direnv#794]
How can I force `direnv export` (or any command) to return a list of defined variables? I'd like to pass all vars to docker and am looking for a simple, cross platform way to do this. Thanks!

**Comment by zimbatm** [comment]
`docker export json` gives you the diff, but only if the environment is unloaded.

**Comment by zimbatm** [comment]
If the environment is loaded, use `direnv show_dump "$DIRENV_DIFF"`.

**Comment by mbrevda** [comment]
Awesome, thanks!
