### ISSUE TITLE
Sops encrypted .env files

### ISSUE THREAD

**Issue by tonsV2** [direnv/direnv#805]
**Is your feature request related to a problem? Please describe.**
I use direnv in pretty much all of my coding projects and it would be really nice to be able to commit my .env files into git even when they contain sensitive information such as passwords and other kind of credentials.

**Describe the solution you'd like**
Sops encrypted .env files could support the above use case.

https://github.com/mozilla/sops

I recently used it in a Go project of mine and it worked like a charm.

https://github.com/mozilla/sops/blob/master/decrypt/decrypt.go

Since key stores from all the major cloud providers are support this would also allow all developers to use the same .env file.

**Comment by johnhamelink** [comment]
Perhaps you could try [git-crypt](https://www.agwa.name/projects/git-crypt/)?

**Comment by Mic92** [comment]
I use this in direnv to import secrets from sops

```
export $(sops -d --output-type dotenv secrets.yaml | xargs) 
```

You can add grep if you want to filter out only certain secret keys.

**Comment by Mic92** [comment]
I actually found a better way:

```
eval "$("$direnv" dotenv bash <(sops -d --output-type dotenv secrets.yaml))"
```

**Comment by zimbatm** [comment]
Looks like you already discovered this in 2020 :)

https://github.com/direnv/direnv/wiki/Sops

**Comment by zimbatm** [comment]
I added a link to it on the wiki landing page.

**Comment by kschamplin** [comment]
I can't seem to get this working... direnv always complains about an invalid line (since it doesn't have `export` in front). Have there been changes since then that could have caused this? I'm using version 2.32.0.

**Comment by musicformellons** [comment]
@kschamplin Although not mentioned the scripts are reading `.env` files instead of the direnv default `.envrc` files. You can use a direnv config file to read `.env` files as well. Or, simpler, just add `dotenv` to your `.envrc` file and direnv will read the `.env` file as well.

**Comment by c33s** [comment]
```
use_sops() {
    local path=${1:-$PWD/secrets.yaml}
    eval "$(sops --decrypt --output-type dotenv $path | awk -F '=' '{print "export", $1 "=" $2}')"
}
```

can be used as:

```
use sops
```

or 

```
use sops custom_dot_env_secret
```

as sops doesn't recognize custom dot env names (how should it), encrypt it like this:

```
sops --encrypt --input-type dotenv custom_dot_env > custom_dot_env_secret
```
