### ISSUE TITLE
Feature: chain two .envrc

### ISSUE THREAD

**Issue by domenkozar** [direnv/direnv#807]
It would be a simple way to do declarative environments with Nix.

So given I have:

- /home/user/.envrc
- /home/user/project/.envrc

And I enter `/home/user/project/`, it would load both environments!

The important bit is that `home/user/project/.envrc` should never know about `/home/user/.envrc` because it would usually be a git project outside of my control.

If I understand correctly, `use nix` would need to be able to accept argument to locate `/home/user/shell.nix`.

**Comment by buschtoens** [comment]
I would love this!

The `direnv-stdlib` already offers a few helpful commands: 

> #### [`source_up [<filename>]`](https://direnv.net/man/direnv-stdlib.1.html#codesourceup-ltfilenamegtcode) 
>
> Loads another `.envrc` if found when searching from the parent directory up to /.
>
> NOTE: the other `.envrc` is not checked by the security framework.
>
> #### [`source_env <file_or_dir_path>`](https://direnv.net/man/direnv-stdlib.1.html#codesourceenv-ltfileordirpathgtcode)
>
> Loads another `.envrc` either by specifying its path or filename.
> 
> NOTE: the other `.envrc` is not checked by the security framework.
> 
> #### [`source_env_if_exists <filename>`](https://direnv.net/man/direnv-stdlib.1.html#codesourceenvifexists-ltfilenamegtcode)
>
> Loads another `.envrc`, but only if it exists.
> 
> NOTE: contrary to `source_env`, this only works when passing a path to a file, not a directory.
> 
> Example:
> ```sh
> source_env_if_exists .envrc.private
> ```

But using these commands has two major problems:

- It bypasses the security framework for all parent `.envrc` files.
- It has to be explicitly invoked by the leaf node `.envrc` file.

What we'd need instead IMO is a way for parent directory `.envrc` files to specify that they must not be unloaded when child directory `.envrc` files are loaded. All parent directory `.envrc` files, that specify that they are not be unloaded, are applied sequentially from root to leaf.

To indicate this we could add a new command like `sticky` to the `direnv-stdlib`.

I'd also like safe equivalents for [`source_env <file_or_dir_path>`](https://direnv.net/man/direnv-stdlib.1.html#codesourceenv-ltfileordirpathgtcode) and [`source_env_if_exists <filename>`](https://direnv.net/man/direnv-stdlib.1.html#codesourceenvifexists-ltfilenamegtcode) that explicitly _do_ use the security framework. This would allow us to conveniently consume partial `.envrc` files that are checked into version control.

```sh
# .envrc.example
# Copy this file as `.envrc` to opt-in to automatic env management.
# Comment out unwanted environments to disable them.

include .envrc.frontend
include .envrc.backend
```

The proposed `include <filename>` command would behave like `source_env`, but with these additions:
- The file is watched for changes, e.g. as if [`watch_file <filename>`](https://direnv.net/man/direnv-stdlib.1.html#codewatchfile-ltpathgt-ltpathgt-code) were called.
- The target file is checked by the security framework. Before changes take effect, they must be `direnv allow`-ed.
  Should `direnv allow` require the path to be specified, i.e. `direnv allow .envrc.frontend`?

**Comment by buschtoens** [comment]
Seems related to or duplicate #772.
