### ISSUE TITLE
direnv: error $PWD/.envrc is blocked. Run `direnv allow` to approve its content

### ISSUE THREAD

**Issue by sgohl** [direnv/direnv#812]
**Describe the bug**

This may not particularly a bug, but it's very annoying to be forced to manually allow every folder, actually it's the blocking point for me to even be able to use direnv

**To Reproduce**

- place .envrc
- get beaten by `direnv: error $PWD/.envrc is blocked. Run `direnv allow` to approve its content`

**Expected behavior**

A possibility to globally silently have any existance of `.envrc` to be allowed. I know what I'm doing! 

**Environment**
 - OS: `Fedora 32`
 - Shell: `bash`
 - Direnv version: `2.21.2`

**Additional context**

My proposal would be an option like

```
direnv allow all
```

which then will be permanently stored where you already store the allows. this would perhaps then even be compatible with prune

**Comment by zimbatm** [comment]
This can easily be achieved by configuring direnv. Create a `$HOME/.config/direnv/direnv.toml` file and then whitelist the paths that you want to trust: https://direnv.net/man/direnv.toml.1.html#codeprefixcode

**Comment by sgohl** [comment]
But i trust *all* paths, who are not known individually. 

My particular use case is to preset environment variables (versions and such) for (very complex!) development (enterprise) environments in many repositories and users who would be confused by such error messages and would possibly flood 1st level with frantic tickets like usual ...

**Comment by sgohl** [comment]
or .. does 

```
[whitelist]
prefix = [ "/" ]
```

work?

**Comment by sgohl** [comment]
I tried it now via config toml, but it seems the toml is not read:

```
sgohl@sgohl ~/tmp > cd 2
direnv: error /home/sgohl/tmp/2/.envrc is blocked. Run `direnv allow` to approve its content
sgohl@sgohl ~/tmp/2 > direnv status
direnv exec path /usr/bin/direnv
DIRENV_CONFIG /home/sgohl/.config/direnv
bash_path /usr/bin/bash
disable_stdin false
warn_timeout 5s
whitelist.prefix []
whitelist.exact map[]
Loaded RC path /home/sgohl/tmp/2/.envrc
Loaded watch: ".envrc" - 2021-07-07T15:52:12+02:00
Loaded watch: "../../.local/share/direnv/allow/f6c2eba31549c5e096cdd58884386a111b896e79b4ce6215c614965ec314612b" - 1970-01-01T01:00:00+01:00
Loaded RC allowed false
Loaded RC allowPath 
Found RC path /home/sgohl/tmp/2/.envrc
Found watch: ".envrc" - 2021-07-07T15:52:12+02:00
Found watch: "../../.local/share/direnv/allow/f6c2eba31549c5e096cdd58884386a111b896e79b4ce6215c614965ec314612b" - 1970-01-01T01:00:00+01:00
Found RC allowed false
Found RC allowPath /home/sgohl/.local/share/direnv/allow/f6c2eba31549c5e096cdd58884386a111b896e79b4ce6215c614965ec314612b

sgohl@sgohl ~/tmp/2 > ls -al  ~/.config/direnv/direnv.toml 
-rw-r--r-- 1 sgohl www 43 Jul  7 15:53 /home/sgohl/.config/direnv/direnv.toml

sgohl@sgohl ~/tmp/2 > cat ~/.config/direnv/direnv.toml 
[whitelist]
prefix = [ "/home/sgohl/tmp" ]
```

**Comment by zimbatm** [comment]
Can you try renaming the config to `~/.config/direnv/config.toml`?

**Comment by zimbatm** [comment]
If `direnv status` doesn't show `whitelist.prefix [/home/sgohl/tmp]` then it's not the right location.

**Comment by StarWitch** [comment]
FWIW, the configuration worked for me as described https://github.com/direnv/direnv/issues/812#issuecomment-874918349, on macOS. (Thanks @zimbatm!)
