### ISSUE TITLE
VS Code Extension

### ISSUE THREAD

**Issue by sandstrom** [direnv/direnv#813]
Let me first say that direnv is awesome! 🏅 

Just wanted to ask, have you considered adding a VS Code Extension? Or do you feel that it's outside the scope and better left for others to work on.

There is currently this one (published in VS Code Extension marketplace), but it's abandoned since 5 years ago:
https://github.com/rubymaniac/vscode-direnv

There is also this fork, which is more up to date (but not published in VS Code Extension Marketplace):
https://github.com/cab404/vscode-direnv

For reference, this is the extension for shadowenv (a similar project), may be useful for inspiration:
https://github.com/Shopify/vscode-shadowenv

**Comment by a4z** [comment]
> There is also this fork, which is more up to date (but not published in VS Code Extension Marketplace):
> https://github.com/cab404/vscode-direnv

it is
https://marketplace.visualstudio.com/items?itemName=cab404.vscode-direnv

and you can install it from the extensions 

![direnv](https://user-images.githubusercontent.com/6172295/135317392-0e58022e-1b7b-4a3c-af2d-b7bbaac2ca6e.png)
