### ISSUE TITLE
Add "direnv block" as an alias of "direnv deny"

### ISSUE THREAD

**Issue by rvl** [direnv/direnv#832]
### Is your feature request related to a problem?

I seem to always accidentally type `direnv block` when I want `direnv deny`.

I believe other users may do the same.

### Describe the solution you'd like

Modify command-line parsing so that the `block` subcommand is an alias of the `deny` subcommand.
Also make `permit` an alias of `allow` while we're at it.
The aliases may even be hidden from the user if you wish.

### Describe alternatives you've considered

Currently I have a function in my `.zshrc` to translate my mistakes into the proper `direnv` command line.

```bash
# Translate "direnv block" to "direnv deny".
# https://unix.stackexchange.com/a/607909/12311
direnv () {
  setopt local_options extended_glob unset
  local -i i=$argv[(i)^-*]
  # $argv[i] is the first non-option argument
  # (or empty if there is none).
  # See if we want to change it.
  case $argv[i] in
    permit) argv[i]="allow";;
    block) argv[i]="deny";;
  esac
  command direnv "$@"
}
````

### Additional context

My confusion probably originates from the use of the word "block" in messages from `direnv`. For example:
```
direnv: error /home/rodney/ops/config/.envrc is blocked. Run `direnv allow` to approve its content
```

Also, language-wise I'm not an expert here, but I _think_ "block" is a closer antonym to "allow" than "deny" is. For example, "blocklist" and "allowlist" (the modern terms for "blacklist" and "whitelist"). "Block" comes from Dutch via Old English; "allow" comes vaguely from Latin, but it's mostly from French via Old English. "Deny" and "permit" are almost straight from Latin.

### Other information

Thanks for `direnv`!

**Comment by mrsauravsahu** [comment]
I always try `revoke` for some reason @rvl 😂  It'd be great if the user can define their own allow/deny synomyms.
