### ISSUE TITLE
eval in .envrc skips env variables with question marks inside

### ISSUE THREAD

**Issue by apiology** [direnv/direnv#840]
**Describe the bug**

I have a .envrc which runs eval on the output of some other process; that output contains the usual `FOO=bar; export FOO` shell env setting.

I noticed recently it had stopped working for an environment variable whose value I had recently rotated.  I was able to reduce it down to there being a question mark in the value.  

It seems to work fine outside the context of eval, but eval is necessary for my use case.

**To Reproduce**

1. Create a new directory with a .envrc file:

```sh
eval $(cat my-secrets)
```

2. Create a my-secrets file:

```sh
WORKS_FINE='abc'; export WORKS_FINE
QUESTION_MARK='?'; export QUESTION_MARK
```

3. Run `direnv allow`

**Expected behavior**

Both WORKS_FINE and QUESTION_MARK are exported.

**Observed behavior**

Only WORKS_FINE is exported.

**Environment**

 - OS: macOS Monterey 12.0.1
 - Shell: system bash; BASH_VERSION says 3.2.57(1)-release
 - Direnv version: 2.28.0

**Additional context**

Running the same eval in my login shell without direnv works just fine.  Adding a backslash in front of the question mark works fine.  In reality I'll just rotate this password again and whatnot, but I thought you folks would want to know.

My use case with eval is to run a [tool I've built](https://github.com/apiology/op_env) that ties it into 1Password and lets me avoid having passwords on disk.  I use Python to escape the passwords in that tool, and Python does not feel compelled to add the backslash when using single quotes:

```sh
$ python
Python 3.8.5 (default, Nov 30 2020, 11:03:40) 
[Clang 12.0.0 (clang-1200.0.32.27)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import shlex
>>> shlex.quote('?')
"'?'"
>>> 
```

**Comment by apiology** [comment]
Yes, that resolved the issue!  I'll move to that syntax as a workaround.  It does not seem to be necessary on the command line, though:

```sh
$ echo QM before: $QUESTION_MARK; eval $(cat direnv-repro/my-secrets); echo QM after: $QUESTION_MARK
QM before:
QM after: ?
$ 
```

**Comment by zimbatm** [comment]
It depends on the value of the IFS variable. If the output is not quoted, the result will be split by IFS and passed as arguments to the `eval` command. That's why it's important to always quote everything in bash.

Always run shellcheck on your scripts to find these issues out. In that case it would have directed you to https://github.com/koalaman/shellcheck/wiki/SC2046

**Comment by apiology** [comment]
Ah, yes, you're right that I had a hole in my tooling.  Should be fixed now--thanks for the explanation!
