### ISSUE TITLE
Check presence of env-vars

### ISSUE THREAD

**Issue by eval** [direnv/direnv#843]
**Is your feature request related to a problem? Please describe.**

I often use the following setup when working with teams:
- `.envrc.local` git-ignored (originating from `.envrc.local.example`) and `.envrc` in git containing:
```
# .envrc
export DATABASE_URL=postgres://localhost:5432/project_development

source_env_if_exists .envrc.local
# Beyond this point we need SOME_TOKEN to be present
```
So DATABASE_URL is a variable that is straightforward: we can provide a sane default value and if needed it can be locally overridden.

There are also variables that our project requires but 1) for which we cannot provide plausible defaults (vary too much per developer) or 2) that are secrets which we won't include in `.envrc`.

**Describe the solution you'd like**

For these types of variables it would be nice to have the possibility to check their presence and warn if absent:
```
# at end of .envrc
env_vars_required GITHUB_NAME, SOME_TOKEN
```

**Comment by zimbatm** [comment]
Sounds good. It would something like this:
```sh
env_vars_required() {
  for var in "$@"; do
    if [[ -z ${!var} ]]; then
      echo "env var $var is required and missing" >&2
      return 1
    fi
  done
}
```

**Comment by eval** [comment]
Thanks - I reworked it slightly to 1) catch non-exported/empty variables (which we had a few of 😳 ) and 2) to not exit and log all missing variables.

```bash
env_vars_required() {
  for var in "$@"; do
    if ! env | grep -q '^'"$var"'=\w'; then
      log_error "env var $var is required but missing/empty"
    fi
  done
}
```

Would it be something to have in the stdlib? If so, I'll happily submit a PR.

**Comment by zimbatm** [comment]
Yeah, something like that could be nice to have. Here is an even better version:
* avoid spawning `env | bash` on each var
* print all the missing envs, and return with error at the end
```sh
env_vars_required() {
  ret=0
  for var in "$@"; do
    if [[ -z ${!var:-} ]]; then
      log_error "env var $var is required but missing/empty"
      ret=1
    fi
  done
  return "$ret"
}
```
