### ISSUE TITLE
direnv allow resolves symlinks; direnv deny does not

### ISSUE THREAD

**Issue by mkhl** [direnv/direnv#850]
**Describe the bug**
i'd assumed that `direnv allow some/path` followed by `direnv deny some/path` blocks that .envrc again, but it does not if part of the path is a symlink.

**To Reproduce**
```
mkdir foo
ln -s foo bar
touch foo/.envrc
direnv allow bar
direnv deny bar
```

the deny call results in an error:
> direnv: error remove /home/mkhl/.local/share/direnv/allow/...: no such file or directory

**Expected behavior**
i expect `direnv deny bar` to block the file that `direnv allow bar` allowed.
instead `direnv deny foo` is required.

**Environment**
 - OS: Fedora Linux 35
 - Shell: fish
 - Direnv version 2.28.0

**Additional context**
this might be the same issue as #768, but i think the fact that `direnv allow` and `direnv deny` should work identically should give it more priority.

this problem popped up while working on the vscode extension. because of it, the extension currently cannot block the .envrc of a workspace with a symlink in its path.

**Comment by Elrolon** [comment]
Problem resolution
