### ISSUE TITLE
“dash” in variable name = error: not a valid identifier

### ISSUE THREAD

**Issue by notDavid** [direnv/direnv#853]
Hi there, please advise if this is a bug or a mistake on my side… escaping the `-` does not seem to help. Thank you :-)

**To Reproduce**
```
❯ #This works OK:
❯ echo export FOOBAR=foo > .envrc
direnv: error /private/tmp/direnvtest/.envrc is blocked. Run `direnv allow` to approve its content
❯ direnv allow .
direnv: loading /private/tmp/direnvtest/.envrc
direnv: export +FOOBAR

❯ #This causes an error:
❯ echo export FOO-BAR=foo > .envrc
direnv: error /private/tmp/direnvtest/.envrc is blocked. Run `direnv allow` to approve its content
❯ direnv allow .
direnv: loading /private/tmp/direnvtest/.envrc
./.envrc: line 1: export: `FOO-BAR=foo': not a valid identifier
```

**Environment**
 - OS: macOS 11.6
 - Shell: fish, version 3.3.1
 - Direnv version: 2.29.0

**Comment by zimbatm** [comment]
This is a bash limitation. If I try in the shell I get the same thing:
```
$ export FOO-BAR=1
bash: export: `FOO-BAR=1': not a valid identifier
```

**Comment by zimbatm** [comment]
See https://stackoverflow.com/questions/36989263/why-cant-environment-variables-with-dashes-be-accessed-in-bash-4-1-2

**Comment by notDavid** [comment]
So I misread the git documentation and `GIT-DIR` turned out to be `GIT_DIR`.

Apparently, dashes in environment variables are very uncommon, so this wil likely not be a problem and i’ll close this issue.
