### ISSUE TITLE
eval not executed

### ISSUE THREAD

**Issue by sirtris** [direnv/direnv#855]
**Describe the bug**
When ever I `cd` into my project directory I want a short `eval` statement to be executed.
More specifically I want to install the `hydra` tab completion with `eval "$(python run.py -sc install=zsh)"` as described in the hydra docs.  
The problem is that the tab completion does not work. Copying the statement in the command line works without issues. Also the `anaconda layout` in the `.envrc` file works fine.  

**To Reproduce**
cd into a project that uses hydra.  
copy `eval "$(python run.py -sc install=zsh)"`  into `.envrc` file

**Expected behavior**
Statement should be executed and tabcomletion should work

**Environment**
 - OS: Pop!_OS 21.04
 - Shell: zsh
 - Direnv version: 2.25.2

**Additional context**
I also replaced `zsh` with `bash` in `eval "$(python run.py -sc install=zsh)"` but that does not solve it.  
Putting `eval "echo "Hello World" " into the `.envrc` file executes as expected.

**Comment by zimbatm** [comment]
That's because direnv evaluates the .envrc in a bash sub-shell, and then only exposes env vars back to the host shell. That's part of the design and how we are able to support multiple shells and restore the original env when existing a project folder.

**Comment by sirtris** [comment]
Ok, thanks.  
Is there a workaround or any way I can get the desired behavior?
