### ISSUE TITLE
all error output exit paths should be prefixed with the text "direnv:".

### ISSUE THREAD

**Issue by pwaller** [direnv/direnv#87]
I just saw this in my terminal after running something long-running and error prone:

```
LoadConfig() Getwd failed: "getwd: no such file or directory"
```

"Crap!", I thought to myself. Then I realised it was just direnv since the directory I was in got deleted. Best to make it clear for others in the future.

**Comment by rvandanp** [comment]
can any one help me here ?
I am getting the same error

direnv: error LoadConfig() Getwd failed: "stat .: no such file or directory"
