### ISSUE TITLE
Make automatic `.env` load an opt-in feature rather than automatic

### ISSUE THREAD

**Issue by felipecrs** [direnv/direnv#880]
### **Is your feature request related to a problem? Please describe.**
So, as the conversation goes on in https://github.com/direnv/direnv/pull/845, it turns out to be very obvious that https://github.com/direnv/direnv/pull/845 was a breaking change which didn't receive a treatment of such (no major version bump, for example).

### **Describe the solution you'd like**
So, in order to keep 2.x version tree clean, I would suggest we make the automatic `.env` load an opt-in feature, rather than on by default.

The user could optionally opt-in by setting a global configuration for direnv (which I'm not sure how that could be achieved, perhaps `~/.direnvrc`?

### **Describe alternatives you've considered**
We could simply bump direnv version to 3, but... in fact I think it would be a very welcome addition to let users decide whether they want to use this feature (which is super useful for me) or not (which seems to be breaking some users cases).

### **Additional context**
None.

**Comment by hacfi** [comment]
Thanks @felipecrs .. that sounds great!! 

Maybe instead of a global configuration file it would be easier to introduce an environment variable that determines whether `.env` is used. Could be `DIRENV_DOTENV_ENABLE=1` (opt-in) for 2.x and then `DIRENV_DOTENV_DISABLE=1` (opt-out) in 3.x?

**Comment by piotrb** [comment]
yea this jumped out as a surprise for me .. I use other tools for working with .env files .. I'd rather not have something as low level as direnv automatically do this .. there is multiple problems with this .. since other tools .. like the dotenv gem for ruby has an override order, and env that comes from "outside" is considered HIGHEST .. so it will lead to incorrect behavior ..

**Comment by zimbatm** [comment]
Sounds good. I already merged #878 that makes it opt-out, but having it opt-in might be better to keep back-compat.

**Comment by phongnh** [comment]
Thanks for raising this issue @felipecrs . I have similar issue with the newest version. In my case, I use shared `.envrc` for repos under Github organization, something as follows. In each repo, we have Docker setup, therefor there is a `.env` file in each repo. When I cd to `repo1`, it is no longer load `.envrc` in parent folder. Need some way to ignore loading `.env` automatically.

```
/Users/phong/projects/org/
├── repo1
├── repo2
├── repo3
└── .envrc
```

**Comment by glensc** [comment]
maybe a better approach of this is to add syntactic sugar to .envrc that loads .env if present:

```sh
# the .envrc file
load_dotenv
```

**Comment by felipecrs** [comment]
> maybe a better approach of this is to add syntactic sugar to .envrc that loads .env if present:
> 
> ```sh
> # the .envrc file
> load_dotenv
> ```

This already exist :)

**Comment by zimbatm** [comment]
> This already exist :)

See https://direnv.net/man/direnv-stdlib.1.html#codedotenv-ltdotenvpathgtcode

Alright, so I decided to release v2.30.3 where you can set `skip_dotenv = true`.

**Comment by jankatins** [comment]
Somehow this doesn't work for me:

```
[21:59:55] λ  direnv --version
2.30.3

[22:05:01] λ  ls -la .env
-rw-r--r--  1 jankatins  staff  0 Jan  5 21:56 .env

[22:05:27] λ  cat $HOME/.config/direnv/direnv.toml
[global]
skip_dotenv = true

[22:05:40] λ  cd .. && cd
direnv: unloading
direnv: error /Users/jankatins/.env is blocked. Run `direnv allow` to approve its content
```

BTW: any chance still to make the reverse the default? This is the first setting I want for direnv, otherwise it worked out of the box...

**Comment by Jayfrown** [comment]
@zimbatm so where can I set `skip_dotenv = true` to stop direnv from loading `.env` files everywhere?

**Comment by mrmachine** [comment]
Please make a new release where an opt-in is required for `.env` handling. I just brew upgraded direnv and suddenly direnv wants to load all my `.env` files. Great to see this behaviour will be opt-in, but I am currently on the latest version so I'll have to downgrade and wait.

**Comment by Jayfrown** [comment]
@mrmachine you can opt-out globally so you don't have to downgrade. See my comment before yours.

**Comment by henrik242** [comment]
@Jayfrown @zimbatm Is it possible to put `skip_dotenv = true` in the `.envrc`? Or somewhere else in a project folder that I can commit?  (not in `$HOME/.config`)

**Comment by phongnh** [comment]
> @Jayfrown @zimbatm Is it possible to put `skip_dotenv = true` in the `.envrc`? Or somewhere else in a project folder that I can commit? (not in `$HOME/.config`)

You can set in `~/.config/direnv/direnv.toml` as follows:

```
03/11 17:12:19 caravan (master ?) (default)
$ cat ~/.config/direnv/direnv.toml
[global]
skip_dotenv = true
```

**Comment by henrik242** [comment]
As I said, *not* in the ~/. config folder. I need it to be set in my project folder (git repo), so that all users of that repo doesn't load .env files.

**Comment by felipecrs** [comment]
> @Jayfrown @zimbatm Is it possible to put `skip_dotenv = true` in the `.envrc`? Or somewhere else in a project folder that I can commit? (not in `$HOME/.config`)

If you have a .envrc, direnv won't read .env.

**Comment by henrik242** [comment]
> If you have a .envrc, direnv won't read .env.

True, but direnv will try to read `.env` files in subfolders in the project.  We're using `.env` for configuring docker-compose in various subfolders of the project, and don't want to have to do a `direnv allow` (or deny) for all of them.

**Comment by felipecrs** [comment]
Got it. In this case we either make `.env` load not enabled by default, or we allow `.direnvrc` to be defined in the project root so that one can put `skip_dotenv = true` in it.

The first was already extensively discussed, and it was decided against it. So, I suggest you open a new issue for the second approach.

**Comment by henrik242** [comment]
OK, will do. Thanks for spending time on this!

**Comment by henrik242** [comment]
@felipecrs Done: https://github.com/direnv/direnv/issues/908

**Comment by henrik242** [comment]
By the way, there's no `DIRENV_DOTENV_DISABLE` variable available, right? That automatic `.env` include is really breaking things for us...  🤞🏻  for #908
