### ISSUE TITLE
Support `guix shell`

### ISSUE THREAD

**Issue by fishyfriend** [direnv/direnv#888]
**Is your feature request related to a problem? Please describe.**

The direnv stdlib's `use guix` command wraps `guix environment`. However, `guix environment` has recently been [deprecated][1] in favor of `guix shell`.

[1]: https://guix.gnu.org/en/blog/2021/from-guix-environment-to-guix-shell/

**Describe the solution you'd like**

A new `use guix_shell` command that passes its arguments along to `guix shell --search-paths` and updates the current environment accordingly. This is exactly what `use guix` does, but with a different underlying Guix command.

In addition, to avoid confusion about which Guix command a user intends, perhaps a new `use guix_environment` command could replace `use guix`.  `use guix` would continue to work as currently, but would also output a deprecation warning describing the reason for deprecation and suggesting to use either `guix_shell` or `guix_environment` instead.

**Describe alternatives you've considered**

`use guix` could simply wrap `guix shell`. This would break some existing scripts since `guix environment` and `guix shell` have different syntax. Users wishing to continue using `guix environment` would have to write `eval $(guix environment ARGS --search-paths)` explicitly.

**Comment by zimbatm** [comment]
Makes sense.

Do you have some pointers on how long ago `guix shell` was introduced? If it's more than one year, it's probably safe to just change the default as developers would most likely be on fresh machines.

**Comment by fishyfriend** [comment]
Based on Guix's blog and commit log history it looks like `guix shell` arrived in late October 2021.

**Comment by fishyfriend** [comment]
@zimbatm, thinking further about your comment, would it work to just wait till a year has passed (so late Oct. 2022) and change `use guix` to use `guix shell` at that time?

One could optionally add a warning message to `use guix` in the meantime, advising users that its behavior will be changing and to replace it with `eval $(guix shell ARGS --search-paths)` if they wish to use `guix shell` prior to the change being made.

Let me know what you think; I'd be happy to submit a PR for this or whatever solution is agreed upon.

**Comment by zimbatm** [comment]
Do you know how often Guix SD is getting released? If it's every 4 months, then we can wait for 6 and that should be enough. Hopefully, they won't have removed the deprecated method by then.

**Comment by fishyfriend** [comment]
Guix is rolling-release but announces an official version roughly every 6 months (latest, v1.3.0, was May 2021). I would guess most users stick to the rolling release as that is the default configuration. So, most will already have `guix shell` available.

Also, it appears from [Guix docs](https://guix.gnu.org/manual/devel/en/html_node/Invoking-guix-environment.html) that `guix environment` will stick around till May 1, 2023. (Wish I'd seen that sooner&mdash;sorry!)

**Comment by zimbatm** [comment]
The best thing to do is add the command to the Wiki for now

**Comment by fishyfriend** [comment]
Sounds good, I've added a [note](https://github.com/direnv/direnv/wiki/GNU-Guix#moving-from-guix-environment-to-guix-shell) to the wiki. Thanks!

**Comment by haplo** [comment]
Just as a note [Guix 1.4 was released](https://guix.gnu.org/en/blog/2022/gnu-guix-1.4.0-released/) on Dec 19th. Personally I would like to see support for `guix shell` sooner rather than later, but I understand it's not nice to break other people's setups.

**Comment by ieugen** [comment]
I think this was fixed in https://github.com/direnv/direnv/pull/1045

**Comment by fishyfriend** [comment]
Indeed it was! Thanks.
