### ISSUE TITLE
Provide a strict_env compatible version of source_up

### ISSUE THREAD

**Issue by jfly** [direnv/direnv#913]
(This request is very similar to https://github.com/direnv/direnv/issues/728, but with `source_up`)

Right now, `source_up` searches upwards (using `find_up`) until it finds a file. If it doesn't, it exits 1, and if you've got `strict_env` turned on, loading the `.envrc` file immediately stops.

Is this intentional? The [docstring on `source_up`](https://github.com/direnv/direnv/blob/abdd443bd5477557509e969e17f74244fec2c55b/stdlib.sh#L419-L423) sort of makes it sound like maybe it was intended to happily ignore missing files?

> Loads another ".envrc" if found with the find_up command.

If it *is* intentional that `source_up` exits nonzero when there's no ancestor file, how would you feel about a PR adding a new `source_up_if_exists` method?

**Comment by zimbatm** [comment]
The exit status is intentional to be able to distinguish if a file was loaded or not.

I don't mind having `source_up_if_exists` being added. A simple workaround is to use `source_up || true`.

**Comment by Zebradil** [comment]
I spend some time trying to figure out why my `.envrc` doesn't export variables. For me it could've been helpful to see an error message about failed `source_up`.

**Comment by jfly** [comment]
@Zebradil check out https://github.com/direnv/direnv/pull/921, I think it'll make that situation a little better.

**Comment by Zebradil** [comment]
@jfly yes, that looks great, thank you!
