### ISSUE TITLE
direnv: error .envrc or .env file not found

### ISSUE THREAD

**Issue by mhenrixon** [direnv/direnv#916]
**Describe the bug**
Since the latest upgrade direnv won't load my `.env` files anymore.

**To Reproduce**

1. Upgrade to latest version
2. Try to use direnv

**Expected behavior**
I was expecting my `.env` files to be loaded

**Environment**
 - OS: macOS latest
 - Shell: fish
 - Direnv version: 2.31.0 

**Additional context**

```
direnv allow .env
direnv: error .envrc or .env file not found
```

The file is there but it won't load. Someone said I now need to use fish syntax in my .env file which for shared project configuration in a multi-user repository just isn't feasible. direnv ends up being completely unusable unfortunately. Even if I move the changes to a `.envrc` they aren't loaded.

**Comment by zimbatm** [comment]
Unfortunately, I had to make that feature optional as it was breaking back-compat for most users.

There is a new config option that you can use to toggle that feature back on: https://direnv.net/man/direnv.toml.1.html#codeloaddotenvcode

```toml
[global]
load_dotenv = true
```

**Comment by mhenrixon** [comment]
```
brew extract --version=2.30.2 direnv homebrew/cask
brew install direnv@2.30.2
```

Also does the trick, not even putting the configuration inside a `.envrc` works for me. I've tried both bash syntax and fish syntax but it errors regardless. No environment variables are added to my shell anymore.

**Comment by zimbatm** [comment]
The configuration should be added to `~/.config/direnv/direnv.toml`

**Comment by binderup** [comment]
I also spend some time today trying to figure out why direnv had stopped working for me.

Creating a config file as described above with the load_dotenv value reenabled the previous functionality (for me at least).

**Comment by knowsuchagency** [comment]
It would be nice to add this to the documentation. I found this issue upon running into the same error on my machine

**Comment by knowsuchagency** [comment]
I think this ought to be made more prominent in the docs or even the homepage. I'm willing to bet most Mac users are going to run into this and some may not make it so far as this issue before giving up. I almost did

**Comment by zimbatm** [comment]
Yeah, sorry about the back-and-forth. I made a mistake. The point on the error message is also a good one if anybody wants to send a PR?

**Comment by dreki** [comment]
This should've been a major version bump.

**Comment by 1Mark** [comment]
This also broke for `zsh`
`mv .env envrc` worked but this isn't feasible.

**Comment by anshajk** [comment]
Thankfully found this issue and was able to fix my own environment by adding it to `~/.config/direnv/direnv.toml`

**Comment by doctaphred** [comment]
> Yeah, sorry about the back-and-forth. I made a mistake. The point on the error message is also a good one if anybody wants to send a PR?

@zimbatm How'd I do? :) https://github.com/direnv/direnv/pull/941

**Comment by judy** [comment]
@doctaphred Much appreciated, I think this will be a great solution to the complaint I raised earlier. I don't read/write Go either, so I can't comment on the PR, but the language looks perfect.

**Comment by kris-luminar** [comment]
> mv .env envrc

it was `.envrc` for me, not `envrc`

**Comment by 1Mark** [comment]
> > mv .env envrc
> 
> it was `.envrc` for me, not `envrc`

Typo, original message fixed.

**Comment by sud0pacman** [comment]
If you are using nix, open the **.envrc** file in the root of your project and type 

> use flake

 in it and then re-enable `direnv allow`
