### ISSUE TITLE
Spurious direnv variables

### ISSUE THREAD

**Issue by pwaller** [direnv/direnv#94]
Here is a session which started out with an empty environment:

```
~$ mkdir test
~$ cd test
~/test$ touch .envrc
direnv: export +DIRENV_DIFF +DIRENV_DIR +DIRENV_MTIME
direnv: error .envrc is blocked because unknown. Run `direnv allow` to approve its content.
~$ cd
~$ cd test
direnv: export +DIRENV_DIFF +DIRENV_DIR +DIRENV_MTIME
direnv: error .envrc is blocked because unknown. Run `direnv allow` to approve its content.
~/test$ direnv allow
direnv: reloading
direnv: loading .envrc
direnv: export ~DIRENV_DIFF ~DIRENV_MTIME
~/test$ cd ..
direnv: unloading
direnv: export -DIRENV_DIFF -DIRENV_DIR -DIRENV_MTIME
~$ cd test
direnv: loading .envrc
direnv: export +DIRENV_DIFF +DIRENV_DIR +DIRENV_MTIME
```

Why am I seeing `DIRENV_*`?

I'm running the master branch.

**Comment by Hubro** [comment]
@zimbatm Sorry for the necro, but you talked about hiding exported environment variables to avoid noise, I am having this exact problem with nix-direnv:

https://github.com/nix-community/nix-direnv/issues/278#issue-1515191528

It's pumping out every environment variable that nix-shell sets, which is a big ugly wall of text.

Can I configure direnv to ignore (be quiet about) a list of environment variables somehow? Or is this mechanism internal only?
