### ISSUE TITLE
PS1 Doesnt get updated with conda activate

### ISSUE THREAD

**Issue by tospe** [direnv/direnv#945]
**Describe the bug**
I have a .envrc in a project folder with the following.

```
eval "$(conda shell.bash hook)" 
conda activate torch 
```

When i enter that folder my the variables are correctly loaded. However make PS1 doesn't reflect the change. In the image bellow we see (base), yet the $CONDA_DEFAULT_ENV is torch.

![imagem](https://user-images.githubusercontent.com/49151314/169034524-954beac8-cc01-4fa7-b777-e1be9765e94b.png)

**To Reproduce**
Conda ready to use.

Folder with .envrc  with 
```
eval "$(conda shell.bash hook)" 
conda activate <your-env>
```

Move to directory and see the variables being loaded. 

**Expected behavior**
PS1 should reflect the active conda env 

**Environment**
 - OS: Ubuntu 20.04 (wsl)
 - Shell: bash
 - Direnv version: 2.31.0

**Comment by zimbatm** [comment]
See https://github.com/direnv/direnv/wiki/PS1 and #529
