### ISSUE TITLE
`direnv exec` has started writing ANSI escape sequences to stderr when stderr isn't a terminal

### ISSUE THREAD

**Issue by frou** [direnv/direnv#953]
**Describe the bug**

Hi there - It seems like a recent version of direnv has started making a classic mistake that many programs do, and is unconditionally writing ANSI escape sequences :)

**To Reproduce**

`$ direnv exec . true 2>x.txt`

Then open x.txt in a text editor and see that it starts with

`\x1B[mdirenv: loading`

**Expected behavior**

When writing to either of stdout/stderr, if they aren't a terminal/TTY then ANSI escape sequences shouldn't be written. So the file x.txt in the example should simply start with:

`direnv: loading`

**Environment**
 - OS: macOS 12
 - Shell: bash
 - Direnv version: 2.32.0

**Comment by tmatilai** [comment]
> It seems like a recent version of direnv has started making a classic mistake that many programs do, and is unconditionally writing ANSI escape sequences :)

Agreed that it should check the TTY. The error messages have been printed in red for quite some years, but I guess this came visible to you because of #884 adding the reset code for status log messages.

**Comment by zimbatm** [comment]
Also, I removed the dependency on `tput`, which might have done the job for us.
