### ISSUE TITLE
(Question) does direnv store a list somewhere of paths that have been allowed?

### ISSUE THREAD

**Issue by venteto** [direnv/direnv#954]
If so, where is this storage location, and when does it expire?

I wonder this because I am testing a script to automate provisioning of a Python project which uses both direnv for environment variables, and the native Python 3 `venv` module (which is `source`d manually in the `.envrc` file, rather than using `layout_python3`, because my template allows me to change the venv _prompt_ to the project name).

So I end up running the script, then deleting the new test directories it creates, in a pretty short amount of time. Every time I re-run my script, I accept its default `cookiecutter` template config values, so my new test project path never changes. One step in my script is `direnv allow`.

Now sometimes, after I delete the last version of the scaffolded test project directory, then run my script again after modifying it a bit, I `cd` into the test directory, whose path has not changed, and for some reason I do not have to run `direnv allow` — somehow, it is **_already_** allowed. It is as if I never deleted the _**previous**_ iteration of the same-named directory.

I don't know if this is a factor in _another_ problem I am having or not (but I'd like to eliminate it as a possibility), but sometimes when I run the script, the non-venv environment variables are loaded, and sometimes they are not, which causes parts of the script to fail (e.g., `manage.py` commands expecting environment variables).

**Comment by lafrenierejm** [comment]
From https://direnv.net/man/direnv.1.html#files:

> `$XDG_DATA_HOME/direnv/allow`: Records which `.envrc` files have been `direnv allow`ed.

**Comment by venteto** [comment]
@lafrenierejm thank you, that location is what I needed to know, I feel bad for missing that bit of info in the docs. Now I can go in and clean out that folder if and when I need to on occasion.
