### ISSUE TITLE
Unable to use VIRTUAL_ENV to control where the venv is created

### ISSUE THREAD

**Issue by ssbarnea** [direnv/direnv#956]
**Describe the bug**

While defining VIRTUAL_ENV was [documented (for older versions)](https://github.com/direnv/direnv/wiki/Python) as a way to control where direnv is creating the virtualenv and its name, it seems to have no effect for the current `layout python` option.

**To Reproduce**

```shell
# .envrc
# This VIRTUAL_ENV value is also configured inside .vscode/settings.json:
export VIRTUAL_ENV=out/.$HOSTNAME

# Activate virtualenv (creates it if needed)
layout python
source_up
```

What you endup with is something ugly and not useful like:
```
which -a python
CWD/.direnv/python-3.11.0b3+/bin/python
```

**Expected behavior**
Get a virtualenv inside out/ folder that depends on the machine name.

**Environment**
 - OS: macOS
 - Shell: zsh
 - Direnv version 2.32.0

**Additional context**

Please keep in mind that we really need to inject the hostname in the path of the created virtualenv so we can still use these on mounted folders cross platform (venvs not being portable).

**Comment by ssbarnea** [comment]
Apparently the value of `direnv_layout_dir` is hardcoded and I cannot control it.

**Comment by ssbarnea** [comment]
Sorry, I did not see that was fixed in yesterday release. I update tools often but not really daily ;)

**Comment by zimbatm** [comment]
no worries :) regarding `direnv_layout_dir`, you can re-define the function so it outputs something different. Eg:

```
direnv_layout_dir() {
  echo "$HOME/.cache/direnv/hello"
}
```
