### ISSUE TITLE
How to reload the .direnvrc file?

### ISSUE THREAD

**Issue by dcunited001** [direnv/direnv#959]
**Is your feature request related to a problem? Please describe.**

I'm having trouble modifying behavior in my direnvrc extensions, which is slowing me down quite a bit. services like my emacs server are loaded only once X11 starts (which is something i need to address), but i have to close everything down to make one change.

i've tried googling it, searching the repo and skimming the source, but i'm not sure. almost every page and issue references direnvrc one way or another. i think direnv is caching the function definitions and doesn't reload what is already defined.

`eval $(direnv hook bash)` is loaded in `.bashrc`, but once it's loaded, then no matter what I do, i can't get direnv to recognize changes to `use_fdsa()` funcions in direnvrc without logging in or out. 

**Describe the solution you'd like**

some advice on how to reload direnvrc without logging in and out.

**Describe alternatives you've considered**

- using `watch_file`, which only reloads the files with `watch_file` statements. i haven't tried putting a watch_file in the direnvrc, but that's a direnv directive, so i don't think it will work

- loading `eval $(direnv hook rc) from within terminator or alactritty. however, i'm using direnv-mode in emacs and there are other scripts/services where I'd like them to load the `.envrc`. more granular control over which sessions load the direnv hooks would be nice eventually, but for now, I just want it loaded by default in .bashrc. i'll differentiate it later.

- sourcing direnvrc from within a shell. this would allow a single shell to have its bash functions loaded. this works, but again, i think direnv is caching the function definitions. the updated definitions are available to me within the shell session, but then direnv loads

- searching for function definitions using `declare -F` or `typeset -f`, but i don't know enough about these to find the functions. 

- blowing away the cache in `$XDG_DATA_HOME/direnv/*`, but this is just a list of hashed .envrc files. direnv is internalizing its state somewhere.

**Comment by joshbode** [comment]
Have you tried `direnv reload`?

```
$ direnv --help
...
reload:
  triggers an env reload
...
```

However, I believe this only reloads the `.envrc` file, not the shell hook.

I'm also not seeing the same issue on my setup - I can change `~/.config/direnv/direnvrc` and have the changes apply without needing to reload the hook.

**Comment by dcunited001** [comment]
thanks. that's how i had initially expected it to work. there may be something different on my system.

most of the examples in the direnv docs don't export environment variables. is this required? i was testing by changing environment variables within my direnvrc use funcitons. when the .envrc references the use function, then when i export these variables, i see the changes in my environment. 

if env variables unexported in the `use_xlang()` functions dont ever end up in the environment after direnv calls `use xlang`, then i may have been confused, as I have some variables duplicated -- partially bc i'm in the middle of iterating on functionality and partially because i'm testing direnv.

**Comment by joshbode** [comment]
do you have any examples of what you're trying that you can share?
