### ISSUE TITLE
`direnv: ([/usr/bin/direnv export zsh]) is taking a while to execute.` in a mounted drive with no `.envrc`.

### ISSUE THREAD

**Issue by zmrocze** [direnv/direnv#961]
**Describe the bug**

I plug my huawei phone for data read with usb. It appears in `/run/user/1000/gvfs/mtp:host=HUAWEI_MAR-LX1A_some_number/` and when I `cd` into it then direnv runs for a moment with 
`direnv: ([/usr/bin/direnv export zsh]) is taking a while to execute. Use CTRL-C to give up.`

It very likely is expected, but I don't understand why direnv would run there. It gets me anxious as I don't want huawei thing to run scripts. Could you help me understand what happens?

**To Reproduce**
 - plug phone with usb 3
 -  cd into `run/user/1000/gvfs/mtp:host=HUAWEI...`
 - wait for direnv

**Expected behavior**
I expect direnv not to run ever if I don't traverse a directory that was earlier `allowed`.

**Environment**
 - OS: manjaro
 - Shell: zsh
 - Direnv version: 2.31.0

**Additional context**
In `.zshrc` I have `eval "$(direnv hook zsh)"`.

**Comment by zimbatm** [comment]
On every shell problem, direnv looks for `.envrc` files in the current and parent directories. That's how it knows if it should ask you to allow in the first place. So don't worry, it won't load an environment before asking you, but it still needs to look for the files if they exist.

Most likely, gvfs is very slow, and every `stat` takes a while to answer, and the deeper you go under the filesystem, the slower it will get.

The global direnv config has a `[whitelist]` config, but not blacklist. It's a feature that would need to be added to automatically ignore a given path prefix.

**Comment by zmrocze** [comment]
ah, alright. If i can request a feature:
 - easiest for me there would be `DIRENV_NOSEARCH=1 cd ...` eventhough im not fan of ux via environment variables

Thanks for explaining. Ill close this, right?
