### ISSUE TITLE
Exporting variables with `?` (question mark) does not take effect immediately

### ISSUE THREAD

**Issue by saivenky** [direnv/direnv#989]
**Describe the bug**
Exporting variables with `?` (question mark) does not take effect until after the entire `.envrc` file has been processed.

**To Reproduce**
Create `.envrc` with:
```
export value=$(echo '123?')
echo Value is $value
export derived=$value
echo Derived is $derived
```

**Expected behavior**
The two `echo` statements should print `123?` but instead they both print empty string.
Expected:
```
Value is 123?
Derived is 123?
```

Actual:
```
Value is
Derived is
```

Note:
* Echoing `$value` _after_ the `.envrc` has been processed looks okay.
* `$derived` continues to be an empty string.

**Environment**
 - OS: macOS Monterey
 - Shell: bash
 - Direnv version 2.32.1

**Additional context**
-

**Comment by zimbatm** [comment]
It's because Bash applies globbing after variable expansion. It will look for a file that start with `123` and has one extra character.

Make sure always to put quotes around variables to avoid that behaviour.

```sh
export value=$(echo '123?')
echo "Value is $value"
export derived=$value
echo "Derived is $derived"
```

A good tool to enforce this is [shellcheck](https://shellcheck.net)

**Comment by saivenky** [comment]
Thanks! This was precisely the issue.
